### PR TITLE
G1 2021 #10313

### PR DESCRIPTION
**Pull request by a19frebo**
Removed the code that was not used regarding feedback, both from the students view and the teachers view.

### CODE REVIEW

**Review by a13zanal — CHANGES_REQUESTED** [review]
In mobile mode, "Teacher feedback" is still there for both student and teacher in "rapport" dugga, otherwise it looks good.

**Review by b19ponka — CHANGES_REQUESTED** [review]
**dugga.js**
Remove table head for Teacher feedback if (mobileMediaQuery.matches). Row:1626, 1628, 1632
Remove empty table cell for Teacher feedback. Row: 1719-1744

**showDuggaservice.php**
Remove feedback variable from array. Row: 464,468-475,520

**Review by a13zanal — APPROVED** [review]
Looks fine, good job!

**Review by b19ponka — APPROVED** [review]
Looks good, well done!

**Pull request merged**
