### PR TITLE
Changed the error message when entering the incorrect MOTD

### PR DESCRIPTION
**Pull request by a18jenro**

### CODE REVIEW

**Comment by a18jenro** [comment]
@b18emigu Updated the message to "Message can only contain 50 symbols and non-nordic letters".

**Comment by b18emigu** [comment]
Can you please have a look at the branch conflicts before i review again? @a18jenro

**Comment by a18jenro** [comment]
@b18emigu Fixat!

**Comment by b18emigu** [comment]
Looks good now!

**Pull request merged**
