### PR TITLE
Fixed issue #6377: Move cursor was displayed when it should not be

### PR DESCRIPTION
**Pull request by a16jenja**
Issue: #6377 

Fixed the issue when hovering over a umlline and when trying to draw lines between entities it would show a move cursor. Now it shows the default cursor when these actions are being done.

### CODE REVIEW

**Comment by a16jenja** [comment]
I noticed this too, and I think you are right, I'll get on it.

**Comment by a16jenja** [comment]
I noticed that you can still move the lines between uml entities, but the cursor is now default. But changing the lines to be static might be a separate issue from this one in my opinion.

**Comment by a17jacsv** [comment]
> I noticed that you can still move the lines between uml entities, but the cursor is now default. But changing the lines to be static might be a separate issue from this one in my opinion.

I agree. Please create an issue of these problems and we'll merge this PS for now.

**Comment by a17jonro** [comment]
The conflict wasn't resolved correctly so the wrong changes were implemented and then merged, this needs to be fixed.

**Comment by a16jenja** [comment]
Agreed, I created a new issue regarding this since I did not know what to do since its been merged already.

**Pull request merged**
