### PR TITLE
G1 2023 v2 #13057 state diagram state

### PR DESCRIPTION
**Pull request by b21eriho**
Added a state that gets preloaded, it cannot be edited yet though if copy-and-pasted lines can be drawn between states. The rounded corners are not quite right but it's the best I can come up with for now, they should maybe be done using an svg-path instead of a rect.

### CODE REVIEW

**Comment by b21eriho** [comment]
On lines 785 and 801 this issue will conflict with issue #13215 , the changes from that issue are better and will not break anything in this issue and as such they should be used in the merge

**Review by b21matfi — COMMENTED** [review]
looking at the issue it looks like it should be a button for the state and then the "drawing"part but i don't see the button is it something i missed?

**Comment by b21eriho** [comment]
https://github.com/HGustavs/LenaSYS/issues/13057

I can't say I entirely understand what you mean, the issue is to create the shape

**Comment by b21matfi** [comment]
i was just unsure if the issue was to create the shape or the button. Got a little confused when reading the issue.
i will review the issue

**Comment by b21eriho** [comment]
The button was temporarily removed during a merge-conflict but is being re-added in another issue that is currently in the works

**Comment by b21matfi** [comment]
alright perfect, thank you and it looks good

**Review by b21matfi — APPROVED** [review]
The shape looks good.

**Comment by c21adano** [comment]
Related: #13338 
 I fix the small conflict, nothing major. It was with the elementtype number that were conflicting, i went with the numbers used by #13338 due to it changing the numbers in the diagaram.php file too.

**Pull request merged**
