### PR TITLE
Fix resizing objects in diagram - #6180

### PR DESCRIPTION
**Pull request by c17matjo**
#6180

### CODE REVIEW

**Comment by c17matjo** [comment]
Okej. Jag har lagt till ett call till updateGraphics() som jag tror borde fixa problemet. Testa nu

**Comment by c17matjo** [comment]
I talked with @a17drama and we decided that since this is a minor bug and since the problem described in the issue was solved, a new issue should be created for the new bug.

**Comment by a17jacsv** [comment]
> I talked with @a17drama and we decided that since this is a minor bug and since the problem described in the issue was solved, a new issue should be created for the new bug.

I'll merge this and the bugs will be resolved in another issues.

**Comment by a14oscna** [comment]
Alright, looks good then!

**Pull request merged**
