### PR TITLE
deleted commented out code

### PR DESCRIPTION
**Pull request by c17alepe**
There shouldnt be any trouble, but heres a test site just in case

#6439 

https://c17alepe.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursevers=97732

### CODE REVIEW

**Comment by a17pongo** [comment]
@c17alepe did you check why this code was commented and if it potentially could be used anywhere?
this is important to check before removing code even though it was commented

**Comment by c17alepe** [comment]
@a17pongo It seems like it was alternative code for a solution and has a version of it working directly above it

**Comment by a17pongo** [comment]
looks like a + sign was added accidentally in the commit

**Comment by c17alepe** [comment]
@a17pongo its githubs + sign for the row added, just like the red ones with - signs. the row is empty for visual reasons. weird place for github to place the + and - signs either way.

**Comment by a17amama** [comment]
Checked the code and it looks fine. The code that was commented out was, as already stated, just an alternative  for the already functioning code, removing it does not cause any issues and it is approved for merge.

**Pull request merged**
