### PR TITLE
Change the swimlane text color

### PR DESCRIPTION
**Pull request by a19samke**
Change the swimlane text color from blue to darkblue !

@a18danli

### CODE REVIEW

**Review by a19isada — CHANGES_REQUESTED** [review]
The colour is very close to black and from what I interpreted, the colour should not be black.

**Review by a18willi — CHANGES_REQUESTED** [review]
The new color is not used anywhere else on lenasys which might make it seem out of place. But the biggest issue is that @a19anjst specifically mentioned thet the text should not be black which the new color seems to be very close to.

**Review by a19isada — APPROVED** [review]
Looks good. Much clearer distintion from black than before.

**Review by a18willi — APPROVED** [review]
Looks much better now

**Pull request merged**
