### PR TITLE
Fix for issue #6166: Make variables more readable by adding values ​​to attributes

### PR DESCRIPTION
**Pull request by a17jonro**
#6166 
I believe that i've changed the most important variables, however if there are more that should be added feel free to request them.

### CODE REVIEW

**Comment by a17jacsv** [comment]
Looking good. @a17jonro please resolve the conflicts here in Github. It's best you do it as you have written the code. Otherwise, it looks good 👍

**Comment by a17jonro** [comment]
@a17jacsv The conflicts should be resolved now.

**Comment by a17jacsv** [comment]
Perfekt! Well done! 👍

**Comment by a17jacsv** [comment]
Reverts #6273.

This issue caused problems with the diagram. The resolved conflicts did some damage. Please look into this.

**Pull request merged**
