### PR TITLE
Assignments localstorage

### PR DESCRIPTION
**Pull request by b18jacha**
Assignments without variants no longer saves to localstorage

Co-author
b18jacha
e15marol

### CODE REVIEW

**Review by a19frebo — CHANGES_REQUESTED** [review]
Seems like duggas with only 1 variant is still stored in local storage. 

row 244, what is really checked here?

**Comment by e15marol** [comment]
> Seems like duggas with only 1 variant is still stored in local storage.
> 
> row 244, what is really checked here?

For the first question, the variants still need to be stored if they are within the scope of the amount of assignments that exist. Meaning that assignments with variants are stored in local storage as we need to keep track of which dugga the user first gets when accessing the dugga page. It is only assignments that have variants, that are saved to local storage.

For the second question, the largest variant.quizID is checked against the dugga IDs, this is so we include all assignments that have a variant assigned.

**Comment by a19frebo** [comment]
I thought that a dugga with 1 variant is a dugga with "no variants". Doesnt a dugga need a variant to even be displayed?

**Comment by b18jacha** [comment]
I don't think a dugga has to have a variant but unsure. But if it doesn't have one it will not save to localstorage with value "UNK" as it did before.

**Comment by a19rebsa** [comment]
This solution works fine, might create an issue later for if there is only one variant we might not want to store it in local storage.

**Review by a19frebo — APPROVED** [review]

**Review by a19kevkh — APPROVED** [review]

**Pull request merged**
