### PR TITLE
added model and text

### PR DESCRIPTION
**Pull request by b21antbr**
Hopefully code is understood, variables and functions in model, inputs and outputs in .txt

### CODE REVIEW

**Comment by a19hakja** [comment]
Nice, assigning a reviewer!

**Review by b21ricni — COMMENTED** [review]
We approve of the model and text, but we are uncertain how they are made. So we could be wrong

**Comment by a19hakja** [comment]
cool, merging

**Comment by b21kurar** [comment]
issue #12971

**Pull request merged**
