### PR TITLE
G2 2023 v2 issue #13292

### PR DESCRIPTION
**Pull request by c21alest**
Related to #13292

Converted PDF to MD

### CODE REVIEW

**Comment by c21alest** [comment]
Should PDF not be deleted maybe?

**Comment by d21erisu** [comment]
Delete the PDF

**Review by d21erisu — CHANGES_REQUESTED** [review]
Great! Just change the name to FRD_profileservice.md and make sure that the PDF is deleted :)

**Comment by c21alest** [comment]
Changed file name

**Review by d21erisu — APPROVED** [review]
Boss! Great job ;)

**Pull request merged**
