### PR TITLE
Don't allow clicking on save button if there's nothing to save #14113

### PR DESCRIPTION
**Pull request by b21oscpe**
The function I made checks if data[] == 0 which means the container is empty or if the historyindex is -1. It is called whenever the mouseUp event is triggered. It should work with both ctrl+z and removing elements. The buttons is set to "disabled" (only by css) by default.

### CODE REVIEW

**Review by a21oligu — CHANGES_REQUESTED** [review]
When loading a diagram, the save buttons appears as disabled but will still allow the user to open the save-modal. There is also nothing that prevents the user from saving the same diagram twice, with zero changes made to it the second time.

**Comment by b21oscpe** [comment]
How is this replicated? For me the modal doesn't show up and an error message is shown.

**Comment by a21oligu** [comment]
> How is this replicated? For me the modal doesn't show up and an error message is shown.

This is also the case for me, except for when you load a diagram with the load button. After the diagram the loads, the button appears as disabled but will still open the modal on click.

If you save your changes, you can press the save button again. That is, you can save even though no changes has been done since the last save.

**Comment by b21oscpe** [comment]
I have now fixed so that it does not say you shouldn't be able to save if you load in a diagram, @b21eriho or @b21phiro should decide if this is ok or not. The problem with this is that the function currently checks if data.length == 0 (no elements on the canvas) OR currentHistoryIndex == -1 which means it was just loaded in and no changes have been made. However, when you load in a diagram there are elements on the canvas and the historyIndex is saved from the last time the diagram was edited. I do not know what other condition could be used to check this without creating uneccessary variables / setting the currentHistoryIndex to 0 once you load a diagram

**Comment by b21eriho** [comment]
That is fine, The implementation you have made is still a good improvement

**Review by a21oligu — APPROVED** [review]
Good job!

**Pull request merged**
