### PR TITLE
Grupp a2019 w19#6457

### PR DESCRIPTION
**Pull request by a16tobfr**
#6457 
The toolbar is now moved to the left and seems to work as intended.
Moved canvas to the right to make room for the toolbar
Changed size of the toolbar
Removed the minimize toolbar functionality
Removed the align toolbar horizontal functionality
Removed unnecessary functions

### CODE REVIEW

**Comment by a16tobfr** [comment]
fixed

**Comment by a17johpe** [comment]
There are some small design fixes that can be added to a separate issue. The base fix looks good and nothing seems broken on the webpage or in the code

**Comment by a17johpe** [comment]
Design fixes:
- undo and redo buttons preferably on same row
- Tooltips on hover over button should be moved slightly as it currently covers the undo/redo buttons slightly (see image)
toolbarposition
- On Firefox, the header for UML mode is clashing slightly with the next header (see image)
toolbardialog

**Comment by a14oscna** [comment]
Remember to create new issues. I will merge this now.

**Pull request merged**
