### PR TITLE
G3 2022 w4 #11628

### PR DESCRIPTION
**Pull request by b20jonlu**
Partial solution for https://github.com/HGustavs/LenaSYS/issues/11628
The basic functionality for showing commit changes when hovering over a commit link is now in place and it is possible to view what lines were changed by a certain commit. More work is still needed in order to implement the feature in a more refined state. 
Image of what the window looks like when hovering over the commit link. 
Screenshot (15)

### CODE REVIEW

**Comment by a20behta** [comment]
current implementation seems to remove filter buttons in header, other views of contribution and pushes the pop up on top of the other contribution information

https://user-images.githubusercontent.com/102468604/164717634-baca7f1b-324b-4f32-a5d5-7e8aca190a42.mp4

video above shows issue clearer

**Comment by b20jonlu** [comment]
@a20behta i don't think it was this branch which caused this issue since the hover element is the one that is inside our weekly branch #merge4. My implementation is responsible for the text inside the window, i only changed the function called by the on mouseover and added overflow protection for the text which shouldn't be the cause. From testing the weekly branch i think this issue might also be there so if you could also test it that would be helpful

**Comment by b20jonlu** [comment]
oh you might have tested the wrong branch
there is a w3 version that was made by eric i am on the w4 version

**Comment by a20behta** [comment]
issue seems to only occure on the webserver and not locally

**Pull request closed without merging**
