### PR TITLE
Fixed the toggle on A4 holes - Fix for #6012

### PR DESCRIPTION
**Pull request by a14oscna**
Toggling the virtual A4 holes is not dependant on if the virtual A4 is toggled on or off.
Added styling for when the option is disabled, hover effect also removed when disabled.
disabled option
Fix for #6012

### CODE REVIEW

**Comment by a14oscna** [comment]
While I agree that my solution may not be the best, i strongly disagree that hiding the option completely is a better solution. Perhaps we could show the dependency in another way?

**Comment by a17jonro** [comment]
Yes, just making it more obvious that the 'virtual a4 hole' option is tied to the 'display virtual a4' and therefore minimizing confusion while retaining the button itself would work great.

**Comment by a17jonro** [comment]
This is great, but unfortunately this has slightly broken the checkbox on the 'Toggle A4 Holes' button.
image

**Comment by a17jacsv** [comment]
Looking good. Works as expected. Nice job!

**Pull request merged**
