### PR TITLE
Grupp b2019 w17#6022

### PR DESCRIPTION
**Pull request by a17amama**
Moved searchbar in resulted to separate it from the rest of the content and make it less awkward
#6022

### CODE REVIEW

**Comment by b17timjo** [comment]
The CSS change will alter the search bar position in both resulted.php and fileed.php. The new position looks fine in both.

A comparsion (top is old, bottom is changed):
6022_compare_oldnew
The increased margins of `searchBar` has the desired effect of separating the bar from the table.
The top/bottom margins in `searchInput` moves the actual input field inside the container, causing the line seen in the bottom example of the image above, which is probably not intended (and does not look very nice)

**Comment by a17pongo** [comment]
@a17amama 
Please make the requested changes to searchbar.

**Comment by a17amama** [comment]
The lines inside the searchbar has been removed, which i believe was already an issue on its own, but it is resolved now anyway and is ready for testing.

**Comment by a17pongo** [comment]
@a17amama if an issue for this already exist could you make a reference to it here?

**Comment by a17amama** [comment]
The issue that was supposed to handle this is issue #5956, which will be closed now.

**Pull request merged**
