### PR TITLE
No more sun grade in dugga #11081

### PR DESCRIPTION
**Pull request by a13zanal**
Removed The sun grade from the dugga header in file dugga.js.

### CODE REVIEW

**Comment by a19rebsa** [comment]
To make it clearer, this is the sun grade before:
före

Now it looks like this:
efter

**Comment by a19simma** [comment]
Can confirm the 'sun' is not present 🌞 

image

**Review by a19simma — APPROVED** [review]
Nice job

**Review by a19arvka — APPROVED** [review]
Stoplight is gone.
Högerregeln som gäller

**Pull request merged**
