### PR TITLE
g1 2023 v6 #13906

### PR DESCRIPTION
**Pull request by b21matfi**
changed what placing type it is and the issue is fixed you can now place sequence life

### CODE REVIEW

**Comment by b21eriho** [comment]
There are other buttons that do not work, these are also a part of this issue. That is why they wrote "such as", please ensure that all buttons do what they should, the exception to this is the button for the button that is the furthest down with the icon for option loop or alternative which is not yet implemented.

**Comment by b21eriho** [comment]
From what I can tell selecting sequence activation will mark the sequence object button but still create a sequence activation object on click, I believe

**Comment by b21matfi** [comment]
Alright i will take a look at it

**Comment by b21matfi** [comment]
The issue is fixed, the bug came because we reuse alot of the code but we don't change the ID, same thing is that some of the button that dont have functionality place the attribute element because we reuse the code without removing or changing the code to apply for the element.

**Comment by b21eriho** [comment]
I see

Den ons 10 maj 2023 14:23b21matfi ***@***.***> skrev:

**Review by a21aldsa — APPROVED** [review]
All menu buttons work except sequence object and option loop. This is how it should be, good job.

**Pull request merged**
