### PR TITLE
edit course with Github link

### PR DESCRIPTION
**Pull request by b21sebgr**
Added a inputfield to add a github link for already created courses

### CODE REVIEW

**Comment by b21leowa** [comment]
Have you pushed the latest version of your branch to https://cms.webug.se/root/G3/students/b21sebgr/LenaSYS/?

I cannot see any Github link for already created courses as seen below:

image

**Comment by b21leowa** [comment]
I pulled from the branch g3-2023-v1-issue#13055 to my own machine and the branch works.

As seen below.

image

**Review by b21leowa — APPROVED** [review]
👍

**Comment by b21sebgr** [comment]
@b21leowa when approved you should merge the pull request with the stable branch and delete the branch

**Pull request merged**
