### PR TITLE
G1 2021 #10312

### PR DESCRIPTION
**Pull request by a17alfja**

### CODE REVIEW

**Comment by a17alfja** [comment]
The user that initially creates the dugga does not count as an active user in this solution, only using the hash to login and view the dugga will (unsure if students or teacher will create dugga).

**Comment by a17alfja** [comment]
also you will need to run the create table for groupdugga in init_db.sql for it to work

**Comment by a17alfja** [comment]
you can now use the file createTables.sql to create groupdugga table

**Review by a16erilj — COMMENTED** [review]
Didn't find anything that broke during testing. So I'll give my approval that regard. However i would like some comments about the idea behind some of functions behind the code.

**Pull request merged**
