### PR TITLE
g2-2024-v2 #14419

### PR DESCRIPTION
**Pull request by a22eddpe**

### CODE REVIEW

**Comment by a22marca** [comment]
I'm having issues finding where to integrate this microservice, it with the rest of the system. @a22eddpe Do you know where this can be added in the javascript-part of the system, so that the microservice is called instead of sectionedservice.php?

**Comment by a22eddpe** [comment]
@a22marca no but i can look for it

**Comment by a22marca** [comment]
I was able to find where to integrate the microservice. I had to modify the current code a bit for this to work.
@a22eddpe 
The code at line 1093 in `Shared/dugga.js` has been modified to the one below to test this:
```
	}else if(kind=="SECTION"){		
		if(opt=="REORDER"){
			$.ajax({
				url: "../DuggaSys/microservices/sectionedService/reorderListentries_ms.php",
				type: "POST",
				data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para+"&hash="+hash,
				dataType: "json",
				success: returnedSection
			});
		}else{
			$.ajax({
			url: "sectionedservice.php",
			type: "POST",
			data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para+"&hash="+hash,
			dataType: "json",
			success: returnedSection
			});
		}
```

I don't think we should modify the code in the codebase yet though, since the microservice is not supposed to be integrated at this point, but it works for testing purposes.

**Comment by a22marca** [comment]
One issues with the code in the previous comment is that you now have to reload the page to get the "new" ordering.

**Comment by a22eddpe** [comment]
Yeah me neither. But nice work.

**Review by a22marca — CHANGES_REQUESTED** [review]
The opt is not retrieved in the microservices, but it is used in the if-statement.
This should be added like this:
```
$opt = getOP('opt');
```

The integration seems a bit tricky, and I managed to integrate it to be able to test the microservices. And it seems that is able to reorder the list when adding the opt as well.
The integration is probably it's own issue, so i don't believe we need to fix it in this issue.

Add the opt, and we are good to go!

**Comment by a22eddpe** [comment]
i added the parameter now

**Pull request merged**
