### PR TITLE
Shortcut to resetToOrigin issue #7220

### PR DESCRIPTION
**Pull request by a16tobfr**
Issue #7220 fixed. The shortcut for resetting the view to the origin. The shortcut is now shift + o

### CODE REVIEW

**Comment by a17jacsv** [comment]
> Issue #6297 handles all the shortcut for all the menu options, and also pull-request #7271 is already merged and done so this pull request is kind of useless. We created a new issue #7311 that fixes the label issue that happened after it got merged into the group branch and are working on it right now. @a14oscna

Pair-review-comment...

**Comment by a16tobfr** [comment]
> 
so this pull request is kind of useless.
> 
This pull request adds the functionality for the hot-key which did not exist before. Therefore, it's not useless.

**Comment by a16jenja** [comment]
> `so this pull request is kind of useless.`
> 
> This pull request adds the functionality for the hot-key which did not exist before. Therefore, it's not useless.

image
This is from the group branch right now, reset view to origin is bound to Shift + 0 in this case since another option got Shift + O. And it works as it should, the functionality is implemented correctly and everything. So not sure what you mean. And as I said previously the issue #7311 is handling the placement of the label right now, since it got misplaced after the merge.

**Comment by a14oscna** [comment]
I deem this solution relevant because of the code structure which has been proven useful. I will create a big write-up with more detail and i am sorry if it will cause a lot of confusion, but I should not have merged PR #7271 without further requirements, as there has been a lot of conflicts in interest after the merge. Since #7311 is similar to this, but adds the "alt modifier" which we do not really need, I have decided to close that PR#7316.

**Pull request closed without merging**
