### PR TITLE
Pull request for #10721

### LINKED ISSUE #10721: Find the cause for split is undefined and fix it
Some programmers get the error split is undefined. Find the cause for it and fix it.

### PR DESCRIPTION
**Pull request by a19simma**
image
check that there's no error referring to trying to split on undefined.

fixes #10721

### CODE REVIEW

**Comment by a19simma** [comment]
can't do anything with feedback if it's undefined

**Review by a19kevkh — APPROVED** [review]
Works for me. Tested in chrome, chrome incognito and brave. 

Although the picture isnt displayed, but thats probably unrelated to this issue...

**Review by a19frebo — COMMENTED** [review]
I still get the error message on google chrome. 
However when i use incognito mode on google chrome i dont get the error message, neither when i use microsoft edge.
image

**Comment by a19simma** [comment]
> 
> 
> I still get the error message on google chrome.
> However when i use incognito mode on google chrome i dont get the error message, neither when i use microsoft edge.
> image

It's your local storage @a19frebo try clearing it.

**Review by a19frebo — APPROVED** [review]
I did clear my local storage yesterday when i tested it, but i tried it again today and now it seems to work for me.

**Pull request merged**
