### PR TITLE
Issue #3745

### PR DESCRIPTION
**Pull request by a15chrau**
Implements top, right, bottom and left align, as well as vertical and horizontal align.

These options are added to an additional drop down menu, titled "Align". This is possibly a temporary solution.

Does not work for figures.

### CODE REVIEW

**Comment by a15chrau** [comment]
I forgot to mention that this also puts the global appearance button within the drop down menu labeled "Edit".

**Comment by a15ponja** [comment]
Closed due to unfinished before merge.

**Comment by a15chrau** [comment]
Re-opened per instruction

**Comment by b15matvi** [comment]
Tested it out, appears to be working.

**Pull request merged**
