### PR TITLE
Score in localstorage - #10435

### PR DESCRIPTION
**Pull request by a13zanal**
Saves score variable for each dugga in an array in localstorage

### CODE REVIEW

**Comment by a19rebsa** [comment]
To test this pull request you open the inspector in the browser, go to application and check your local storage. To each dugga you should see that the score is stored in an array.

**Review by e15marol — COMMENTED** [review]
It works, however score seems arbitrary and we can't quite figure out what the score represents. Also there are some duggas that don't generate any scores, for instance 3D dugga in the demo-course. If you constantly save a dugga over and over, it generates a new highscore (different value from the previous highscore) and adds it to the array, is this intentional?

**Review by b18jacha — APPROVED** [review]
**It works.** 

_Would be cool to have the date saved with every highscore aswell!_

**Review by e15marol — APPROVED** [review]
So the highscore goes either by counting clicks or time taken and records it as a highscore value, which is what the numbers represent. The solution works, although for the future, the highscore might need a change as it doesn't serve a purpose that we can see currently. Good job!

**Pull request merged**
