### PR TITLE
 changed so variables in constructElementType in diagram.js use the l…

### LINKED ISSUE #14161: Refactor function
## Description / Job
The function ``constructElementOfType`` inside ``diagram.js`` uses ``var`` declarations and either return ``undefined`` or an element (two different places). Try to refactor this function, and make it return in one place rather than two. The return types should be the same, ``undefined`` or element.

```
function constructElementOfType(type)
{
    var typeName = undefined;
    for (const name in elementTypes) {
        if (elementTypes[name] == type) {
            typeName = name;
            break;
        }
    }
    if (typeName) {
        var defaultElement = defaults[typeName];
        var newElement = {};
        for (const property in defaultElement) {
            newElement[property] = defaultElement[property];
        }
        return newElement;
    }

    return undefined;
}
```

### PR DESCRIPTION
**Pull request by a21nibah**
fixes #14161

### CODE REVIEW

**Review by c21adano — CHANGES_REQUESTED** [review]
java script usually throws an error if you try to return only in an if statement. Besides. it makes more sensce to return undefined if it can not get an object. 
"Try to refactor this function, and make it return in one place rather than two." This seems to be missing from the pull request

**Comment by a21nibah** [comment]
> "Try to refactor this function, and make it return in one place rather than two." This seems to be missing from the pull request

java script usually throws an error if you try to return only in an if statement. Besides. it makes more sensce to return undefined if it can not get an object.

**Comment by b21phiro** [comment]
> > "Try to refactor this function, and make it return in one place rather than two." This seems to be missing from the pull request
> 
> java script usually throws an error if you try to return only in an if statement. Besides. it makes more sensce to return undefined if it can not get an object.

True! A suggestion I have for a potential solution here, is to assign a dynamic variable that will be returned no matter what. Ex (unrelated code but for an idea)

```
function returnSomething() {
   let result = {};

  if (bla bla bla) {
      result = this
}
else {
   result = that
}

return result
}
```

**Comment by b21phiro** [comment]
Other words don't return in the logical operations but rather as a result.

**Review by c21adano — APPROVED** [review]
calling the function returns undefined or a given element type.

**Pull request merged**
