### PR TITLE
G3 2024 v7 #15633

### PR DESCRIPTION
**Pull request by a22samka**
Changed all tables in loginbox to a div structure instead

### CODE REVIEW

**Review by d22isaka — COMMENTED** [review]
With the new loginbox there appears to be a new ''Sign in'' text above the username-field.
Not sure if intended as the issue states to only change tables to divs. Only 3 lines of code needs to be deleted if that's not the case.

Other than that, looks good and it works fine =)
Skärmbild 2024-05-16 094407

**Review by a22moamy — CHANGES_REQUESTED** [review]
Fix the comment left by @d22isaka

**Review by d22isaka — APPROVED** [review]
Looks good to me! =)

**Review by a22moamy — APPROVED** [review]
looks good now

**Pull request merged**
