### PR TITLE
Added radios for sorting in fileed

### PR DESCRIPTION
**Pull request by a15wilhe**
Added input element with type radios for sorting with pairing labels. Lots of props. And also a onclick function that has not been submitted yet. You can check out the result at my folder at the testsite in fileed. 
Partfix for #3277

### CODE REVIEW

**Comment by a15matab** [comment]
I get errors when pressing the radiobuttons when testing it. Doesn't seem to find the "sorttype" function?

screenshot from 2017-04-25 11-36-05

**Comment by a15matab** [comment]
I can't unselect any radiobutton after selecting it. Is this just because the "sorttype" function isn't present yet?

**Comment by a15wilhe** [comment]
when one radio button is selected it cannot be unselected. It's a core function of the radio button.

**Comment by a15matab** [comment]
Sorry I meant them being deselected after another button is selected. At the moment it seems all the buttons can be selected at once. Is this intended?

bug11

**Comment by a15wilhe** [comment]
no that's wrong, I will fix it

**Comment by a15wilhe** [comment]
I have now changed the name on all radios to the same. check it out in my testfolder. Good testing!

**Pull request merged**
