### PR TITLE
Refactor checkElementError() #13151

### PR DESCRIPTION
**Pull request by a21oligu**
Refactored the function _checkElementError()_ by dividing it further into more maintainable, traceable functions: _checkEREntityErrors()_, _checkERRealtionErrors()_, _checkERAttributeErrors()_ and _checkLineErrors()_.

### CODE REVIEW

**Comment by b21eriho** [comment]
What do you mean Adam, that you have decided against these changes or are you telling me to go through it before saying that it has passed testing (which is obvious)

**Comment by c21adano** [comment]
there are over 1400 changed lines in this pull request

**Comment by c21adano** [comment]
just want to understand why that is before a merge is done

**Comment by b21eriho** [comment]
Yes of course... I do not understand your point, of course I would not simply say to merge it without understanding the changes... Are you saying you are also reviewing it?

**Comment by a21oligu** [comment]
I divided the function checkElementError() into smaller functions. The checkElementError consisted of all the logic for the different types of tests, although only one was used at a time. I divided these sections into separate functions by moving the sections to individual functions containing the code only for the test that is to be run.

**Comment by b21eriho** [comment]
Thank you, that is very helpful

**Comment by c21adano** [comment]
no just panicked a little, large changes like this one which changes 1400 lines need to be investigated as to way so many changes happend. 

It seems like part of the code has been auto indented:
autodent

This is the cause of my concern, we are not allowed to merge things that auto indent large parts of the kode.

**Comment by b21eriho** [comment]
Rather, it seems since a large function was split into multiples the indentation had to be changed since the code is no longer inside an if-statement

**Comment by a21oligu** [comment]
> Rather, it seems since a large function was split into multiples the indentation had to be changed since the code is no longer inside an if-statement

@b21eriho is right, splitting the function meant that the if-statements was removed, thus the indentation was changed.

**Comment by c21adano** [comment]
ok, but wait with the merge for now. local storage seems broken and we dont wanna merge until we find why.

**Comment by b21eriho** [comment]
I am still in the middle of the code-review and naturally only leader and issue-responsible may merge so this will not be merged without your approval

**Comment by b21eriho** [comment]
I have looked through through the code as an overview and the indentation and comments seem to work correctly. However this branch has a strange bug compared to the group's current stable branch, when selecting the tool to create an entity and then trying to switch back to the selection tool to pan around the system breaks and no tool can be selected nor used

**Comment by c21adano** [comment]
Dose the site look like this? There has been some problems with the local storage, where the site breaks if no local storage is currently saved.
eretst


Otherwise its sounds good. Oscard will merge later.

**Comment by b21eriho** [comment]
image
It looks like this, in my case I added a few entities and then swapped back to another tool, and now the system is unresponsive.

**Review by b21eriho — APPROVED** [review]

**Pull request merged**
