### PR TITLE
CodeViewer: Hides Copy button when there isnt room for it

### PR DESCRIPTION
**Pull request by a17fellu**
The copy button will get hidden when the box reaches a certain width threshold. Also removed the old functionality added in this PR: #7416 as it is now obsolete with this pull request

Fixing issue: #7434

### CODE REVIEW

**Comment by a17fellu** [comment]
> https://imgur.com/a/ygVTFpy
> The functionality for the actual copy-button works but with some unwanted side effects.

Will look into it

**Comment by a17fellu** [comment]
@a17robda i cannot reproduce this bug. Can you give some steps so i can try to reproduce this?

**Comment by a17robda** [comment]
Strange, I am getting this bug in both Firefox and Chrome, Tried restarting the server and updating branches but still the same bug for me.

**Comment by a17fellu** [comment]
I have tried multiple browsers but cannot reproduce this. Maybe we should let someone else look at it as well?

**Comment by a17robda** [comment]
That would be nice I guess. Maybe there is something wrong on my side.

**Comment by b16johso** [comment]
I am getting the same bug as @a17robda.

**Comment by a17fellu** [comment]
I also managed to reproduce this bug on an old installation. The bug dissipated after i cleaned the cache and cookies. If that didn't help i also created a new code element on the course page. But before trying that just clean the cache to see if it 100% is a cache issue.

**Comment by a17fellu** [comment]
After some testing i can conclude that it is not a cache issue. The bug appears when opening a code page that was there before this branch was installed. This is a super weird bug and i am not too sure of how to fix this

**Comment by a17poner** [comment]
Any more luck replicating the issue and solving it? Would be nice if you could get the solution to run consistently for everyone so we can merge it in before wednesday :)

**Comment by a17poner** [comment]
This didn't make it in time for the last merge, closing

**Pull request closed without merging**
