### PR TITLE
Cv#1180

### PR DESCRIPTION
**Pull request by a12jiyba**
Changed font-family to "Andale Mono",AndaleMono,monospace

### CODE REVIEW

**Comment by f12danjo** [comment]
Doesn't change the font on all the text in the code box.

**Comment by a12jiyba** [comment]
It should work now!

**Comment by a12jiyba** [comment]
wait do not merge

**Comment by a12jiyba** [comment]
#1180

**Comment by f12danjo** [comment]
Nice, now all the text gets the new font. However: Some text gets white background color, so we get white blocks around some text. Could we fix this somehow?

**Comment by a13jansa** [comment]
This change should be right now. issue nr #1180

**Pull request closed without merging**
