### PR TITLE
ds16 #845

### PR DESCRIPTION
**Pull request by a13chrju**
method fix.

### CODE REVIEW

**Comment by a13oscwe** [comment]
Looks fine, should the actual password recovery be implemented? If so which group takes on that responsibility? Anyhow that would be a different issue i guess.

**Comment by c13chrjo** [comment]
It should not be functional since we don't have a mailserver available

**Comment by a13chrju** [comment]
yeah, it's only the visuals

**Comment by a13denli** [comment]
Good!

**Pull request merged**
