### PR TITLE
Some "Reset pw" buttons are not purple anymore 

### PR DESCRIPTION
**Pull request by a16lisri**
Fix for: https://github.com/HGustavs/LenaSYS/issues/7569

### CODE REVIEW

**Comment by a17joaap** [comment]
Isn't that a feature of access? If the user was added less than 24 hours ago, they have a purple button. Not sure what for though.

**Comment by a17fellu** [comment]
Yeah looks like that is the case. But what would be the reason for that feature?

**Comment by a16lisri** [comment]
> Isn't that a feature of access? If the user was added less than 24 hours ago, they have a purple button. Not sure what for though.

Yeah that makes sense, as I couldn't test it locally (where no new users had been added). Doesn't make sense for the button to be purple though.

**Comment by a17fellu** [comment]
Maybe wait with merging this so we maybe can get some answers

**Comment by a17poner** [comment]
yeah I will wait with merging this then

**Pull request closed without merging**
