### PR TITLE
G1 2021 w19 #10720

### PR DESCRIPTION
**Pull request by e15marol**
Since assignments are only going to be accessed through canvas in the future and not through direct urls, there should be no issues for the fix we did, in that it stores the url in local storage when you open the assignment and redirects to it if you cannot enter the correct hash or wish not to (e.g. closing the popup window).

To test this, either access a dugga through your local installation of lenasys or through the following link: http://canvas.webug.his.se/courses/1/assignments/5 and use the admin account.

If you're having issues loading the iframes, simply open up the HTML editor inside canvas and change the address to where you have your lenasys installation folder.

Co-Authored-By: b18jacha 62884577+b18jacha@users.noreply.github.com

### CODE REVIEW

**Review by a19kevkh — APPROVED** [review]
Excellent.

**Review by a19frebo — APPROVED** [review]
Nice solution! 👍 🚀

**Comment by b18jacha** [comment]
@b19ponka @a16erilj  We just discovered a new issue with this.
- When trying to load a new hash it will always try to redirect us to previous visited dugga, no matter if we enter correct password or pressing the X button to close the popup. We need a new issue for this.

**Comment by b18jacha** [comment]
> @b19ponka @a16erilj We just discovered a new issue with this.
> 
> * When trying to load a new hash it will always try to redirect us to previous visited dugga, no matter if we enter correct password or pressing the X button to close the popup. We need a new issue for this.

Created a new issue https://github.com/HGustavs/LenaSYS/issues/10788

**Pull request merged**
