### PR TITLE
Suggestion for github contribution appearance

### PR DESCRIPTION
**Pull request by a16joare**
This is a new suggestion for issue discussed in #6839. 

This soultion has scrapped the icons and continued with the more text based approach. 
From start when the page is first loaded it checks if a key in localstorage exists and either load a defualt value which will keep every contribution tab open or load from the already existing values from localstorage. This will provide the possibility to choose if you want to see all the content or hide some of them. 

Here is a image when you first load the page (with no existing localstorage key):
image

Closed some of the tabs by clicking on the text "Made 3 commit(s)" etc.. :
image

The solution supports the possibility to choose which div/label to keep open. This gives the opportunity to hide everything, keep some tabs for a specific week oppend or keep all tabs of a specific kind open.
image

Here is only the issues tab shown:
image

Everything closed: 
image

Any thoughts on this @HGustavs ?

### CODE REVIEW

**Comment by a17maxsj** [comment]
I like the concept a lot. Using local storage is a great idea! The only issue i have right now is that all the links are broken. I think they are trying to be loaded within the frame. Making the link open a new tab should fix this.  target="_blank"

https://gyazo.com/35882c1cc6fbc629228057c5ae69ba9b

**Comment by HGustavs** [comment]
AFAIK this seems very close to what we want.

Very useful for teachers, but students that want to hide some of their activities, can do so.

**Comment by a16joare** [comment]
Fixed the linking problem that @a17maxsj pointed out.. Also fixed the problem that made the tabs close when the links were clicked..

**Comment by a17maxsj** [comment]
Works great now!

**Comment by a17maxsj** [comment]
Also change the color scheme to something like this? i think it looks a lot nicer!
image

**Comment by a17poner** [comment]
Yeah agree, some extra buttons and functionality for this can make some new seperate issues :)

**Pull request merged**
