### PR TITLE
Strange behaviour when both template and example diagrams are toggled on #14233

### PR DESCRIPTION
**Pull request by a19clasv**
Placed Vertical and Horizontal buttons under A4 template.
So it looks like this:
image
Instead of this:
image

### CODE REVIEW

**Review by a21aldsa — APPROVED** [review]
Looks good

**Comment by b21eriho** [comment]
@a19clasv I messed up slightly in solving the merge-conflict. If you check in the changed files you can see that in the stable branch the buttons you moved have had their styling removed, please remove the styling in the same way on your branch

**Comment by a19clasv** [comment]
Looks like this now:
image

**Review by a21aldsa — APPROVED** [review]
Looks fine, things still seem to work after the conflict fix

**Pull request merged**
