### PR TITLE
added a button for sequance option loop

### PR DESCRIPTION
**Pull request by c21adano**
added a button for sequance option loop

### CODE REVIEW

**Review by b21oscpe — CHANGES_REQUESTED** [review]
Button is not highligthed when selected. I suggest adding something along the lines with "active" along with its other class-attributes
06decddc1f84405c116ebda35c439a8a

**Comment by b21oscpe** [comment]
I believe it is done with "holdplacementbuttonup()" if im not mistaken

**Comment by c21adano** [comment]
> Button is not highligthed when selected. I suggest adding something along the lines with "active" along with its other class-attributes 06decddc1f84405c116ebda35c439a8a

Its not highligthed when selected due to currently being linked with er attribute like how the other sequance elements are linked to super state.

**Review by b21oscpe — APPROVED** [review]
I took a look and it seems like you're right, looks good

**Pull request merged**
