### PR TITLE
Hamburger menu in analytics navbar | Fix for issue #9488

### PR DESCRIPTION
**Pull request by a17towan**
There is now a hamburger menu that appears when the screen reaches a certain screen width in the navbar in analytics.php. Instead of cramming all the small icons together, the icons are moved to the hamburger menu as a list item depending on how small the screen width is.

<a href="https://gyazo.com/107f463e79c88c36f14f9313bb935ca6">Image from Gyazo</a>

### CODE REVIEW

**Comment by a18jenro** [comment]
Also, if you spam the hamburger menu icon you will queue a very long animation of opening and closing it.

**Comment by a17towan** [comment]
Don't spam it then <3

**Comment by a18jenro** [comment]
Maybe I got twitchy-fingers-disease?

**Comment by a17towan** [comment]
I fixed the things now so your twitchy-fingers disease should no longer negatively influence your ability to press the hamburger-button in the intended way.

<a href="https://gyazo.com/4a9fbd3e785d751afb242dec8a4f91c5">Image from Gyazo</a>

Also the icons are centered.

**Pull request merged**
