### PR TITLE
AccessED: Fixed bug where old version icon didn't show.

### PR DESCRIPTION
**Pull request by a17robda**
Fix for #6670 Someone had replaced the img ID with the class attribute.

### CODE REVIEW

**Comment by a17joaap** [comment]
The issue was a little more complicated I'm afraid.

**Comment by a17robda** [comment]
It goes back to the older version of the course if there is one.

**Comment by a17robda** [comment]
I will take a closer look.

**Comment by a17joaap** [comment]
And it's supposed to be 'class' not 'id' because of CSS:
```
.oldSubmissionIcon {
  height: 20px;
  margin-left: 10px;
  cursor:pointer;
  vertical-align: middle;
}
```

**Pull request merged**
