### PR TITLE
Time sheet: Changed day from DATETIME to DATE

### PR DESCRIPTION
**Pull request by a17joaap**
Gets rid of the trailing 0's in the submission view

### CODE REVIEW

**Comment by a17joaap** [comment]
It should work now

**Comment by a17maxsj** [comment]
All old entries shows UNK! what could be the cause of this?

image

**Comment by a17joaap** [comment]
Your entries are being saved in the database:
dbtest

The problem seems to be with the submissions folder

**Comment by a17joaap** [comment]
@a17maxsj this is because of different branches using the same database 'Databas2019'.

If I upload a submission on branch A, it will save it to the correct folder with the name timesheet1.txt.
If I then switch branch to B, and upload a new submission, it will have the name timesheet2.txt.

Both of those submissions are saved in the submission database table, which is why they show up in the tab. But timesheet1.txt only exists on branch A and can not be viewed when on branch B.

**Pull request merged**
