### PR TITLE
Accessed: Fixed weird clipping on hover-dropdown on "Double-arrows icon"

### PR DESCRIPTION
**Pull request by a17robda**
Fix for issue #6858

### CODE REVIEW

**Comment by a17robda** [comment]
I am aware of the issue with getting into the actual "menubox" as it was a bug that was present before the fix. However, the fix is only for the issue which is the weird clipping of the menu compared to hovering over the other icons (Which also have the same issue at the moment in this weeks branch. See issue #6920 for the same bug.).

**Comment by a17poner** [comment]
There is a big change to this being done by groupB, I won't merge this until possibly after wednesday. Hopefully their fix will solve this for all of us and this wouldn't be needed then.

**Comment by a17robda** [comment]
This still seems to be an issue with the weird clipping after merge.

**Comment by a17poner** [comment]
I don't have it after hard refreshing with gruppC2019W21 and it seems to work as intended now.

**Comment by a17poner** [comment]
Seems to be fixed now already for all that tested it on location here, closing this.

**Pull request closed without merging**
