### PR TITLE
Issue#12995

### PR DESCRIPTION
**Pull request by a21nibah**
just a clerification. I saw that i wrote that this issue will cause errors. it's not that it will cause errors but more like that it could cause errors. so i have fixed so pdo connect  and the diagram files now handle a fialed connection more gracefully.

### CODE REVIEW

**Comment by a21nibah** [comment]
no it is fine. it is just i had to change the rights to read and write so i could work via ssh on the server. i can provide a list of files that were changed if needed

**Comment by b21oscpe** [comment]
"ah yes. det där var bara för att jag behövde ändra rättigheter på allt till execute så jag kunnde jobba mot servernn. de filer som ändrats finns i commit" - @a21nibah

**Comment by b21oscpe** [comment]
The discussion about the "745 files" can be ignored in testing, the problem is resolved

**Comment by c21adano** [comment]
Related: #13032 
I think its best to temporarily close this pull request, due to issue#13032 which is about moving the database code out of diagram.php and the numerous file changes done. The file changes themself are not harmful but may "overwrite" someone else work.
This issue(#12995) will be reviseted at a later date and its branch will be keeped for that reason.

**Pull request closed without merging**
