### PR TITLE
G2 2023 v5 issue#13789 - Change duggaedservice-tests.txt to MD and add expected output

### LINKED ISSUE #13789: Change duggaedservice-tests.txt to MD and add expected output
Related to: #13788

[backend-models/service-tests/duggaedservice-tests.txt](https://github.com/HGustavs/LenaSYS/blob/44f973e4d27a94e1a23932e941dd1501dc3868ce/backend-models/service-tests/duggaedservice-tests.txt)

### PR DESCRIPTION
**Pull request by a21jeaha**
I have finished converting the test document.
The login values and expected/relevant output has been added as well. 

close #13789

### CODE REVIEW

**Comment by a20fanma** [comment]
Do not forget to link the issue next time.

**Review by a20fanma — APPROVED** [review]
It looks good

**Comment by c21alest** [comment]
MD looks a bit weird:
Skarmavbild_2023-05-05_kl _15 55 38
@a21jeaha can you confirm that this is correct?

**Comment by a21jeaha** [comment]
> MD looks a bit weird: Skarmavbild_2023-05-05_kl _15 55 38 @a21jeaha can you confirm that this is correct?

thats odd.. i have checked the output both in visual studio and here in github. i have not experienced that problem at all.

are you sure your accessing the last version?

**Comment by c21alest** [comment]
It must have been some problem with the review preview, not it looks great! Good job!

**Pull request merged**
