### PR TITLE
Update testdata.sql

### PR DESCRIPTION
**Pull request by a17alfja**
Removed duplicate insert

### CODE REVIEW

**Comment by e15marol** [comment]
Looks good, there are no duplicate inserts that we could find.

**Comment by b18jacha** [comment]
And we also tried a fresh install with zero errors.

**Review by e15marol — APPROVED** [review]
Looks good, there are no duplicate inserts that we could find.

**Review by b18jacha — APPROVED** [review]
Tried a fresh install with zero errors.

**Pull request merged**
