### PR TITLE
Fix section problems

### PR DESCRIPTION
**Pull request by a18danli**

### CODE REVIEW

**Comment by a19isada** [comment]
Make sure that all the functionallity still works as it should when testing.

**Comment by b18phika** [comment]
It's with great sadness that I have to deliver the news that I do in fact not own a mac, and therefore cannot test this pull request.

**Review by a18willi — APPROVED** [review]
Nothing seems to be broken

**Review by b18phika — APPROVED** [review]

**Comment by a19isada** [comment]
After testing on a mac, you can visit a course page and nothing seems to be broken.

**Pull request merged**
