### PR TITLE
Codeviewer: Fix on reset button after maximize

### PR DESCRIPTION
**Pull request by a17robda**
Revisited #7274 fix for #7198 on new branch.

### CODE REVIEW

**Comment by a17robda** [comment]
Unfortunately, this still seems broken after some additional testing. Closing PR for now.

**Comment by a17robda** [comment]
Still doesn't work.

**Comment by a17robda** [comment]
This should finally work now.

**Comment by a17robda** [comment]
Closing temporarily since i need to fix a conflict first, will reopen afterwards.

**Comment by a17poner** [comment]
Are the errors present caused by this and can they be fixed before we merge it or do we blame someone else for them? :D

**Comment by a16lisri** [comment]
I show it in a gif here: https://gyazo.com/aa73b6c88ae56bcbb99c65def521603b

**Comment by a17poner** [comment]
aa okey, I think that got fixed and one point and maybe came back in the merge, @a17robda do you think this is something that is easily solvable and want to piggyback it onto here or should we make a new issue for it and solve it again`?

**Comment by a17robda** [comment]
You could probably make a new issue for it since I have never gotten that specific error when I tested the fix for this issue. I did however get some errors with the hiding of copy buttons, but those are probably fixed now.

**Comment by a17poner** [comment]
aight, i'll check if its a problem on my machine after merging it and will make an issue if I see it!

**Pull request merged**
