### PR TITLE
Positioning of A4 holes #6414

### PR DESCRIPTION
**Pull request by a17jacsv**
By clicking "Toggle A4-Holes" you change the position of the holes of the A4 from left-right & upper-bottom (Horizontal and vertical). At the moment you click the menu item to shift sides. A future issue would be instead of a checkmark put an icon who describe which side the holes are at. I will write that issue when it's approved and merged.

#6414

### CODE REVIEW

**Comment by a17jacsv** [comment]
> The actual function seems to be working well, the holes goes to the other side of the paper in both vertical and horizontal.
> 
> One issue I found though is that when this option is toggled on, when you press spacebar, leftclick anywhere on the screen and zooming in and a bunch of other stuff. It will keep switching, which seems weird.
> 
> Also don't forget to reference the issue in the description of the pull request like this #6414

Okay, that's weird. I will look into it.

**Comment by a17jacsv** [comment]
Fixed the problem by making a new menu item to swift the holes from left to right. The problem was that the canvas is being redrawn every time you move the canvas and therefore the holes kept shifting... Now it should work as expected! 👍

**Comment by a17jacsv** [comment]
The problem with enabling disabled items was before this issue and will be solved in another issue. The other problems will be solved now. Please test it again.

**Comment by a16jenja** [comment]
Oh I missed the other comment, my bad, then it works good!

**Pull request merged**
