### PR TITLE
G1 2023 v7 #14042

### PR DESCRIPTION
**Pull request by a21nibah**
solves issue #14042 I have added a parameter to allow for other keys. it does not make sence to really make it so you can send in an array since you most likely will only be saving a diagram at once. I have asked in the issue if we should have key generation be automatic so that we generate a key according to timestamp but got no reply so that can be a separate issue if we want to have automatic key generation.
i have also fixed so that the function calls use the "CurrentlyActiveDiagram" key

### CODE REVIEW

**Review by d21matbo — CHANGES_REQUESTED** [review]
The changes does not work for the "save current diagram"-button in the toolbar.

I believe that this error occurs due to the button not using any argument in its function call.

**Review by d21matbo — CHANGES_REQUESTED** [review]
Think something went wrong with the quotation marks, as it now throws the error:

Uncaught SyntaxError: Unexpected end of input (at diagram.php:844:144)

**Comment by a21nibah** [comment]
ok see if that works. works fine here.

**Review by d21matbo — APPROVED** [review]
The changes made have fixed the issue, looks good!

**Pull request merged**
