### PR TITLE
Update resulted.js

### PR DESCRIPTION
**Pull request by a17amama**
Commented out setTeacher value, cause the value only held NULL and was taking up unnecessary space

### CODE REVIEW

**Comment by c17johha** [comment]
#5661

**Comment by a17pongo** [comment]
https://issue_5661.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97731

**Comment by a17ludca** [comment]
Works on the standard port 20001 but not on 20002, I don't know if this is an issue we have to fix or not. The code provided works.

**Comment by a17pongo** [comment]
I think this is an error in server configuration, workflow and folder structure on the web server will be refined to prevent this.

**Pull request merged**
