### PR TITLE
Umv18#1061

### PR DESCRIPTION
**Pull request by a13erilj**
Fixed issue: #1061 
* Added php code to retrieve course results for each student of the course
* Added js code to parse the course results to the right divs
* Removed unused div in teacherView.php
* 'studentinfo' now holds both course data and student data
View changes: http://webblabb.iki.his.se:8080/umv/a13erilj/week-18/UserManagementView/teacherView.php

### CODE REVIEW

**Comment by c13marme** [comment]
Removed a function from teachermanagementview.js that didn't work

**Comment by a13erilj** [comment]
Good, I forgot it was still there.

**Comment by c13marme** [comment]
$studentinformation query in usermanagementservice.php doesn't order by lastname right now, will create a separate issue for that.

**Comment by c13emmjo** [comment]
some comments would be nice

**Pull request merged**
