### PR TITLE
Error checking for ER diagrams

### PR DESCRIPTION
**Pull request by a20edwth**
Error checking for ER diagrams, errors will be outlined in red. #11600

Instructions for testing:
Note: testing requires knowledge in ER diagrams.

1) Click "Demo-Course"
2) Click "Diagram Dugga"
3) Change the diagram to test all problems listed below:

1. Wrong line type, **correct**:  single line for strong entities and double line for weak entities
2. Wrong key type, **correct**: strong key for stong entities and weak key for weak entities
3. More or less than one key 
4. More or less than 2 lines to entities from a relation
5. Attributes with same name on the same entity
6. No cardinality set (Cardinality is the "N" or "1" situated on a line from an entity to a relation)
7. Wrong relation type, **correct**: weak relation must have a line to a weak entity and strong relation must have lines to two stong entities

### CODE REVIEW

**Comment by c20emili** [comment]
the error detecting system works for the faults mentioned in the first comment but a weak entity are not allowed to have anything but weak relations which is incorrect.
image
and doesn't can't there be a double line on a strong relation to show a forced relation?

**Comment by c20emili** [comment]
This fault are not entirely correct: "1.Wrong line type, correct: single line for strong entities and double line for weak entities"
Strong entitys **can** have double lines to show a forced relation. a weak entity can have different types of relations as long as it has one weak relation to a different entity.

**Comment by a20edwth** [comment]
Added a commit where enities can now have a forced relation and weak entities can have different relations as long as it has one weak relation.

Testing follows the same instructions.

**Comment by c20emili** [comment]
Test failed. a weak entity can be weak to another weak entity which this does not allow (se picture below).
image
and a weak entity needs a weak relation which this does not reflect (se picture below).
image

**Comment by a20edwth** [comment]
The entity gets an error since a weak entity needs a weak key which it does not have, and a weak entity cant have a strong key thus an error for the strong key.

**Comment by a20samul** [comment]
1. Error doesn't disappear if you accidently delete the line and replace it with the same line again.
errordoesntdissappear

2. The weak entity has a weak key but the error does not disappear from employee element.
weakkey

3. It would perhaps be more correct if the line going from employee to the relation was coloured red rather than the diamond.
lineshouldberedinstead

4. The behaviour is not consistent, "EMPLOYEE" doesn't become red whereas "DEPENDANT" does when same error is made.
bdale

The behaviour is not consistent through out the functionality. This issue needs improvement.

Tested on three different laptops.

**Pull request merged**
