### PR TITLE
#5232 DuggaED: Implement further the search functionality

### PR DESCRIPTION
**Pull request by b16karhe**
#5232 Made it possible to search in the variant editor through:

- **_Removed unused functions._**
- **_Fixed the filter function._**
- **_Made the filter reset when the window is closed and a new one is opened._**
- **_Added some comments._**

### CODE REVIEW

**Comment by b16karhe** [comment]
There are some errors when pressing enter but they stem from "sortableTable" and is not something that i have control over.

**Comment by a14isshi** [comment]
It all seem to work as intended and the errors are inside sortabletable. This however does not affect the functionality but should be taken care of. Another false I found is that the search-function is case-sensitive which it probably shouldn't be and therefore this should be fixed before this is merged.

**Comment by a14isshi** [comment]
@b16karhe

**Comment by b16karhe** [comment]
_@a14isshi_ **[DONE]** Transformed all characters to lowercase to stop the matching from being case sensitive.

**Pull request merged**
