### PR TITLE
G3 2024 v2 #14370

### PR DESCRIPTION
**Pull request by d22isaka**
We have added functionality to retreive codeexamples through github.

### CODE REVIEW

**Review by a22natth — APPROVED** [review]
As testing was done on this issue, the requirements had slightly shifted but all parties agreed on that the issue would fetch data correlating to the inserted GitHub repo URL and the file path (on GitHub). More specifically, it was important that it was fetched from the actual GitHub repository and not locally, which the pull request accomplished. When the specified file is fetched, additional files with the same name (regardless of type, .js, .html etc.) are also received. This means that the changed requirements for the issue (can be seen in a comment of issue #14370) regarding fetching multiple files with the same name but different types has been done. An example of the fetched data can be seen below, to which the specified file put into the path is also displayed in the console (which in this case was a HTML file), and proves that the issue has been solved. Furthermore, the data for the files are put into an array which contains additional information of the exact URL which can be used to access the file on GitHub. The testing was also done in light and dark theme to which the functionality worked in both modes. In regards to the readability of the code, the comments give a short but overall description of the methods. Although, a comment on line 3933 in sectioned.js states that the array “codeExampleContents” might be changed into a global variable, but depending on what the following functionalities are, I will leave no change request about this. 

image

**Review by a22willi — CHANGES_REQUESTED** [review]
Looks good in general, but how do you plan to store the files on the server when using ajax? Would it not be simpler to use php for this functionality?

**Comment by d22mikwe** [comment]
> 

This will be adressed in 14525

**Comment by d22mikwe** [comment]
> Looks good in general, but how do you plan to store the files on the server when using ajax? Would it not be simpler to use php for this functionality?

This will be adressed in #14525

**Review by a22willi — APPROVED** [review]
Looks good

**Pull request merged**
