### PR TITLE
[SectionEd] Set Date in Edit Item view style needs fixing #6812

### PR DESCRIPTION
**Pull request by a16hiwah**
fixed by removing unnecessary date input in  sectioned.php. line 232

test link; https://a16hiwah.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732

"before"
57447137-9a1f3080-7256-11e9-9bdc-dc45cc095836
 
"after"
bild

### CODE REVIEW

**Comment by b17nicsv** [comment]
#6812

**Comment by a16hiwah** [comment]
@a17pongo should i take them back and just fix the styling?

**Comment by a17pongo** [comment]
yes

**Comment by a17pongo** [comment]
maybe make them look like they are unified and belong together.
Maybe it would look better if it wasn't two dropdowns or something like that but this is up to our leader to decide.

**Comment by b17nicsv** [comment]
I would like to see them look alike. The date menu looks different from the other menues.

**Comment by a17pongo** [comment]
@b17nicsv do you approve the new changes?

**Comment by b17nicsv** [comment]
Yes, now it looks much better 👍

**Pull request merged**
