### PR TITLE
Maximize function on box 4 now works properly - Template 6

### PR DESCRIPTION
**Pull request by a17chrka**
**Template 6 working as expected:**
<a href="https://gyazo.com/aa5464d8203986b8ccb866055154ca37">Image from Gyazo</a>

**This issue also includes template 7, which as shown below functions properly now as well:**
<a href="https://gyazo.com/e98f2b85384812718af42557ef615236">Image from Gyazo</a>

### CODE REVIEW

**Comment by a18geoge** [comment]
Could not replicate the problems on my local end nor on the testserver while using the G1-2020-W19 branch. The maximize buttons work on template 6 and 7 on all of the boxes.

**Comment by a17chrka** [comment]
Certainly confusing, the pull request does however fix another 
problem with resizing of the boxes which is worth merging to the weekly branch.

**Comment by a17chrka** [comment]
This should be resolved with the latest commit:
<a href="https://gyazo.com/163fda99f710dc0715197dc680f67db6">Image from Gyazo</a>

**Comment by a18geoge** [comment]
Perfect.

**Pull request merged**
