### PR TITLE
G3 2024 v6 #15537

### PR DESCRIPTION
**Pull request by a22karja**
made the pop up on accessed.php search bar to change size depending on what is put into it. No more scroll. Changed the lower corners to be rounded and it now matches the color of the table shown

### CODE REVIEW

**Comment by a22karja** [comment]
and changed the instruction to actually use an example that would work

**Review by a22willi — CHANGES_REQUESTED** [review]
2024-05-1011-03-44-ezgif com-video-to-gif-converter
It still does not work quite right, see the attached gif.

**Review by a22willi — COMMENTED** [review]
Works better now, but the info popup is not aligned properly with the search bar. @a22moamy What do you think?
image

**Comment by a22moamy** [comment]
> Works better now, but the info popup is not aligned properly with the search bar. @a22moamy What do you think? image

Should be fixed.

**Review by a22willi — APPROVED** [review]
Looks good.

**Pull request merged**
