### PR TITLE
Added note element

### PR DESCRIPTION
**Pull request by c21adano**
Added a new element called note, the note exist as its own type of element and can be connected with any other element type. 
lines connected with the note will be dashed, writing more than 4 lines inside the note will make it bigger, changing the colour of the note to black will make the outline white and vice versa. 

Notation for note: #14025

Image of how the note element looks
notefinishedproduckt

The note button is currently under the sequance pop out and is keybinded to "n"

### CODE REVIEW

**Review by b21matfi — CHANGES_REQUESTED** [review]
image
Everything looks fine but when you press save without chaging the type it gives an error

**Comment by c21adano** [comment]
Cant change type from x to x seems to be a problem for all element types and not just note, therefore i would argue that its not part of this issue.

**Comment by b21phiro** [comment]
Indeed, this is an issue that can be reproduced with other elements and should be looked into (if time is on our side).

**Review by b21matfi — APPROVED** [review]
The error message is part of this issue. Everything works well Good job!

**Pull request merged**
