### PR TITLE
#7520 Saved Examinatorfilter to local storage

### PR DESCRIPTION
**Pull request by a18oscte**
In updateTable()
Made a variable to save the dropdown choice. saved it in local storage.
updated forloop on row 585 to select the option matching the saved variable in local storage

Co-Authored-By: @a18matna

### CODE REVIEW

**Comment by a18ismca** [comment]
Unfortunately, ResultEd needs to be fixed up before I can review this pull request and approve it.

**Comment by c14jonfr** [comment]
I am able to see that the store to localStorage works (by manually adding more options to the examinator dropdown) but since the teacher-variable (data.teachers) is empty I am not able to test if the value is taken from the localStorage and applied to show the saved drop down option.

Do you have any directions on how to test this, i.e. how was this tested during development?

**Comment by a18matna** [comment]
> I am able to see that the store to localStorage works (by manually adding more options to the examinator dropdown) but since the teacher-variable (data.teachers) is empty I am not able to test if the value is taken from the localStorage and applied to show the saved drop down option.
> 
> Do you have any directions on how to test this, i.e. how was this tested during development?

We did the same, we manually added options and simply assumed it would work the same way

**Comment by c14jonfr** [comment]
> We did the same, we manually added options and simply assumed it would work the same way

So you were not able to test if the value from localStorage was working (the last selected option shows up as selected on page reload)?

**Comment by b18alegu** [comment]
I'll close this pull request and put this issue back into "In Progress"

**Pull request closed without merging**
