### PR TITLE
added brackets to avoid errors when checklogin = false

### PR DESCRIPTION
**Pull request by a17poner**

### CODE REVIEW

**Comment by a17poner** [comment]
should be possible to be logged out and go into codeviewer

**Comment by a17maxsj** [comment]
Did not get an error at all on webserver, is this limited to local instances?

**Comment by a17poner** [comment]
May be related to php error settings? does the webserver react to undefined variable errors thrown or will it be silent about them?

**Comment by a17maxsj** [comment]
@HGustavs

**Pull request merged**
