### PR TITLE
G1 2021 w21 #11087

### PR DESCRIPTION
**Pull request by a19taral**
Added the missed parenthesis

### CODE REVIEW

**Comment by a19taral** [comment]
To test: check if the variant in the background changes when a hash pops up in a bit or färg dugga.

**Comment by a17alfja** [comment]
image
You can remove the other part of the if-statement completely (showduggaservice.php)

**Comment by a17alfja** [comment]
nvm

**Review by a19rebsa — CHANGES_REQUESTED** [review]
When going to the hash-url you get redirected to the 404-page, so this solution breaks something.

**Review by a13zanal — CHANGES_REQUESTED** [review]
I end up on page 404 when I enter a saved Url.

**Comment by a17alfja** [comment]
I think the submission is not saved because the variant is unknown when it saves (with "SAVDU" opt parameter).

**Comment by a19taral** [comment]
can you check again now

**Comment by a17alfja** [comment]
I think I have found a solution
image
+
image
(in dugga.js)
The variant value wasn't set before save, so it randomized. Should hopefully work.

**Comment by a19taral** [comment]
> I think I have found a solution
> image
> +
> image
> (in dugga.js)
> The variant value wasn't set before save, so it randomized. Should hopefully work.

worked like a charm. Nice work!

**Review by a13zanal — APPROVED** [review]
Now it works just fine! 👍🏻

**Review by a19rebsa — APPROVED** [review]
It works! 👍

**Pull request merged**
