### PR TITLE
 Arrows are either too big or lines have to be adjusted #13462 

### PR DESCRIPTION
**Pull request by b21phiro**
Issue: https://github.com/HGustavs/LenaSYS/issues/13462

### CODE REVIEW

**Comment by b21phiro** [comment]
NOTE: The arrows do NOT rotate when diagonal.

**Review by a21aldsa — CHANGES_REQUESTED** [review]
While yes, you can make diagonal lines between state elements now. And yes, as previously noted, the arrow is still bugged. This PR can't be approved, in my opinion, because this has negatively affected other parts of the system; the lines between IE and UML. These should not be able to go diagonal. The attached screenshot shows two IE elements with a wrong line and, subsequently, bugged icons.

image

**Comment by a21aldsa** [comment]
Also, the lines feel very "floaty", as in, they dont snap to left, right, up, down, and now, corners, like i would imagine they should. But perhaps this on purpose as a part of a design choice you have made?

**Comment by c21adano** [comment]
This pr has conflict with the stable branch, the first two conflict only occupy the same rows and can coexist, but the conflicts at 7919 and 8152 have real conflicts with the stable branch.

So the change that happend on the stable branch added -sd at the end of the class, while this pr has changed som of the numbers on "points". Im unsure if the stable version points numbers should be used or this pr points numbers. 

I therefor ask for help regarding distinguish which changes should be keept or changed to resolve the conflict. Of course the conflict comes after making the requested changes.

**Comment by a21aldsa** [comment]
Oh and I think you should remove the log message that is still in the code before merging.

**Comment by b21phiro** [comment]
Fixed so only SD elements go diagonally.

**Comment by c21adano** [comment]
I resolved the 4 merge conflicts, the first conflict was due to two functions being created on the same line, the 2nd conflict was on ~7683 were this issue split remade and if into an else if, while another issue wrote more code on it, keept the else if with the new code.
3rd and 4th conflict was due to the size change on arrows, another issue added a new sd class to those arrows, i keept the size change and added back the sd class.
This will need a new round of testing to check for problems.

**Review by a21aldsa — CHANGES_REQUESTED** [review]
The changes requested have been implemented. But, I noticed something that I did not before. The lines change drastically depending on current zoom level. Here's a screenshot showing the line as it is supposed to be, this is at 1x zoom:

image

And here is one, of the exact same line and location, just slight more zoomed in, at 1.5x:

image

I do not know if this is within the scope of this issue, perhaps it is a new issue but that is not for me to decide.

**Review by a21aldsa — APPROVED** [review]
still the same

**Pull request merged**
