### PR TITLE
G1 2021 #10574

### PR DESCRIPTION
**Pull request by a19frebo**
Created course G1- Webbutveckling - datorgrafik.
Created all assignments for the course, and Iframed all assignments along with a text submission for each assignment.

### CODE REVIEW

**Comment by B18mohah** [comment]
image
images gets lost in the transition from Lenasys to Canvas.
image

**Review by a18osken — COMMENTED** [review]
It seems that using https in the iframe link prompts a certificate check which our hosting does not have, simply removing the https should work hopefully then we won't get prompted

**Comment by a19frebo** [comment]
We could not install an SSL certificate so we changed all the IFrame links to http:// instead of https://, and now the images are shown correctly aswell.

**Review by a18osken — APPROVED** [review]
All the previous issues have been solved, you's done it sirs

**Review by B18mohah — APPROVED** [review]

**Pull request merged**
