### PR TITLE
G3 2024 v5 #15033

### PR DESCRIPTION
**Pull request by b22chran**
Implemented regex to the inputs for filename and github-link so it matches the requirements. 
Added so it visualize if an invalid input is entered and that a template needs to be chosen before saving the information.

### CODE REVIEW

**Review by b22marah — CHANGES_REQUESTED** [review]
Code looks good, but indentation and inline-css could be worked on.
image
The image above shows current code indentation, and the following will show a suggested indentation, which is more consist and clear for the future reader / developer:
image
The suggested indentation change, moved variable declaration from middle of function to the top where the rest of the variables are declared. Also spaced every if-statement so it's clearer for which if-else block belongs to who.

For the inline css we see alot of inline-css which there are currently other issue active regarding the removal of inline-css to using a css file instead. There are columns in the html, which has the same class names but still css is set for every occuring instance of this class, which should be removed and placed in the css file instead, a image below shows a example of this.
image

**Comment by b22marah** [comment]
Besides previous comments, the functionality of the code works well and as intended:
image

And with correct inputs:
image

Well done! 👍

**Comment by d22mikwe** [comment]
LGTM!

**Comment by a22moamy** [comment]
Please avoid using "var" in code and use "let" or "const" instead.

**Pull request merged**
