### PR TITLE
Reverting while creating edge #13202

### PR DESCRIPTION
**Pull request by a21oligu**
Fixed an issue where reverting changes (ctrl+z) while creating an edge causing the app to break. Fixed by clearing/resetting ghost element and line.  Solves issue #13202

### CODE REVIEW

**Comment by b21willu** [comment]
"If you press ctrl z while holding a line after it has been connected to an entity on one side, everything but the lines are removed."   It seems like this doesnt work like expected. The lines are removed now but everything else thats been put on the diagram still gets removed. It should not remove everything, just deselect the line that got connected.

**Comment by a21oligu** [comment]
> "If you press ctrl z while holding a line after it has been connected to an entity on one side, everything but the lines are removed." It seems like this doesnt work like expected. The lines are removed now but everything else thats been put on the diagram still gets removed. It should not remove everything, just deselect the line that got connected.

Pressing ctrl+z will cancel the editing and undo the last change. Did you test the correct branch?

**Comment by a21oligu** [comment]
> > "If you press ctrl z while holding a line after it has been connected to an entity on one side, everything but the lines are removed." It seems like this doesnt work like expected. The lines are removed now but everything else thats been put on the diagram still gets removed. It should not remove everything, just deselect the line that got connected.
> 
> Pressing ctrl+z will cancel the editing and undo the last change. Did you test the correct branch?

Also, I believe there is an issue while reverting when only 2 changes are made. The app reverts both changes, making it look like all items disappear.

**Comment by b21willu** [comment]
> > > "If you press ctrl z while holding a line after it has been connected to an entity on one side, everything but the lines are removed." It seems like this doesnt work like expected. The lines are removed now but everything else thats been put on the diagram still gets removed. It should not remove everything, just deselect the line that got connected.
> > 
> > 
> > Pressing ctrl+z will cancel the editing and undo the last change. Did you test the correct branch?
> 
> Also, I believe there is an issue while reverting when only 2 changes are made. The app reverts both changes, making it look like all items disappear.

I tried with multiple entities and lines before and it still removed everything, dont know what went wrong. But i tried again and  now its working fine, except like u said when 2 changes are made but that seems to be another issue. Looks good!

**Comment by a21oligu** [comment]
> > > > "If you press ctrl z while holding a line after it has been connected to an entity on one side, everything but the lines are removed." It seems like this doesnt work like expected. The lines are removed now but everything else thats been put on the diagram still gets removed. It should not remove everything, just deselect the line that got connected.
> > > 
> > > 
> > > Pressing ctrl+z will cancel the editing and undo the last change. Did you test the correct branch?
> > 
> > 
> > Also, I believe there is an issue while reverting when only 2 changes are made. The app reverts both changes, making it look like all items disappear.
> 
> I tried with multiple entities and lines before and it still removed everything, dont know what went wrong. But i tried again and now its working fine, except like u said when 2 changes are made but that seems to be another issue. So my bad, the solution looks good!

I have now solved the merge conflict, and this pull request should be ready to merge once you have approved

**Comment by b21willu** [comment]
Looks good!

**Pull request merged**
