### PR TITLE
Removed Random css dugga pop-up window #10601

### PR DESCRIPTION
**Pull request by a13zanal**
Removed Random css dugga pop-up window in html_css_dugga.html and Replaced this window with a instruction container.

### CODE REVIEW

**Review by a18osken — APPROVED** [review]
It looks good! 🥇 

The instructions themselves could do with a touch-up, but it also seems quite irrelevant.

**Comment by B18mohah** [comment]
this solution works well for students and not for teachers.

**Review by B18mohah — APPROVED** [review]
this solution works well for students and not for teachers.

**Comment by B18mohah** [comment]
this solution works well for students only and the teacher.

**Pull request merged**
