### PR TITLE
added test proposals to courseedservice

### PR DESCRIPTION
**Pull request by b21antbr**
Co-authored-by: c21axepe c21axepe@student.his.se

### CODE REVIEW

**Comment by a19hakja** [comment]
I'm a bit confused. Not saying anything is wrong, I'm just wondering if we really need this? Since we're already writing test descriptions with proper values for each file, before we even do the real tests. And if we do in fact need this and this is what was asked for, it isn't something I would look for in a file that has to do with functional requirements. you feel me?

I might not be in charge anymore so it isn't really up to me. I'll check in with management to make sure that this is what they want, aswell as hold out for an answer from you before

**Comment by d21erisu** [comment]
> I'm a bit confused. Not saying anything is wrong, I'm just wondering if we really need this? Since we're already writing test descriptions with proper values for each file, before we even do the real tests. And if we do in fact need this and this is what was asked for, it isn't something I would look for in a file that has to do with functional requirements. you feel me?
> 
> I might not be in charge anymore so it isn't really up to me. I'll check in with management to make sure that this is what they want, aswell as hold out for an answer from you before

It's not wrong, just too close to reality. We want as fuzzy abstract proposals as possible if that makes sense. Just a clue on how to test it, not an actual way to test.

**Review by a19hakja — CHANGES_REQUESTED** [review]
Yeah i felt it being a bit fuzzy too, try to aim for something more like this https://github.com/HGustavs/LenaSYS/blob/master/backend-models/functional-requirements/FRD_Fileedservice.md

**Review by a19hakja — APPROVED** [review]
aight this looks good, i'll approve

**Pull request merged**
