### PR TITLE
Tabel sorting fix for the access, test and files tab.

### PR DESCRIPTION
**Pull request by a16joare**
This is a solution that solves the sorting problem for the tables in access, test and  files tab on course front page. Instead of using 3 different compare functions i made one compare function that all sortingTables can use. The compare function is universal and can be used for more tables later on.

This solution works for the tabels at the pages stated above but do not work for the results table under the "Results tab" on the course front page.

My suggestion is that we take this solution and then adding the results table as an new issue and trying to solve that one with this solution.

### CODE REVIEW

**Comment by HGustavs** [comment]
There is a default sorting function used in sortabletable one idea would be to replace this default with this function if this works better.

This way all default-search functions are automatically better.

**Comment by a16joare** [comment]
This solution only makes the compare function for each table to work universal. Before this all tables had an own implementation of compare function. I just made one compare function that works for all tables.

**Comment by a17oscno** [comment]
Ok to merge, following the code standard and the code works

**Comment by a17pongo** [comment]
Please rewert my change if this merge is not ok, I was a little quick to accept.
sorry!

**Pull request merged**
