### PR TITLE
fixed #563 - the position of the login button is now correctly displayed

### LINKED ISSUE #563: Login button shows incorrectly in chrome
The fault does not lie in CSS

### PR DESCRIPTION
**Pull request by a13chrju**
changed the name of one of the "navheader.php" files too while I was at it since it's confusing to work on two files at the sime time that has exactly the same name.

### CODE REVIEW

**Comment by a13chrju** [comment]
never mind the name change of the file "navheader.php", just saw that some files still links to "navheader.php" instad of the new "navheader1.php". :)

**Comment by b13danso** [comment]
This is really conflicting with issue #551. The changes made to the css(loggedout-class) is not relevent for this issue. I dont see the point in changing the <td> to <div>s and closing the <table> before the checklogin(). The misspositioning is a matter of css and it is an easy fix which is already stated in issue #549, this is a duplicate.

**Comment by a13chrju** [comment]
I just didnt understand why they would use tables for positioning items in html therefore I changed it to divs and removed some tr-tags etc. :) but you're right, personally thought it was easier to see after my edit

**Comment by c13chrjo** [comment]
Since this issue already exist and a fix has been made I will close this pull.

**Pull request closed without merging**
