### PR TITLE
Clicking on file will now show a download link and/or a preview

### LINKED ISSUE #6938: FileEd: Clicking on filename causes error
When clicking on a filename in the fileed view the console shows a href null error. I assume the filenames are supposed to be clickable to show them in either a dialog or on another page.

### PR DESCRIPTION
**Pull request by a17adasy**
fixes #6938 
When you click on a filename a preview pop up will show up.

Test site: https://a17adasy.gruppb.webug.his.se:20002/DuggaSys/fileed.php?cid=2&coursevers=97732

### CODE REVIEW

**Comment by a17anter** [comment]
Unable to test on the webserver because there are no files/images etc. to "preview" and it's not possible for me to upload new ones, I only get error "No file found - check upload_max_filesize and post_max_size in php.ini" and I can't find the reason why.

**Comment by b17nicsv** [comment]
Before merging I would like to hear that it works on the webserver aswell.

**Comment by a17alian** [comment]
I think I have the same problem, both uploading and previewing/ downloading file works fine on local:
image

But uploading on webserver casuses error "No file found - check upload_max_filesize and post_max_size in php.ini " and preview looks like this. Downloading results in a "file cannot be found" error. 

image

**Comment by b17nicsv** [comment]
This was discussed on the kundmöte. A place to start is to check apache server settings. There might be some Apache standard settings on the server which needs to be changed.

**Comment by b17nicsv** [comment]
Since no changes were made until now. I would like the branch this is put on @a17adasy so we can archive it for next year instead! 🎉

**Comment by b17nicsv** [comment]
https://github.com/HGustavs/LenaSYS/tree/GruppB2019W21%236938

The branch which contains the code used here.

**Comment by a17adasy** [comment]
The branch with the code: https://github.com/HGustavs/LenaSYS/tree/GruppB2019W21%236938

**Comment by b17nicsv** [comment]
I've set the servers post_max_size to 128M and upload_max_filesize to 64M and it didn't fix the issue. 

To change the values:

* Go to /etc/php/7.0/cli
* Sudo nano php.ini
* Sudo service apache2 restart

**Pull request closed without merging**
