### PR TITLE
G3 2024 v7 #15626

### PR DESCRIPTION
**Pull request by b22chran**
Removed the console.log that cluttered the console. See the issue https://github.com/HGustavs/LenaSYS/issues/15626 to see how it looked before. Also check with the responsible of issue (d22mikwe) or group leader (a22moamy) if it is correct.

### CODE REVIEW

**Review by a22ahmom — CHANGES_REQUESTED** [review]
When adding new items in a course these messages popup in the console. 
Screenshot 2024-05-17 110126

However when creating a new item the item does not seem to be created at all.
Screenshot 2024-05-17 110435

By talking to group leader (a22moamy) the only relevant messages that should popup in the console are the below.
Skarmavbild_2024-05-16_kl

**Comment by b22chran** [comment]
I tried to put the code back that i removed and it still not creating new items. I don't know if that is another issue that have appeared from something else? I get this error when trying to create a code-item in a course:
Skärmavbild 2024-05-17 kl  12 08 46
I think this is supposed to be the call that gets posted in the console if the creating of items is successful.

**Comment by b22chran** [comment]
Have been trying some more of the creating of items, and it seems like it works fine in "Demo Course" but not in some of the other courses. When creating an item in Demo Course this will be the outcome: 
Skärmavbild 2024-05-17 kl  14 29 01

The console-text in the green square is an Ajax-call that is called by an intervall and not by creating an item.

**Review by a22ahmom — CHANGES_REQUESTED** [review]
The clutter still exists in the console, remove it.

Screenshot 2024-05-17 162549

**Review by a22ahmom — APPROVED** [review]
Looks good!

Screenshot 2024-05-20 095901

**Pull request merged**
