### PR TITLE
GruppB2019W18#6321

### PR DESCRIPTION
**Pull request by b17nicsv**
[#6321](https://github.com/HGustavs/LenaSYS/issues/6321)

### CODE REVIEW

**Comment by a17pongo** [comment]
@b17nicsv have the changes been implemented?

**Comment by a17pongo** [comment]
Have looked into rebase but it seems more complicated at this point. I suggest closing this pull request and create a new branch for the current week and then reference this pull request so history won't be lost.

**Comment by b17nicsv** [comment]
Yes. I agree. I'll make a new issue and pull request it. You can close this one. 👍

**Comment by a17pongo** [comment]
closed because this pull request was too old.

**Pull request closed without merging**
