### PR TITLE
Toggle load button as well as dropdown #13680

### PR DESCRIPTION
**Pull request by b21oscpe**
The "load" button is now toggled instead of fixed. It has also been styled according to the design of the options-pane

### CODE REVIEW

**Review by a21nibah — CHANGES_REQUESTED** [review]
can you please change this so it uses display instead of the way you are doing it now? something similar to the dropdown button. The button hides for a normal user but it is still there for a screen reader. Or just set hidden=true which would work as well and would be less code to write I think. But display set to None I believe is better and is how elements are hidden in modern web development.

**Comment by b21eriho** [comment]
Test out using hidden=true, better availability would be preferred

**Comment by b21oscpe** [comment]
b7a3de2f389fcbadf16fe3a8f37ca61c
Found this after a quick search, but I will look into using "hidden=true", although I think it this solution might end up weird visually

**Comment by b21eriho** [comment]
If it doesn't work visually we'll have to reassess

**Pull request merged**
