### PR TITLE
Updated icons in diagram dugga #11395

### PR DESCRIPTION
**Pull request by a20samul**
Updated svg icons in diagram dugga to give them a unified look.

### CODE REVIEW

**Comment by c20emili** [comment]
Tested by looking the icons and the are more uniform and clearer than the previous ones. The code has been wrongly indented.

**Comment by b19karhj** [comment]
Fixed the indented code so its correct, before merge

**Comment by b19karhj** [comment]
Indentation is now correct. Good for merge.

**Comment by b19karhj** [comment]
Merge completed

**Pull request merged**
