### PR TITLE
Disabled select all in edge creation mode

### PR DESCRIPTION
**Pull request by a19steis**
Disabled CTRL+A in edge creation mode as suggested in the issues comments.

### CODE REVIEW

**Review by a19chrel — APPROVED** [review]
The solution works as it should, good job!

**Review by a19chrel — CHANGES_REQUESTED** [review]
The code works (disable the SELECT ALL keybind) in line-creation, but the problem is still existing if you entering line-creation with selected elements, the line-creation mode trys to add a line to context[0] and context[1].

**Review by a19chrel — CHANGES_REQUESTED** [review]
The diagram still tries to create a line when selecting all elements in an element-creation mode and then switch to line creation with the buttons. Seems to have with the "mouseup" event on the tool-bar to do.

**Comment by a19steis** [comment]
This fix solves the immediate issue, but by removing the mouseup event from toolbar may introduce other issues that needs to be resolved.

**Review by a19chrel — CHANGES_REQUESTED** [review]
While creating this new fuction `tup,` the comment for `mup` was moved above incorrect function. Also an comment for `tup` would be nice.

**Review by a19chrel — APPROVED** [review]
LGMT, nice work!

**Pull request merged**
