### PR TITLE
Update in resulted.php - modification of heading and it's title

### PR DESCRIPTION
**Pull request by a18ismca**
The heading was replaced to far left instead of being centered. Also, the title was changed to increase comprehension of the site.

Co-Authored-By: a17pioja <a17pioja@users.noreply.github.com>

### CODE REVIEW

**Comment by a18ismca** [comment]
@a18viksa okay! we are going to create another issue that addresses several php files and not only this one. thanks for suggesting :)

**Comment by a18ismca** [comment]
@c14jonfr okay! we will work on it... i think that new issue is already in progress in our project... so if you take a look and then comment what you think about it :)

with @a17pioja

**Comment by b18alegu** [comment]
I'll put this back to in progress since you are working on it 👍

**Comment by a18ismca** [comment]
issue #8131 solves the problems you have addressed in this issue @a18viksa and @c14jonfr... so it would be good if both of you approve this issue so this issue correspond with the other new issue #8131

**Pull request merged**
