### PR TITLE
Lines don't connect vertically #13540

### PR DESCRIPTION
**Pull request by a19clasv**
Both lines and arrows now connect for SD elements.

### CODE REVIEW

**Comment by a19clasv** [comment]
Put this in a json file if you want to use the diagram i tested it on.
{"data":[{"kind":"SDState","name":"State1","stroke":["#383737"],"attributes":["do: func1"],"x":474,"y":169,"id":"A38133"},{"kind":"SDState","name":"State3","stroke":["#383737"],"attributes":["do: func3"],"x":957,"y":773,"id":"201E22"},{"kind":"SDState","name":"State2","stroke":["#383737"],"attributes":["do: func2"],"x":696,"y":443,"id":"B78609"},{"kind":"UMLInitialState","stroke":["#383737"],"x":195,"y":469,"id":"C8631E"},{"kind":"UMLFinalState","stroke":["#383737"],"x":1437,"y":495,"id":"2D6A28"}],"lines":[{"id":"35702C","fromID":"C8631E","toID":"A38133","type":"SD","label":"","startLabel":"","endLabel":"","startIcon":"ARROW","endIcon":"ARROW"},{"id":"6D48F5","fromID":"A38133","toID":"B78609","type":"SD","label":"","startLabel":"","endLabel":"","startIcon":"ARROW","endIcon":"ARROW"},{"id":"8B7F9F","fromID":"201E22","toID":"2D6A28","type":"SD","label":"","startLabel":"","endLabel":"","startIcon":"ARROW","endIcon":"ARROW"},{"id":"111B4D","fromID":"201E22","toID":"B78609","endIcon":"ARROW","type":"SD","label":"","startLabel":"","endLabel":"","startIcon":"ARROW"}]}

**Comment by a19clasv** [comment]
The easiest way is to export a diagram in the options, replace the contents with my diagram and import it

**Review by a21aldsa — CHANGES_REQUESTED** [review]
The SD lines connect just fine although looking at the issue, I would imagine this covers all lines for all elements. But the IE lines still do not connect properly vertically. I am not sure if this is within the scope of this issue though, @b21oscpe will have to decide that.

**Comment by b21oscpe** [comment]
If possible adjust the code to make it work for IE aswell

**Pull request merged**
