### PR TITLE
Fix function linetest() #13785

### PR DESCRIPTION
**Pull request by a19clasv**
1. Made it clear what it does now. Had to brush up on my linear algebra for that.
2. It should return a boolean if it's necessary to change it. It's only used to get a boolean value, but it seems like it was also supposed to be used to get intersection points.
3. Removed.
4. Updated and stated.

### CODE REVIEW

**Comment by a19clasv** [comment]
Forgot I wasn't supposed to change the functionality. 2. It should return a boolean if it's necessary to change it, but it returns x and y at the moment.

**Review by a21nibah — CHANGES_REQUESTED** [review]
I am not a fan of how returns are handeled right now. Having true and false does not make sence if it does not return true and instead returns an object.
It would be better to return undefined if the lines do not intersekt and an object if it does.

**Comment by a19clasv** [comment]
It's stated in the issue that I shouldn't change the functionality, just decide if the function should return either a boolean or an object. I've already done that.

**Comment by a19clasv** [comment]
Basically, I'm supposed to come up with a decision and not implement it. My decision is in 2 and it's not implemented.

**Comment by a21nibah** [comment]
> It's stated in the issue that I shouldn't change the functionality, just decide if the function should return either a boolean or an object. I've already done that.

the issue states that you should decide weather the function should return either boolean values(true/false) or an object and (null or undefined)
my suggestion is to return an object  and undefined
or if the intersections are not being used anywhere in the code after the test function is called return either true or false.

**Comment by a19clasv** [comment]
"or if the intersections are not being used anywhere in the code after the test function is called return either true or false." I already wrote that it's only used to get a boolean value. That means that you agree with me.

**Comment by a21nibah** [comment]
My bad. I did not read up on this as i should have, sorry about that. The changes that you have made looks good but i would still prefer that this issue is changed so that you can implement the return type. YOu have already changed comments  the function so  it just makes sence to go all the way.

**Comment by b21phiro** [comment]
The function should only return EITHER objects or boolean values, and should NOT change the basic functionality of the function as it's being used.

As of right now, it returns either false or object. I agree with Nibar about object and/or undefined/null rather then false, if you now choose to return objects.

In my opinion the changes are acceptable, but the return of false is not correct as you return an object if found.

**Comment by b21phiro** [comment]
> Right now it's only being used for boolean values, so it would be best to make it return true or false if we were to change the function. And I'm a bit confused about not changing the basic functionality because changing what it returns would do that.

True, but if the checks are for example ``if (!linetest()) `` it should not matter if it's ``null | false | undefined``

**Comment by a19clasv** [comment]
It returns true or false now.

**Comment by a19clasv** [comment]
[Fix function linetest() #13785 fix 3 #13992](https://github.com/HGustavs/LenaSYS/pull/13992) is the new pull request for the issue.

**Pull request closed without merging**
