### PR TITLE
fix for #12756

### PR DESCRIPTION
**Pull request by b22jonan**
added ranges to the drawRulerBars function so it only draws lines that would be visible 
also added a quickfix for the long bars since they dissapeared if i just added the range.

### CODE REVIEW

**Review by a22ricni — APPROVED** [review]
It seems to be working. I tested it by first be at coordinate 1000,1000 and it lagged in the week branch. Then switch branch to this issue and i went to 1000,1000 coordinate, and it didn't lag.

**Review by a22jacka — CHANGES_REQUESTED** [review]
Tried zooming a bit and it messed up the rulers alot

bild
4x zoom
bild
1.25x zoom

Could also add some spaces on if-statements that it follows `if (...) {`. Can also be fixed afterwards so not the most important

**Comment by b22jonan** [comment]
> Tried zooming a bit and it messed up the rulers alot
> 
> bild 4x zoom bild 1.25x zoom
> 
> Could also add some spaces on if-statements that it follows `if (...) {`. Can also be fixed afterwards so not the most important

fixed the problem witht the zoom, should work now

**Comment by b22jonan** [comment]
fixed issue completely this time, no issues when zooming in or out

**Review by a22jacka — APPROVED** [review]
The rulers now take up the entire width/height like they're supposed to

**Review by a22ricni — APPROVED** [review]
It seems to be working. Tested it first by first be at coordinate 1000,1000 and it lagged in the week branch. Then switch branch to this issue and i went to 1000,1000 coordinate, and it didn't lag. And also tested the zoom if it still works and I didn't find any problem with it.

**Pull request merged**
