### PR TITLE
G2 2021 w19 issue#10831

### PR DESCRIPTION
**Pull request by a19danla**
Updated the file with template literals and row breaks to increase readability.
Hopefully it wont break the swimlane functionality this time.

Co-Authored-By: b19wilfo 62884368+b19wilfo@users.noreply.github.com

### CODE REVIEW

**Review by a18willi — CHANGES_REQUESTED** [review]
Arrows are hidden on moments that are collpased (see Färgduggor below)
image
All other functionality seems to work though.

**Review by a19isada — CHANGES_REQUESTED** [review]
The arrow pointing to the right on moments is not visible when hiding duggas under a moment
image

**Review by a18willi — APPROVED** [review]
Looks better now!

**Review by a19isada — APPROVED** [review]
Works as normal now.

**Pull request merged**
