### PR TITLE
G3 2023 v6 issue#13549

### PR DESCRIPTION
**Pull request by c21sebar**
For issue https://github.com/HGustavs/LenaSYS/issues/13549
Clicking the refresh button on a moment now creates a codeexample with the name of the "selected" folder.
Since the "selected" folder/directory is not yet implemented we have a harcoded string for this.
This string is located in sectioned.js at line 3602, for your testing change this to a folder you have access to with relevant files.
Note that this is directory should only include the files relevant to the code-example, no subdirectories or any other files. Minimum 1 file and max 5 files because no support for other templates in a code-example.

A codeexample is created with the correct name.
A box for each file in the folder is created and linked to the code-example.
A listentries is created linked to the codeexample with the code-example type.

There is a check if there already is a code-example and if there is do the update.
Update not yet implemented.

Support for creating multiple code-examples is done/considered but needs the https://github.com/HGustavs/LenaSYS/issues/13897 to implement correctly with that solution to how and where the "moment"folder is saved.
A simple for loop on each folder with our createExample method on each of these folders in that "moment"folder.

### CODE REVIEW

**Review by c21rebja — COMMENTED** [review]
I was unable to test to see if this worked. 

When creating a new course, nothing was added into the courses-folder since this version of the code never downloads the files, only the metadata. I did however see the logs in the console, so the code runs, but it didn't generate any code examples. 

I am not sure how you made it work, but I am unfortunately out of time to test this any further, so a new tester will be assigned later today.

If this works properly for the next tester, it is possible the issues were on my end.

**Review by a21henhe — COMMENTED** [review]
I am getting this code to work, where the file for the code examples is created and the examples are created inside. The issue I am facing is that the content of the code examples is not displayed, as it states that the files (with correct names) cannot be found: 
image

I am not sure based on the previous description if this issue is meant to display the contents of these examples or not @c21sebar @b21sebgr

**Review by b21leowa — COMMENTED** [review]
I guess it works as intended but as Henric said about the text file not found. 

But moment is not working as smooth as I hoped it to work. But that is another issue.

**Comment by b21sebgr** [comment]
The file not displaying correctly is an other issue, other than that it seems to work okay and should be merged or have i understood something incorrectly?

**Comment by a21henhe** [comment]
> > 
> 
> i will gladly take a look at this if you show where you found this cleanup things

Good, it seems you found what I commented on without me pinpointing it :)

Although:
In dugga.js, please remove double spacing on line 1282-1284

and in sectioned.js please check the indentation of ajax-query between lines 3012-3015, it looks goofy on github :)

After that it looks fine :)

**Comment by c21sebar** [comment]
> > > 
> > 
> > 
> > i will gladly take a look at this if you show where you found this cleanup things
> 
> Good, it seems you found what I commented on without me pinpointing it :)
> 
> Although: In dugga.js, please remove double spacing on line 1282-1284
> 
> and in sectioned.js please check the indentation of ajax-query between lines 3012-3015, it looks goofy on github :)
> 
> After that it looks fine :)

I dont' know why the indentation looks odd in github but in vscode it look like this:
image
and in github it look likes this:
image

**Comment by b21leowa** [comment]
> > > > 
> > > 
> > > 
> > > i will gladly take a look at this if you show where you found this cleanup things
> > 
> > 
> > Good, it seems you found what I commented on without me pinpointing it :)
> > Although: In dugga.js, please remove double spacing on line 1282-1284
> > and in sectioned.js please check the indentation of ajax-query between lines 3012-3015, it looks goofy on github :)
> > After that it looks fine :)
> 
> I dont' know why the indentation looks odd in github but in vscode it look like this: image and in github it look likes this: image

That is because you have 4 spacing instead of 2.

**Comment by b21leowa** [comment]
Will you fix the if statements and switch it to a switch instead? Otherwise i'm okay to merge this issue.

**Pull request merged**
