### PR TITLE
#13201 Study potential microservice documents and document all unique…

### PR DESCRIPTION
**Pull request by a21ponkr**
… occurrences

Added Accessed service, Fileed service, Highscore service

Currently work in progress

### CODE REVIEW

**Comment by a19hakja** [comment]
Hey, is this work in need of review yet?
Since it's a pull request I'd set it up for review, but it also says work in progress.

If so i can assign somebody, otherwise just hit me up when it's done

**Comment by a21ponkr** [comment]
Forgot to rename the text-file but I will fix that after the review is done, in case of other fixes needed.

**Review by a21oscgu — CHANGES_REQUESTED** [review]
Looks good! Rename the text-file

**Review by a21oscgu — APPROVED** [review]
Looks good!

**Pull request merged**
