### PR TITLE
Fixed red background in add popup

### PR DESCRIPTION
**Pull request by a21lukpo**
There is now no red background, only a red border that shows if the input is incorrect, also changed background color when input is correct since this was originally white and the input text couldn't be seen. This can be tested on my server version https://cms.webug.se/root/G3/students/a21lukpo/LenaSYS/DuggaSys/courseed.php

### CODE REVIEW

**Review by g21emmka — APPROVED** [review]
These changes only works on _edit course version_ and _new course version,_ on these two places it looks good and works as intended.

**Comment by a21rammo** [comment]
@g21emmka the branch has conflicts FYI

**Comment by g21emmka** [comment]
@a21rammo I know I have talked to @c21sebar about this, he will look into this. That's why i just left a comment about the changes that has been made on this issue.

**Comment by a21rammo** [comment]
Yeah i found out that this PR is trying to change the variabel name.style.backgroundcolor. There is one PR that was merged 18 hours ago that also changed this variabel. @b21leowa and @a21lukpo will needs to sort out which is correct way of the input fields.


image

**Pull request merged**
