### PR TITLE
Arrows hidden on moments in sectioned

### PR DESCRIPTION
**Pull request by a19samke**
@a18danli (CO-WORK)
we deleted the unnecessary code,   and add a snippet of  code that makes the arrows show and hide button work

### CODE REVIEW

**Review by a18willi — CHANGES_REQUESTED** [review]
When using the #10191-1 branch some of the arrow funtionalities are broken. For example most of the time the arrows wont change when clicking on the purple bar. Secondly sometimes when clicking on an arrow all arrows on all the sections change aswell. This does not happen in the G2-2021-W16 weekly branch so it seems some of the code changes here have caused it.

**Review by b18phika — CHANGES_REQUESTED** [review]
"Request changes" for the same reasons @a18willi mentioned

**Comment by a19samke** [comment]
Yes we noticed it after we committed the code, for example when I click a the first arrow button then the other buttons moves. But right now we have problems how we can think, is it any of you who realize what the fault is @b18phika  @a18willi

**Comment by a19isada** [comment]
This is to an old branch

**Pull request closed without merging**
