### PR TITLE
Added missing group column to quiz. Fixes #6921

### LINKED ISSUE #6921: Cant create new test
image

### PR DESCRIPTION
**Pull request by a17adajo**

### CODE REVIEW

**Comment by a17adajo** [comment]
Used from https://github.com/HGustavs/LenaSYS/blob/d459d8fb7f2177ee932f1f644b45e8bddfb7c42f/Shared/SQL/deltachange.sql#L89

**Comment by a17maxsj** [comment]
Where in duggaed did this error occur and how can it be verified? Please specify

**Comment by a17adajo** [comment]
when using a fresh install this happens

**Comment by a17adajo** [comment]
The column was added in deltachange in #6562 but no change was done to init_db to make sure the database can be installed fram scratch as described by @HGustavs in 
https://github.com/HGustavs/LenaSYS/issues/6359#issuecomment-487272650

**Pull request merged**
