### PR TITLE
Center camera

### PR DESCRIPTION
**Pull request by a19karwa**
Now you can center the camera around all elements.

### CODE REVIEW

**Comment by a19karwa** [comment]
[#10672 ]

**Review by b19jenda — CHANGES_REQUESTED** [review]
It works really well and looks good, but should all the console.log still be left in the code? or do they serve a purpose?

**Review by b19jenda — APPROVED** [review]
Looks good!

**Comment by a19nikbo** [comment]
Changed the Swedish comments to English comments and removed an unused variable

**Pull request merged**
