### PR TITLE
MOTD now shows an icon in navheader if closed

### PR DESCRIPTION
**Pull request by a19isada**
MOTD now shows an icon in navheader if closed in courseed page. It will stay that way if you visit another part of the site and then return to the courseed page. 
Co-author: @a18willi @b16oskni

### CODE REVIEW

**Review by a19kimgr — APPROVED** [review]
Looks good and works. There is one thing that might be worth looking into, that is if the screen width is below 322px the menu gets a bit scuffed. Maybe add the button to the hamburger menu then? Dont know if this will be an issue since I dont know minimum mobile screen width.

**Review by a19klafr — CHANGES_REQUESTED** [review]
I do not get any buttons in the navheader, or elsewhere when closing the motd on lenasys start-page (courseed.php). Tested in both chrome and firefox.

**Comment by b18phika** [comment]
@a19kimgr The problem with that is that not everybody has the hamburger menu, so that's why it's not in it. We'll discuss whether or not everybody should on the meeting with the customer today. so hopefully that'll be resolved in the near future.

**Review by a19klafr — APPROVED** [review]
Looked for wrong item. Rechecked and everything works as requested

**Pull request merged**
