### PR TITLE
Pop up box #926

### PR DESCRIPTION
**Pull request by a13jansa**
Add some new code in CSS and PHP file

### CODE REVIEW

**Comment by a13henhu** [comment]
I've checked this request, and everything is working as it should.

**Comment by c13caral** [comment]
Everything works good!
But there are some problems with the code standard.

Like in line 206 it is:
      <td>
	Play Link: 
</td>
		<td>
		Important Words:
		</td>

**Comment by a13alfbe** [comment]
Change the colspan of the two <td> that contains #impword and #playlink to avoid using negative margin to position the #impword input. 

There is also an empty <tr> between the #impword and #impwords

**Comment by c12jenek** [comment]
Code standard checks out, approved to merge!

**Comment by c13caral** [comment]
#926

**Pull request merged**
