### PR TITLE
Fix for issue #6733: Add recursive relations

### PR DESCRIPTION
**Pull request by c17matjo**
I've implemented recursive relations to UML classes and ER entities. Recursive relations don't seem to work in exported diagrams but I think that should get it's own issue as this issue has taken a long time as it is. 

bild

#6733

### CODE REVIEW

**Comment by c17matjo** [comment]
> Are recursive lines for ER relations actually needed? I don't remember how ER works very well but from a google search it looks like recursive relations still use the relation symbol which means they should already work without needing a special recursive line.
> bild

Copied from the issue page. I'm not sure if ER entities really need recursive relationship-lines. I'm going to focus on the overlapping issue for now

**Comment by a17celal** [comment]
> > Are recursive lines for ER relations actually needed? I don't remember how ER works very well but from a google search it looks like recursive relations still use the relation symbol which means they should already work without needing a special recursive line.
> > bild
> 
> Copied from the issue page. I'm not sure if ER entities really need recursive relationship-lines. I'm going to focus on the overlapping issue for now

Hm, good question. What do you think? @a14oscna @a17vikab

**Comment by a17vikab** [comment]
> > > Are recursive lines for ER relations actually needed? I don't remember how ER works very well but from a google search it looks like recursive relations still use the relation symbol which means they should already work without needing a special recursive line.
> > > bild
> > 
> > 
> > Copied from the issue page. I'm not sure if ER entities really need recursive relationship-lines. I'm going to focus on the overlapping issue for now
> 
> Hm, good question. What do you think? @a14oscna @a17vikab

Remove the ER recursive lines.

**Comment by a14oscna** [comment]
Recursive lines should exist for ER and it should work just as your image shows c17matjo.

**Comment by c17matjo** [comment]
@a14oscna Since recursive relationships in ER use the regular relation symbols they don't need any special support. My screenshot was made on the normal group branch. What did you mean should be done?

**Comment by c17matjo** [comment]
@a14oscna ?

**Comment by c17matjo** [comment]
I've adjusted the cardinality spacing now. I'm not sure what @a14oscna meant but for now I think you can re-review it.

**Comment by a14oscna** [comment]
Sorry for a late reply. You are correct c17matjo, there should be a relation symbol when recursive relations are made in ER just as your image shows. Only in UML should the line able to be drawn back to the same class.

**Comment by c17matjo** [comment]
Okay. Do you mean that when the user clicks and drags a new line within an ER entity the program creates a new relation symbol with 2 connections to the entity automatically? I think that should get it's own issue as it's more of a shortcut and this issue has a big scope as it is.

**Comment by a14oscna** [comment]
No, you can just keep it as it is, assuming you can drag a line from an entity to a relation, and then an additional line from the relation back to the same entity as your image suggests. :)

**Comment by c17matjo** [comment]
Ah, I see. Then everythings done :)
@a17celal, you cleared to review it now :+1:

**Comment by a14oscna** [comment]
Perfect, will have it in before the big merge today!

**Pull request merged**
