### PR TITLE
G1 2021 w18 #10314

### PR DESCRIPTION
**Pull request by a19taral**

### CODE REVIEW

**Comment by a19simma** [comment]
Press a butt in a dugga and it should console log this
image

**Comment by a19simma** [comment]
issue #10314

**Review by e15marol — COMMENTED** [review]
Local changes are tracked, but there's also a function added (addGroupButton in dugga.js line 894) that's not been used, what is its purpose? Also when saving, and then making changes to a dugga, it sometimes console logs that changes have not been made even though they have been made and are displayed through the counter.

**Comment by b18jacha** [comment]
Can we test in any dugga assignment or does it need to be a group assignment?

**Review by b18jacha — COMMENTED** [review]
Can we test in any dugga assignment or does it need to be a group assignment?

**Comment by a19taral** [comment]
the add Group button is just for the testing convenience and it can be removed, and you can test for any assignment type.

**Comment by a19simma** [comment]
> Also when saving, and then making changes to a dugga, it sometimes console logs that changes have not been made even though they have been made and are displayed through the counter.

It tracks 'clicks', not actual changes. Just when there's an interaction from the user in any way. Also I don't know how to reproduce this error.

**Comment by a19simma** [comment]
Hopefully fixed the issue @e15marol @b18jacha pull the newest branch and check 
image

**Review by e15marol — APPROVED** [review]
It works now, although the counter is console logged twice now, which is a non-issue. Approved, good job! We'll have to clean up the console logs in the future as the console is getting clogged up. But for testing purposes for future functionality changes this can remain for now.

**Review by b18jacha — APPROVED** [review]
Looks good!

**Review by e15marol — CHANGES_REQUESTED** [review]
Just discovered for example in biträkningsdugga 1, that if you have two or more of the bits pressed, and you save, the counter is incremented by 1 everytime you save, and while you have only 1 it displays the correct amount of "clicks" whenever you save, while none of the bits are pressed, the counter does not get displayed in the console. Not sure if this will cause issues for the future, but it should be looked over if its handled appropiately.

**Review by b18jacha — CHANGES_REQUESTED** [review]
Also I just found that when clicking on either one of the two big "0" buttons on bitdugga 1 it counts as a change even tho we haven't changed it to anything.

**Comment by a19simma** [comment]
> Just discovered for example in biträkningsdugga 1, that if you have two or more of the bits pressed, and you save, the counter is incremented by 1 everytime you save, and while you have only 1 it displays the correct amount of "clicks" whenever you save, while none of the bits are pressed, the counter does not get displayed in the console. Not sure if this will cause issues for the future, but it should be looked over if its handled appropiately.

When you click save, for whatever reason it generates every button click again, which is kinda weird. Not sure if we should fix this or leave it for another issue as the number itself isn't really important.

**Review by e15marol — APPROVED** [review]
Works for experimental use of tracking clicks!

**Review by b18jacha — APPROVED** [review]
Great start of a bigger issue.

**Pull request merged**
