### PR TITLE
Fix warning messages in console when pressing FAB in duggaED

### PR DESCRIPTION
**Pull request by b17carma**
Fix for issue https://github.com/HGustavs/LenaSYS/issues/7189

### CODE REVIEW

**Comment by a17andby** [comment]
I have hard time to recreate this problem. I get not error when I press the FAB button in duggaed.php.

Tried to recreate this issue on our test server on our new weekly branch.

**Comment by b17carma** [comment]
I get it at http://gruppc.webug.his.se:20001/DuggaSys/duggaed.php?cid=2&coursevers=97732 when I press the FAB before anything else (Chrome)

**Comment by a17andby** [comment]
> I get it at http://gruppc.webug.his.se:20001/DuggaSys/duggaed.php?cid=2&coursevers=97732 when I press the FAB before anything else (Latest version of chrome, doesn't appear to show the warning on firefox)

can you try again and see if you get the error on the same link that you just posted? gruppc.webug.his.se wasn't updated with the latest changes

**Comment by b17carma** [comment]
Yep, I still get the error message after you updated it

**Comment by a16lisri** [comment]
I can't recreate the problem either.

**Comment by b16johso** [comment]
Can't recreate this

**Comment by a17fellu** [comment]
I cannot recreate this. Have tried with latest Chrome, latest Firefox

**Comment by b17carma** [comment]
Considering nobody seems to be able to recreate this (and since it¨s only a warning in the end) I'll close this pull request :P

**Pull request closed without merging**
