### PR TITLE
Removed unused code in accessed.php. Issue#11067

### PR DESCRIPTION
**Pull request by a18willi**
Issue only mentioned removing ssn, firstname and lastname inputs. But after looking at the code and what it was used for it seemed like the edit user menu code never was used(there werent even a way to open the menu). Hence i've removed the code for the edit user functionality in accessed.php.

### CODE REVIEW

**Review by a19danla — APPROVED** [review]
Other functions seems to be working fine.

**Review by b19wilfo — APPROVED** [review]
Works and as stated there doesn't seem to be a way of accessing the edit user interface so it probably was not used.

**Comment by b18phika** [comment]
There's a function called "closeEditUser" (accessed.js 105-107), that doesn't do anything now that the form has been removed. That should probably be either removed or commented out. 
@a18willi

**Review by a19danla — APPROVED** [review]
Works as intended

**Review by b19wilfo — APPROVED** [review]
Works as it should.

**Pull request merged**
