### PR TITLE
Updated cardenality

### PR DESCRIPTION
**Pull request by a19chrel**
The text is now calculated from the coordinate on the line instead of the end/start point of the line. The offset from the line is also taken into account depending of the number of connected lines to the same side of an entity.

### CODE REVIEW

**Review by a19phith — APPROVED** [review]
Seems to be working, good job

**Review by a19hammi — CHANGES_REQUESTED** [review]
Not sure if this is what should be the expected behavior. I'd love if you took a second look at this. It's not a high priority issue but right now we lack much else to do.

https://user-images.githubusercontent.com/81571224/116985694-20976d00-accd-11eb-88d5-f33ff7002088.mp4

**Review by a19hammi — CHANGES_REQUESTED** [review]
Så här ser det ut på min lokalt. Skall nog inte vara så.

https://user-images.githubusercontent.com/81571224/117012363-2a31cc80-acef-11eb-8093-3f067f6f7934.mp4

**Comment by a19matma** [comment]
Will investigate this further, but yes it might be difficult to get further since what's considered acceptable behaviour is very subjective.

**Comment by a19chrel** [comment]
> 
> 
> Så här ser det ut på min lokalt. Skall nog inte vara så.
> 28e820f2d19e9719db7ce54e20b5c5f6.mp4

Seems like the the line gets connected to right side of the entity instead. I would say this is an problem with the calculation of lines instead of the cardinality-draw. 
bild
But maybe the offset here could be better.

**Comment by a19hammi** [comment]
> 
> 
> > Så här ser det ut på min lokalt. Skall nog inte vara så.
> > 28e820f2d19e9719db7ce54e20b5c5f6.mp4
> 
> Seems like the the line gets connected to right side of the entity instead. I would say this is an problem with the calculation of lines instead of the cardinality-draw.
> bild
> But maybe the offset here could be better.

Yep, we looked at it the other day or so. The line connects to left/right side the very PIXEL that the Refer-top intersects the Car bottom.

**Comment by a19hammi** [comment]
We'll merge this for now and try finding a better solution later.

**Pull request merged**
