### PR TITLE
codeviewer: Ability to maximize a window

### PR DESCRIPTION
**Pull request by a17fellu**
Only a QOL improvement to codeviewer that lets you maximize the window you want to have maximized with a single button press. Right now it supports all templates except for template 9(template 9 is a little broken)

### CODE REVIEW

**Comment by a17fellu** [comment]
I have a reset button i just forgot to push it. Will add that and re-request review

**Comment by a17robes** [comment]
> I have a reset button i just forgot to push it. Will add that and re-request review. As for the single pane template it shouldn't have the maximize function since you cant change its size

True that!

**Comment by a17fellu** [comment]
> 
> 
> Works like a charm! Reset button is a nice touch (exept for template 9, fix later?)

Template 9 itself has a few bugs. This means that it isn't possible to add it to it at this moment. But when it gets fixed its an easy addition.

**Comment by a17poner** [comment]
Nice, is there a issue for fixing the broken things about template 9? if not we should probably make one and have it fixed 😛

**Pull request merged**
