### PR TITLE
G1 2023 v1 #13074 Add a button in the menu for placing statediagram states.

### PR DESCRIPTION
**Pull request by b21eriho**
The button is now there, however it's sometimes there when it would usually be hidden by the system. Selecting it also in some cases doesn't allow you to swap back due to a bug. However all these things are caused by the backend not being implemented yet. Also the icon for a statediagram state is at this point the same as for IE-entity

### CODE REVIEW

**Comment by b21eriho** [comment]
I can't tell how the tooltip is different from your screenshot, in what way is it inconsistent?

**Comment by a21aldsa** [comment]
I have attached a screenshot of the tool tip for ER. Note how it is much cleaner. I understand why you have done it this way but I strongly believe there are ways to rewrite this to look more elegant. Perhaps just add a space between state and diagram since these are two separate words?

image

**Comment by b21eriho** [comment]
Wording updated

**Comment by b21eriho** [comment]
I have implemented the button, and it now gets hidden like it should in the demo diagram and is shown appropriately in dugga.php. However the system will print endless errors when the state diagram tool is selected and if one attempts to place a state the system breaks and no other tools can be selected or used.

This issue is however caused by the values for the state entity are undefined and the system can thus not read them. However the same attribute of the button that allows it to be hidden, causes the system to attempt to read these null values so I cannot bypass this issue. 

Summary: The button is there and is hidden when it should, however selecting it will cause errors and using it will break the system until a reload. Do I create a pull-request with this, since the solution to this issue is to implement the state entity which isn't a part of this issue.

**Comment by c21adano** [comment]
for testing just assign another diagram typ to the button. The state diagram entity will be added in another issue.

**Comment by b21eriho** [comment]
That will not work, in that case the button will be hidden in the same way that that other diagram type, the system is very interlocked in this case

**Comment by c21adano** [comment]
hmm then i guess it should be fine to just test it right now, and fix the issues when we add the state entity to the system.

**Review by a19clasv — APPROVED** [review]
There is a state diagram state button, but there are other issues as mentioned in the previous comments. However, c21adano said to fix the issues when we add the state entity to the system, so it's approved.

**Comment by b21eriho** [comment]
These conflicts are indeed problematic, since both these developments and the ones they are conflicting with seem to have added things starting in the same spots and thus these changes should realistically be added in sequence, not be picked between

**Comment by b21oscpe** [comment]
Pray

**Pull request merged**
