### PR TITLE
G1 2023 v7 #14110

### PR DESCRIPTION
**Pull request by d21matbo**
Reworked the current system to store and map multiple JSON strings to their own key, while they are all in the same string (localstorage). Used this system to connect the saving and loading functions for local diagrams.

You can either save a diagram with the same name to overwrite it, or a new name to save it as a seperate diagram.
AutoSave is called the first time a diagram is saved, and then it is called by the function `saveDiagramBeforeUnload()`

### CODE REVIEW

**Comment by a21nibah** [comment]
would like some clerification. so is the goal that all diagrams should be saved under the key diagrams? issue #14117 uses another implementation of the following where all keys are fetched from local storage rather than this.
    let diagramKeys;
    let localDiagrams;

    let local = localStorage.getItem("diagrams");
    if (local != null) {
        local = (local[0] == "{") ? local : `{${local}}`;
        localDiagrams = JSON.parse(local);
        diagramKeys = Object.keys(localDiagrams);
    

Otherwise it looks good. saves are done as they should and loading is done correctly from what i can see. 
although i can not figure out how you go about saving multiple files as described in the issue. Is this something that has been implemented yet in the UI or what is that about?

**Comment by b21eriho** [comment]
It would seem that multiple issues that realistically should have been assigned in sequence were assigned in parallell. This issue #14110 is the issue that should implement the saving and loading from local storage and make that usable to the user. Due to the aforementioned administrative fault we will have to make some choices resulting in work needing to be redone.

What will happen is that this PR will be merged when tested and then the other issue #14117 will have to be rerun to add the functionality desired there on top of this implementation. Apologies for the lost work.

Regarding the testing please elaborate on what you said about not being able to save multiple files

**Comment by a21nibah** [comment]
the functionality from issue #14117  can be merged without much having to be redone. You really have to remove the functionality that displays all keys and use the eone from this pr. otherwise it should all work since the issue mostly consists of making function calls to the saveDiagram function. 
also the issue for this pr states:
Try to link/hookup the load-save system together. I.e. you can save multiple files, name them, load them.
Has that been implemented? looking at the code seems like it should work but can not find anythin where you can do this in the UI.

**Comment by b21eriho** [comment]
All these things can be done in this implementation, there may be some issue with the availability though I can't say I'm sure of this.

**Review by a21nibah — APPROVED** [review]
from what I can see everything works as it should. loading, saving etc. The code looks good and i can not see any issues during testing. Nice work.

**Pull request merged**
