### PR TITLE
Created folder for markdown-testfiles and created one for github-markdown

### PR DESCRIPTION
**Pull request by a21henhe**
We created a folder called "markdown-testfiles" and moved the previous file "lenasys-markdown.txt" to the folder and created a new text-file which contains GitHub-markdown syntax which can be used to test the GitHub-markdown syntax in the LenaSys-markdown system.

Co-authored by b21leowa

### CODE REVIEW

**Comment by b21geoyo** [comment]
I tested the github markdown testfile and went through the syntax. You seem to included everything. However there are some syntax issues.

1. The dark/light mode image has inconsistent identation, and there are additional spaces between the URL and image name.


2. You can not have text on the same line as a horizontal line like you have in the test file. See image below.
image

Also if you look at the github markdown cheatsheet. It says :

"(In this example, leading and trailing spaces are shown with with dots: ⋅)". So im not sure if the dots should be replaced with spaces in the github test file or not.

Markdown cheatsheet

**Comment by a21henhe** [comment]
> 

@b21geoyo review is fixed in new commit, please re-check :)

**Comment by b21geoyo** [comment]
I reviewed the GitHub markdown test file and everything seems to be fixed from the previous issues, except for one thing that I am unsure about.
In the GitHub markdown test file, sublists are indented with two spaces. I'm wondering if we should use three spaces for the sublists.

When I test the sublists in GitHub using two spaces does not indent the text. You can find these tests below.

This is with 2 leading spaces for the sublists:

1. First ordered list item
2. Another item
  * Unordered sub-list 
1. Actual numbers don't matter, just that it's a number
  1. Ordered sub-list
4. And another item 

This is with 3 leading spaces for the sublists:

1. First ordered list item
2. Another item
   * Unordered sub-list 
1. Actual numbers don't matter, just that it's a number
   1. Ordered sub-list
4. And another item

Just to provide an additional source of comparison, I also tested the Github markdown spacing on an external website.
See the image below.

image

**Comment by a21henhe** [comment]
> I reviewed the GitHub markdown test file and everything seems to be fixed from the previous issues, except for one thing that I am unsure about. In the GitHub markdown test file, sublists are indented with two spaces. I'm wondering if we should use three spaces for the sublists.
> 
> When I test the sublists in GitHub using two spaces does not indent the text. You can find these tests below.
> 
> This is with 2 leading spaces for the sublists:
> 
> 1. First ordered list item
> 2. Another item
> 
> * Unordered sub-list
> 
> 1. Actual numbers don't matter, just that it's a number
> 2. Ordered sub-list
> 3. And another item
> 
> This is with 3 leading spaces for the sublists:
> 
> 1. First ordered list item
> 2. Another item
>    
>    * Unordered sub-list
> 3. Actual numbers don't matter, just that it's a number
>    
>    1. Ordered sub-list
> 4. And another item
> 
> Just to provide an additional source of comparison, I also tested the Github markdown spacing on an external website. See the image below.
> 
> image

This is now resolved, please check again @b21geoyo

**Comment by b21geoyo** [comment]
All the previous issues are now fixed.

**Review by b21geoyo — APPROVED** [review]
All the previous issues are now fixed.

**Pull request merged**
