### PR TITLE
 Lines between states should be possible to label #13081 

### PR DESCRIPTION
**Pull request by a21aldsa**
created a new line type: UML_STATE and gave it its own set of icons, called SDLineIcons. This set of icons contains one icon called ARROW which uses the SVG from UML black triangle. Then I implemented this new line type and made it so that any line between two UML_STATES gets this type. I also modified the options panel for state lines to account for the new line type and its icons, so that the drop down for icon selection is correct.

### CODE REVIEW

**Comment by a21oligu** [comment]
It is currently possible to set cardinalities for an edge. An arrow should only be present on the "toElement" side of the edge, as I believe an edge in a State Chart diagram cannot be bidirectional (and is a transition). Also, the edge can be of "double" kind, which seems wrong.

**Comment by c21adano** [comment]
> It is currently possible to set cardinalities for an edge. An arrow should only be present on the "toElement" side of the edge, as I believe an edge in a State Chart diagram cannot be bidirectional (and is a transition). Also, the edge can be of "double" kind, which seems wrong.

Those are improvements that can be made, but it would be better to focus on that after the merge and allow it to keep its current functions.

Som of the code has to be changed from UML_State to SD to function in the future due to the code changes that were made in issue #13338.

**Comment by a21aldsa** [comment]
Or that functionality can be removed in a later issue, I am indifferent

**Review by a21oligu — APPROVED** [review]
The implemented code solves the issue and I approve, though there are room for further improvements.

**Comment by a21oligu** [comment]
> Som of the code has to be changed from UML_State to SD to function in the future due to the code changes that were made in issue #13338.

This should be fixed before merging

**Comment by a21aldsa** [comment]
> > Som of the code has to be changed from UML_State to SD to function in the future due to the code changes that were made in issue #13338.
> 
> This should be fixed before merging

done

**Comment by a21oligu** [comment]
> > > Som of the code has to be changed from UML_State to SD to function in the future due to the code changes that were made in issue #13338.
> > 
> > 
> > This should be fixed before merging
> 
> done. Note that the elements are still called UML_STATE though, this was not part of my issue nor my code so I do not feel like this PR is in the scope to edit these.

I don't know, I feel like @c21adano is to decide that. There seems to be an merge conflict now though

**Comment by a21aldsa** [comment]
> > > > Som of the code has to be changed from UML_State to SD to function in the future due to the code changes that were made in issue #13338.
> > > 
> > > 
> > > This should be fixed before merging
> > 
> > 
> > done. Note that the elements are still called UML_STATE though, this was not part of my issue nor my code so I do not feel like this PR is in the scope to edit these.
> 
> I don't know, I believe @c21adano is to decide that. There seems to be an merge conflict now though

merge conflict was my bad, i commented out UML_STATE: "UML_STATE" from entitytype, forgetting that this is still used for the actual elements.

**Comment by a21oligu** [comment]
Everything seems to be fine now, and the the pr is ready for merge

**Pull request merged**
