### PR TITLE
Add explanation to the legend for the pink bar indicating national holiday #11126

### PR DESCRIPTION
**Pull request by b16oskni**
Added holiday to legend

Co-author: @a18willi @a19isada

### CODE REVIEW

**Review by a19danla — CHANGES_REQUESTED** [review]
Works good in chrome but can't see any explanation for any of the bars in firefox
image

**Comment by a19danla** [comment]
And in chrome 
image

**Review by b19wilfo — CHANGES_REQUESTED** [review]
The change works on chrome and opera but does not appear to be working on firefox.

**Comment by a19danla** [comment]
When i check on the weekly branch G2-2021-W21 I get the same behaviour, seems like Firefox doesn't like the way its implemented.

**Review by a19danla — APPROVED** [review]
It now works on Firefox.

**Review by b19wilfo — APPROVED** [review]
It now works on firefox as well.

**Pull request merged**
