### PR TITLE
Grupp b2019 w18#5916

### PR DESCRIPTION
**Pull request by a17ludca**
Fixed sortable headers in resulted, sort after fname, lname, ssn and grade.

testing site: https://a17ludca.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732

### CODE REVIEW

**Comment by a17pongo** [comment]
is the test link valid? I did a quick test too and sortable headers do not seem to work

**Comment by c17johha** [comment]
#5916

**Comment by a17ludca** [comment]
Accidental branch-switch in putty so the code you were supposed to test wasn't on the server, mb. Should be able to test now.

**Comment by a17oscno** [comment]
Everything seems to be working as it should so i will aprove the changes and make it ready for merge.

**Pull request merged**
