### PR TITLE
Fixed so you can add picture into the markdown file.

### PR DESCRIPTION
**Pull request by b21leowa**
You can now add an image to a md file with %%% image url, thumbnail size, full size %%%.

Can test it on my server version: https://cms.webug.se/root/G3/students/b21leowa/LenaSYS/DuggaSys/courseed.php

image

This pull request will also fix issue  #13082.

### CODE REVIEW

**Comment by b21leowa** [comment]
I updated it so now you can upload picture as in github.
The alt-text can also be empty.
alt-text
image

**Comment by b21geoyo** [comment]
When adding images in LenaSYS markdown format, it is expected to use ||| instead of %%% unless the customer has requested a change. Also when I test it on your server version it does not work.

**Comment by b21leowa** [comment]
Can you check again please @b21geoyo? I forgot to change branch on my server and I solved so that the image has the same style as in Github. Look my recent screenshot. I accidentally solved 2 issues in one. The issue #13025 and #13082 

image

**Comment by b21geoyo** [comment]
Github flavored markdown for images seems to be working now with alt texts.

**Pull request merged**
