### PR TITLE
showDugga.php - Alternating rows fix #6564 

### LINKED ISSUE #6564: File submission table needs alternating row colors
Submission table needs alternating row colors to better separate the items from eachother
image
Should look more like this imo (not exactly like this, just a rough mockup):
image

### PR DESCRIPTION
**Pull request by a17andby**
Added some css that adds an other color to the rows on showDugga's tables.

Screenshot from 2019-05-03 15-25-03

(forgot to refer the issue: https://github.com/HGustavs/LenaSYS/issues/6564 )

### CODE REVIEW

**Comment by a17andby** [comment]
(For some reason I did this commit with my private github account. andreas-bylund is me)

**Comment by a17adajo** [comment]
Just a heads up. it looks like you did a commit with the wrong user here: 511d01a

**Comment by a17andby** [comment]
> Just a heads up. it looks like you did a commit with the wrong user here: [511d01a](https://github.com/HGustavs/LenaSYS/commit/511d01ac4787c28d27b3caafe05025ed5c161545)

Yes, removed my private account from my git config so it won't happen again, hopefully. Thanks for the heads up anyway :)

**Comment by a17adajo** [comment]
Ok, I did not see your comment about you finding it out yourself :)

**Pull request merged**
