### PR TITLE
G2 2023 v7 14154 create microservice createnewcodeexample

### PR DESCRIPTION
**Pull request by b21kurar**
Moves the functionality to create new items to a microservice and changes to dugga.js to ensure that it is called when creating new items.

The call to the microservice is not commented out, as it doesn't interfere with basic functionality.

### CODE REVIEW

**Review by b21ricni — CHANGES_REQUESTED** [review]
Does work, dunno if i did it wrong tho, but it calls the correct function.
User: Toddler, course: testing, Tried to create new code item
image

**Comment by b21kurar** [comment]
I have added an include to `coursesyspw.php` since this appears to fix some database related problems, other than that I don't know why the includes keep giving me troubles...

**Review by b21ricni — APPROVED** [review]
It now creates a new code, nice! :3

**Comment by d21erisu** [comment]
great

**Pull request merged**
