### PR TITLE
Codeexample sections now shows up under the correct moment. g3-2024-v6-#15319

### PR DESCRIPTION
**Pull request by a20jonda**
Extra:
* Added .vscode to .gitignore to make it easier to debug using visual studio code.
* Fixed errors occurring in sectioned.php due to them obscuring important footer texts.
* Fixed sections not inserting with correct positions or duplicate positions which would break functionality.

### Testing
1. Create a empty test course:
2. Connect https://github.com/LenaSYS/Webbprogrammering-Examples as github URL
3. Create a course version and add 7 Moments with some few random elements sprinkled in. (ajax_api_index, booking and README have a chance of showing up after refreshing moments without choosing anything. The bug can be found before my issue.)
image

4. Ensure that the positions `pos` are correct in `listentries` in the database
image
5. (One at a time) Choose GitHub moment and then press the refresh moment example icon on the moment. After a site refresh the codeexamples should pop up.
image
image
6. Verify  `pos` in the database

### CODE REVIEW

**Review by a22natth — CHANGES_REQUESTED** [review]
Since there currently are issues with creating new courses, the testing was done on a preexisting and empty course instead(Distribuerade System). 

When trying to create a new moment in the course, I am presented with the errors seen below. Additionally, no moment is shown/created on the page. A comparison was done on the weekly branch, to which there were no issues regarding creating a new moment. 
Pasted Graphic


Due to this, no further testing could be done. Fix so that a user can create a new moment within a preexisting course, as it seems this specific functionality might have been lost when solving this issue.

**Comment by a20jonda** [comment]
image
Looking into it. There is something stopping older courses from receiving the github folders.

image
There is not problem with newly added courses.

Most courses already have the correct files and folder meaning that they don't get reset during the install.php

**Comment by a20jonda** [comment]
Resetting files did not solve it
image

**Comment by a20jonda** [comment]
Creating a new branch g3-2024-v6-#15319-v2

**Pull request closed without merging**
