### PR TITLE
 fixed duplicate variable declaration in diagram.js

### LINKED ISSUE #14092: Duplicate declaration of variable
## Description
Inside ``diagram.js`` There's a duplication of a variable called ``changeType``. First at line ~462 and at line ~373.
```
                        var changeType = changeTypes[index];```

```
    save (stateChangeArray, changeType)
```.

## Job
Change the names of the variables, and replace declaration using ``var`` to either ``let`` or ``const`` depending on context.

### PR DESCRIPTION
**Pull request by a21nibah**
fixes #14092
this appears to work as expected when testing but wwhen reviewing check so that i have not missed changing a variable name somewhere.

### CODE REVIEW

**Review by c21theti — COMMENTED** [review]
It looks as if you have kept working on this branch after the issue was resolved, but I might be mistaken, can you take a look at this? @b21phiro / @b21eriho 

image

**Comment by b21eriho** [comment]
I am unsure of what you mean, this PR only has the one commit 
image

**Comment by b21phiro** [comment]
I think you are looking at the overall commits to our branch. @a21nibah comitted #14097 once.

**Review by c21theti — APPROVED** [review]
I've checked the code and what I can see it looks like all variables are changed correctly and none is missed

**Pull request merged**
