### PR TITLE
redirected duggan's login to course page

### PR DESCRIPTION
**Pull request by a19taral**
To test: close the login box in a dugga. this should redirect you to the according course page.
for some reason, sometimes the login box does not appear. just try with another dugga

### CODE REVIEW

**Review by e15marol — CHANGES_REQUESTED** [review]
When exiting the hashbox you get redirected to a null page "http://localhost/lenasys/LenaSYS/DuggaSys/null".
Skärmklipp

By login box in a dugga you are referring to the "Load Dugga" button I assume? This has not changed in functionality, but I suppose this wasn't the goal for the issue regardless.

**Comment by a19taral** [comment]
did you change your local branch to G1-2021-W20-10955 ?

**Comment by e15marol** [comment]
> did you change your local branch to G1-2021-W20-10955 ?

Yes

**Review by b18jacha — CHANGES_REQUESTED** [review]
It still takes us to the null page. Ignore previus comment I did :octocat:

**Comment by a19taral** [comment]
try it this time with incognito

**Comment by a19taral** [comment]
as i saw,  you need to add lenasys to the url to match your settings.
for me it redirect to http://localhost/LenaSYS/DuggaSys/courseed.php

**Comment by e15marol** [comment]
It appears to be working in incognito mode, but not without it.

**Comment by e15marol** [comment]
Also, attempting to enter anything but a correct hash in the Load Dugga window takes you to a 404 page, this might however be a separate issue for when the button has been implemented on the course pages.

**Comment by a19taral** [comment]
according to your settings 
http://localhost/lenasys/LenaSYS/DuggaSys/courseed.php
but  for me it redirects to
http://localhost/LenaSYS/DuggaSys/courseed.php
to work for you , you need to add an extra lenasys in exitHashBox()

**Comment by a19taral** [comment]
> Also, attempting to enter anything but a correct hash in the Load Dugga window takes you to a 404 page, this might however be a separate issue for when the button has been implemented on the course pages.

 maybe they should create another issue for this

**Comment by b19ponka** [comment]
> Also, attempting to enter anything but a correct hash in the Load Dugga window takes you to a 404 page, this might however be a separate issue for when the button has been implemented on the course pages.

It is intended to work this way.

**Comment by b18jacha** [comment]
@a19taral Does it only work in incognito for you?

**Comment by a19taral** [comment]
> @a19taral Does it only work in incognito for you?

yes but i use  chrome for testing

**Comment by e15marol** [comment]
> according to your settings
> http://localhost/lenasys/LenaSYS/DuggaSys/courseed.php
> but for me it redirects to
> http://localhost/LenaSYS/DuggaSys/courseed.php
> to work for you , you need to add an extra lenasys in exitHashBox()

Even with changing my filepath accordingly, it does not appear to be working. It works in incognito as it is initially, so I wouldn't think the path is the issue?

**Review by e15marol — APPROVED** [review]
Works great, good job!

**Review by b18jacha — APPROVED** [review]
Works

**Pull request merged**
