### PR TITLE
G1 2023 v4 #13613

### PR DESCRIPTION
**Pull request by b21matfi**
I added functionality to the button, created an svg for the SuperState. This can be changed.

### CODE REVIEW

**Comment by b21matfi** [comment]
To be clear, you can place it and change the name, you can not do more then that

**Review by d21matbo — CHANGES_REQUESTED** [review]
image

The image above illustrates that the newly added superstate does not work well when we zoom.

Another issue I found was that the superstate currently uses the same collision detection as the rest of the elements, this makes it impossible to place any element inside the superstate (which I believe we want to be able to do)

**Comment by b21matfi** [comment]
I have fixed so that you can zoom in and out, but the rest should be done in another issue. For example to be able to put other elements inside it

**Review by d21matbo — APPROVED** [review]
The newly added changes fixes the issue with the zoom, great job!

**Pull request merged**
