### PR TITLE
Added functionality to contribution tool clock. Issue#9837

### PR DESCRIPTION
**Pull request by b16oskni**
Updated functionalty to show Hourly activites by weeks instead of day.
Added additional input element.

co-author; @a19isada @a18willi

### CODE REVIEW

**Review by a20chrjo — APPROVED** [review]

**Review by a20chrjo — CHANGES_REQUESTED** [review]
Tested in Chrome and Firefox.

What works:
Selecting different weeks, selecting the same week.

What does not work:
Selecting just one week and you can select the weeks in inverse order i.e. first week "5" and second week "4".

**Review by b19alest — CHANGES_REQUESTED** [review]
Don't know if this is intended or not but if only the first week is selected then the end date don't update and if only second week is selected the start date don't update.

You can also select for example week 4 as first week and week 1 as second. Which will result in nothing showing on the clock.

Would maybe be handy to be able to only chose one week?

**Comment by a19isada** [comment]
If you have selected week 4 and week 3, you will now get a popup that you have made an incorrect selection. You can select one week of you choose the same week on both of them. 

"Don't know if this is intended or not but if only the first week is selected then the end date don't update and if only second week is selected the start date don't update."

This behavior is intented.

**Review by a20chrjo — APPROVED** [review]
It now works as intended

**Review by b19alest — APPROVED** [review]
Works nice! 👍

**Pull request merged**
