### PR TITLE
Arrow on moments in sectioned now always shows Issue#10191

### PR DESCRIPTION
**Pull request by a18willi**
Fixed wierd string that broke arrow functionality.

Co-Authored-By: @b18phika

### CODE REVIEW

**Review by a19samke — CHANGES_REQUESTED** [review]
bild111

It works in some causes but not in all Moments ,check the image on above .

**Review by a18danli — CHANGES_REQUESTED** [review]
Same for me, works in some cases only.

**Review by a19samke — APPROVED** [review]

**Review by a18danli — APPROVED** [review]
Works for me!

**Review by a19samke — APPROVED** [review]
It looks like it works!

**Pull request merged**
