### PR TITLE
Codeviewer#959 markdown headings

### PR DESCRIPTION
**Pull request by b12simsa**
Changed the parser so that it uses the replace() function from javascript with regular expression as parameters, Instead of the previous functions.
This also makes the parser able to handle headings, and whitespace after markdown symbols better. The new function needs to be tested with a lot of different markdown inputs since I have not tested it all.

### CODE REVIEW

**Comment by c13caral** [comment]
This looks really great!! It is ready to merge! :+1:

**Comment by a13alfbe** [comment]
Works for me too. Huge improvement, good job!

**Comment by c13caral** [comment]
#959

**Comment by f12danjo** [comment]
This also fixed issue [#925](http://github.com/HGustavs/LenaSYS/issues/925). Closing that issue.

**Pull request merged**
