### PR TITLE
Delete button resized and repositioned

### PR DESCRIPTION
**Pull request by a20edwth**
Moved the position of the delete buton and made it bigger. #11387

Instructions for testing:
1) Click "Demo-Course"
2) Click "Diagram Dugga"
3) Click or box select any element/s
4) Click cross icon in the right upper corner of the selection box and the elements selected should get deleted

### CODE REVIEW

**Comment by c20emili** [comment]
works when using box select and on lines but not on elements when pressing outside the elements selection box.

**Comment by a20edwth** [comment]
Made new commit that makes it possible to delete single elements. Same testing instructions applies.

**Comment by a20gabpa** [comment]
Test failed. It works when only using the pointer tool to click on the delete button. However when using the box selection tool to select a single element, and then clicking the delete button (X), does not work. If I however switch back to the pointer mode with the element already selected (with box selection) it works. It also work when multiple elements are selected and on single lines using box selection. 

image

Works to click on X:

image


Does not work to click on X:

image

**Comment by a20edwth** [comment]
Fixed the problem above

**Comment by a20samul** [comment]
Tested by pressing delete on single and multiple elements both using the pointer and the box selection tool which lead to element/s and line/s deleteing. Delete button is resized and repositioned. Functionality works as intended, test passed.

**Comment by b20thelo** [comment]
Wait with pull request as issue #11396 might include this solution too. In case it does this pull request will be closed.

**Pull request merged**
