### PR TITLE
G3 2024 v2 #14412

### PR DESCRIPTION
**Pull request by a22diako**
Lista på fungerande popups esc efter ändringarna:
-Log out popup, course list
-Log out popup, inside course
-Course list, inställningar popup
-inuti kurserna, 'load dugga' esc

### CODE REVIEW

**Review by a22karja — COMMENTED** [review]
everything in the issue is resolved, The only pop up that dosen't close on pressing escape is hide/show (ghost/eye button) item in the courses

**Review by a22danwe — CHANGES_REQUESTED** [review]
the issue is mostly resolved, there are two popups that im unable to close using "esc". these popups occur when you hide marked items (ghost button) and show hidden items (eye button). 

image

**Review by a22karja — APPROVED** [review]
Every thing looks good. Good job

**Review by a22danwe — APPROVED** [review]
perfecto!

**Comment by a22willi** [comment]
This is set to merge into master, due to the limited time, I will close this and create a new PR to our weekly branch.

**Pull request closed without merging**
