### PR TITLE
Fixed: #9787, states now save.

### PR DESCRIPTION
**Pull request by a19hammi**
Implemented state saving for changes made to the diagram. This will pave the path for undo/redo and a new form of saving diagram files. I need rigorous testing for this one so would love more than one reviewer to perform thorough testing!

### CODE REVIEW

**Comment by a19hammi** [comment]
Now works (AGAIN)

**Comment by a19hammi** [comment]
Requesting review @a15nikho

**Comment by a19hammi** [comment]
Spotted new problem with storing attribute after merge.

**Review by a19karal — APPROVED** [review]
Funkar som det ska :)

**Pull request merged**
