### PR TITLE
#6004

### PR DESCRIPTION
**Pull request by a17oscno**
Removed the file and everything should work fine without it due to it never being used.

### CODE REVIEW

**Comment by a17oscno** [comment]
https://a17oscno.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732

Use this for testing

**Comment by a17ludca** [comment]
remove row 575-721 and then mark as resolved

**Comment by a17pongo** [comment]
has this been tested again after the new changes?

**Comment by c17johha** [comment]
#6004

**Comment by a17ludca** [comment]
This seems to be a pull request that still includes the duplicate code inside sortableTable.js, other than that this removal of a file is fine.

**Comment by a17pongo** [comment]
Closing this branch and I will remove the file, preventing duplicated code and old buggs being introduced again

**Pull request closed without merging**
