### PR TITLE
Time intervall added #11259

### PR DESCRIPTION
**Pull request by b20matad**
Sets a timeout which doesn't allow zoom events to trigger more than once every 75 ms. To slow down zoom on a touchpad.

### CODE REVIEW

**Comment by c20emili** [comment]
Tested the zoom with my computer trackpad and did not notice any difference in zoom speed. Did not notice any errors in the code.

**Comment by a19meram** [comment]
used my computer and tested trackpack of zooming effect. Can't see any diffrent between the local version and server, the semantical version of the code have no errors

**Comment by b19karhj** [comment]
Based on the test results the issue need to be corrected.

**Comment by b19karhj** [comment]
The test turned out to be incorrect. The solution works and has now passed the test.

**Comment by b19karhj** [comment]
Merge complete.

**Pull request merged**
