### PR TITLE
#5903 sortabletable null error

### PR DESCRIPTION
**Pull request by a17adasy**
Commented out a line that caused error cause it tried to get an ID of an element that was commented out above in the code.

This may cause another error that has not yet been detected.

### CODE REVIEW

**Comment by c17johha** [comment]
#5635

**Comment by c17johha** [comment]
#5903

**Comment by a17alian** [comment]
Please provide a link for testing

**Comment by a17adasy** [comment]
https://a17adasy.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732

Here is the link for testing, but somehow the old else issue has crawled in.

**Comment by a17pongo** [comment]
https://a17pongo.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732

use this link for testing.
Code is correct on branch

**Comment by a17alian** [comment]
Code tested and working - no error appears in console

**Pull request merged**
