### PR TITLE
G1 2021 #10361

### PR DESCRIPTION
**Pull request by a19kevkh**
Do not prompt for a password when refreshing the page for uploading a file.

### CODE REVIEW

**Comment by a19frebo** [comment]
Added a SESSION variable that is set to '1' when we upload and resets to '0' after.

**Review by e15marol — CHANGES_REQUESTED** [review]
When uploading a file and you hit the refresh button, you're prompted a password.

**Review by b18jacha — CHANGES_REQUESTED** [review]
From what we can see, after you have uploaded a file and refresh the page, it will prompt a password request

**Comment by a19frebo** [comment]
The hasUploaded variable is now reset when the dugga is saved into the database

**Review by e15marol — APPROVED** [review]
The fixes solved the problem, good job! Works now.

**Review by b18jacha — APPROVED** [review]
**Very good**

> Works as intended

**Pull request merged**
