### PR TITLE
Add checkboxes to diagram menu - Fix for issue #5694

### PR DESCRIPTION
**Pull request by c17matjo**
image
The checkboxes are not specified in the html document but are instead added to the page from javascript in a setCheckbox method. This can be called on any element that needs a checkbox element.

### CODE REVIEW

**Comment by a17jacsv** [comment]
This issue-branch is from the old branch and should be rewritten in a new issue-branch from our updated gruppA2019W16-branch. Please fix it.

**Comment by c17matjo** [comment]
The branch was rebased onto the gruppA2019W16 branch using the git-rebase command so deleting it and creating a new one shouldn't be necessary.

**Comment by a17jacsv** [comment]
Ok, that should work.

**Comment by a17jacsv** [comment]
It works as expected. There were some conflicts but they are now solved. Good job!

**Pull request merged**
