### PR TITLE
Fixing buggs with github repo button 

### PR DESCRIPTION
**Pull request by a22karja**
The timer no longer starts without a Github repo link

If the string dosent contain certain elements that all github links have you cant save them

WARNING TO TESTER:
If you get a red toast warning when pressing the repo button you have to enter a github token on that course. You do this here.
image

It has to be a valid github token not just random text

### CODE REVIEW

**Review by a18chrkr — CHANGES_REQUESTED** [review]
Looks good and the implementation works. The 'github.com' part of the link is case sensetive though, which will be no problem if the user copy the link (which will probably be most cases) but this _could_ be considered, but is by no means necessary to change.

Other than that there is a few inconsistencies to spaces before curly brackets and also some parameters are declared with space before and after '=' while some are not.

Below is a screenshot of some examples:

whiteSpaceForCurlies

Double check the code and make sure everything is consistent - then this is an ez approve!

**Review by a18chrkr — CHANGES_REQUESTED** [review]
Still a couple variable declarations that e.g. look like this "status=true". Please include space between '='. Also change 'var' to 'let' for declarations.

**Review by a18chrkr — APPROVED** [review]
Changes look good! Seal of Approval! 🐋

**Comment by d22mikwe** [comment]
LGTM!

**Pull request merged**
