### PR TITLE
fix for issue #6765 - reverting css changes after weekly merge

### LINKED ISSUE #6765: Variables in style.css are not used
Referencing #5931 

Variables for colours in style.css have been created, but they are not used, which they should.

### PR DESCRIPTION
**Pull request by a17pongo**
Finished reverting missing CSS changes that occured after weakly merge.
Might not be 100% and have probably missed something, leaders should discuss the best course of action to implement this fix between groups.
Fixes #6765

### CODE REVIEW

**Comment by b17nicsv** [comment]
This pull request shouldn't touch anything else than colors. Won't merge it unless it only change set color variables.

**Comment by b17nicsv** [comment]
For testing: https://b17nicsv.gruppb.webug.his.se:20002/DuggaSys/courseed.php

**Comment by a17pongo** [comment]
added fix for lightbox

**Comment by a17amama** [comment]
Approved

**Pull request merged**
