### PR TITLE
Codeviewer: Fixed bug where reset wouldn't work on first maximize

### PR DESCRIPTION
**Pull request by a17robda**
Fix for #7198

### CODE REVIEW

**Comment by a17robda** [comment]
Interesting, which version of LenaSYS and browser are you using?

**Comment by a17andby** [comment]
> Interesting, which version of LenaSYS and browser are you using?

Branch: GruppC2019W21_7198
Browser: Brave (Chromium)

**Comment by a17robda** [comment]
I see, it seems like it is an issue with some templates only. I will look into this.

**Comment by a17robda** [comment]
Since there is a new branch for this week I will close this and make a new PR.

**Pull request closed without merging**
