### PR TITLE
G1 W16 2021 #10167

### PR DESCRIPTION
**Pull request by b19ponka**

### CODE REVIEW

**Comment by a13zanal** [comment]
Added courseid to the 'refresh' URL.
Removed a body tag and everything inside it. also found and deleted a lonely closing html tag

**Comment by b19ponka** [comment]
When uploading, the refresh URL was not complete. It is now corrected

**Review by a19rebsa — APPROVED** [review]
It works fine!

**Review by a18osken — APPROVED** [review]
good job for solving this tirefire

**Pull request merged**
