### PR TITLE
GruppB2019 w18 #6256

### PR DESCRIPTION
**Pull request by a17ludca**
Quick adjustment of the dropdown-containers

### CODE REVIEW

**Comment by b17nicsv** [comment]
The popup still starts at the navbar. Additionally, why doesn't the funnel or the sort function work in the Access tab if they are visible? The popup still needs correction and I would suggest (perhaps making another issue) to remove the funnel and sort icons from Access since they don't work and there's already a way to sort the different columns.

**Comment by a17pongo** [comment]
the funnel and sort got broken during one of our first merges, im gonna check with henrik on what he thinks the current workflow should be.
@b17nicsv if there are changes that should be made on the current issue then please as a reviewer mark the pull requests as "changes requested"

**Comment by a17pongo** [comment]
What is the status on this?
also, hiwah has made a pull request in this issue that supposidly fixes it.. is it ok to close this pull request?

**Comment by b17nicsv** [comment]
Hiwahs pull request solved the problem. It is okay to close this pull request.

**Pull request closed without merging**
