### PR TITLE
G1 2023 v4 #13591

### PR DESCRIPTION
**Pull request by d21matbo**
It is now possible to change the line type using the options panel on the right.

The previous bahaviour (line type based on distance) is kept while placing the element and once it is placed the type can only be changed by using the options panel.

Options-panel when a line is selected now has a new dropdown for line type

### CODE REVIEW

**Review by a21aldsa — APPROVED** [review]
Works

**Review by a21aldsa — CHANGES_REQUESTED** [review]
You cant edit lines, for example, change from strait to segmented.

**Comment by d21matbo** [comment]
The newest commit should solve the problem that got merged from stable

**Review by a21aldsa — APPROVED** [review]

**Comment by a21aldsa** [comment]
Works fine now

**Pull request merged**
