### PR TITLE
Potential fix: ctrl-z bug

### PR DESCRIPTION
**Pull request by a19matma**
ctrl-z should work as intended now.

Co-Authored-By: Hamlet Magnusson Millqvist <81571224+a19hammi@users.noreply.github.com>

### CODE REVIEW

**Comment by a19matma** [comment]
Also purged some console.logs that were left behind

**Comment by a19hammi** [comment]
Patch for pull-request #11144 
Need review from original authors. Usually I should not participate in making code but this one is an exception.

**Review by a18osken — APPROVED** [review]
I am not aware of what the initial bug entailed, but ctrl-z seems to work as intended now.

**Comment by a19chrel** [comment]
> 
> 
> I am not aware of what the initial bug entailed, but ctrl-z seems to work as intended now.

The problem was that when an stepback (CTRL + Z) was executed, you moved multiple steps in the history. Even if you only should move one.

**Comment by a19chrel** [comment]
There is one problem still, the load now gets in the wrong place, because the scrubHistory has some changes, this can easly get fixed by removing the `+ 1 ` on this line. This was an mistake by me that should get removed. I suggest that we do that in the patch for the solution.
https://github.com/HGustavs/LenaSYS/blob/daae9a670a035c7873481f36619f2b66efe57098/DuggaSys/diagram.js#L4909

**Comment by a19chrel** [comment]
Also i suggest we move the replay-calculations from save() in stateMachine to toggleReplay(), because the replay was made before it was possible to import / export. And now does the values for replay mode do not update if you dont make an change.

https://github.com/HGustavs/LenaSYS/blob/4591e75e2176eaf989341de0674894fb9af39dab/DuggaSys/diagram.js#L485-L495

**Review by a19chrel — APPROVED** [review]
LGTM, seems to have done the trick.

**Pull request merged**
