### PR TITLE
Code view#872 markdown headings

### PR DESCRIPTION
**Pull request by f12danjo**
Implemented headings functionality with markdown.

### CODE REVIEW

**Comment by c13caral** [comment]
There was just one problem. when you added Three stars (***) it became like h1 e. g. 

*** Test

Is the same as

<h1>Test<h1t>

**Comment by a13alfbe** [comment]
The only thing i could find was that the headers
Example:
\# ## Header 1 Should be:
# ## Header 1
But instead it is like this:

\# 
## Header 1

**Comment by f12danjo** [comment]
It is true that if you input "# " (any number of #) followed by more "# " on the same row, you get several headings, each on their own row.

The question is: Is this reason enough to not merge this branch?

The code doesn't break anything and the headers works if you write correct markdown syntax :)

**Comment by b12simsa** [comment]
Maybe merge and at the same time create a new issue about headers not being parsed correctly in all circumstances?

**Comment by c13caral** [comment]
There is some problems but we gonna create new issue for them  #959 and merge this pull request.
Because the issue is solved but one bug was found

**Pull request merged**
