### PR TITLE
G2 2024 v5 issue#15387

### PR DESCRIPTION
**Pull request by b21isabe**
retrieveCodeviewerService_ms.php has now been implemented with its microservices.

I used curl commands to test because the website would refresh when calling a service, making the output not show in the network tab.

editCodeExample
```
curl -X POST -d "opt=EDITEXAMPLE&courseid=1885&cvers=1337&exampleid=7000&examplename=UNK&sectionname=UNK&addedWords=foo,bar&log_uuid=TmX2JZ8vpNIWHYh
" http://localhost/LenaSYS/DuggaSys/microservices/codeviewerService/editCodeExample_ms.php
```

editContentOfExample
```
curl -X POST -d "opt=EDITCONTENT&courseid=1885&cvers=1337&exampleid=7000&boxtitle=Testingbox&boxcontent=Code&wordlist=3&filename=JS-TEST1.js&fontsize=10&boxid=1
&log_uuid=TmX2JZ8vpNIWHYh
" http://localhost/LenaSYS/DuggaSys/microservices/codeviewerService/editContentOfExample_ms.php
```

editBoxTitle
This wouldn't work with the curl commands  at first since authentication fails, to test I just commented out the if statement with the “checklogin” on line 33
```
curl -X POST -d "opt=EDITTITLE&courseid=1885&cvers=1337&exampleid=7000&boxtitle=testbox1&boxid=1
&log_uuid=TmX2JZ8vpNIWHYh
" http://localhost/LenaSYS/DuggaSys/microservices/codeviewerService/editBoxTitle_ms.php
```
deleteCodeExample
```
curl -X POST -d "opt=DELEXAMPLE&exampleid=7000&boxid=1
" http://localhost/LenaSYS/DuggaSys/microservices/codeviewerService/deleteCodeExample_ms.php
```

### CODE REVIEW

**Comment by a22marca** [comment]
Should add a switch to handle all the opts from codeviewerService in dugga.js like so:
```
	}else if(kind=="CODEVIEW"){
		switch (opt){
			case "DELEXAMPLE":
				$.ajax({
					//url: "codeviewerService.php",
					url : "../DuggaSys/microservices/codeviewerService/deleteCodeExample_ms.php",
					type: "POST",
					data: "opt="+opt+para,
					dataType: "json",
					success: returned,
					error: returnedError
				});
				break;
			default:
				$.ajax({
					url: "codeviewerService.php",
					type: "POST",
					data: "opt="+opt+para,
					dataType: "json",
					success: returned,
					error: returnedError
				});
		}
	}else if(kind=="BOXCONTENT"){
		switch (opt){
			case "EDITCONTENT":
				$.ajax({
					//url: "codeviewerService.php",
					url : "../DuggaSys/microservices/codeviewerService/editContentOfExample_ms.php",
					type: "POST",
					data: "opt="+opt+para,
					dataType: "json",
					success: returned
				});
				break;
			default:
				$.ajax({
					url: "codeviewerService.php",
					//url : "../DuggaSys/microservices/codeviewerService/editBoxTitle_ms.php",
					type: "POST",
					data: "opt="+opt+para,
					dataType: "json",
					success: returned
				});
		}
	}else if(kind=="BOXTITLE"){
		switch (opt){
			case "EDITTITLE":
				$.ajax({
					//url: "codeviewerService.php",
					url: "../DuggaSys/microservices/codeviewerService/editBoxTitle_ms.php",
					type: "POST",
					data: "opt="+opt+para,
					dataType: "json",
					success: returnedTitle
				});
				break;
			default:
				$.ajax({
					url: "codeviewerService.php",
					//url: "../DuggaSys/microservices/codeviewerService/editBoxTitle_ms.php",
					type: "POST",
					data: "opt="+opt+para,
					dataType: "json",
					success: returnedTitle
				});
		}

```
(note that the merged branch should still use codeviewerservice.php)

**Review by a22marca — CHANGES_REQUESTED** [review]
You should add a switch case to dugga.js like the one I commented in the PR.
The url's should still direct to codeviewerservice.php when merged.

We should also try to test the microservice's integration when adding the use of the retrieve service, not curl commands. This is to make sure that they really are working with the rest of the website.

**Comment by b21isabe** [comment]
I have tested changing dugga.js to only use the microservices like this:
```
	}else if(kind=="CODEVIEW"){
		switch (opt){
			case "EDITEXAMPLE":
				$.ajax({
					//url: "codeviewerService.php",
					url: "../DuggaSys/microservices/codeviewerService/editCodeExample_ms.php",
					type: "POST",
					data: "opt="+opt+para,
					dataType: "json",
					success: returned,
					error: returnedError
				});
				break;
			case "DELEXAMPLE":
				$.ajax({
					//url: "codeviewerService.php",
					url : "../DuggaSys/microservices/codeviewerService/deleteCodeExample_ms.php",
					type: "POST",
					data: "opt="+opt+para,
					dataType: "json",
					success: returned,
					error: returnedError
				});
				break;
		}
	}else if(kind=="BOXCONTENT"){
		switch (opt){
			case "EDITCONTENT":
				$.ajax({
					//url: "codeviewerService.php",
					url : "../DuggaSys/microservices/codeviewerService/editContentOfExample_ms.php",
					type: "POST",
					data: "opt="+opt+para,
					dataType: "json",
					success: returned
				});
				break;
			}
	}else if(kind=="BOXTITLE"){
		switch (opt){
			case "EDITTITLE":
				$.ajax({
					//url: "codeviewerService.php",
					url: "../DuggaSys/microservices/codeviewerService/editBoxTitle_ms.php",
					type: "POST",
					data: "opt="+opt+para,
					dataType: "json",
					success: returnedTitle
				});
				break;
		}
```
I discovered a few bugs that I have fixed and to me it now looks like that the microservices has the same functionality as the monoservice. I have left dugga.js unchanged, should this be changed in any way?

**Comment by a22marca** [comment]
> I discovered a few bugs that I have fixed and to me it now looks like that the microservices has the same functionality as the monoservice. I have left dugga.js unchanged, should this be changed in any way?

I think the `switch` should be added to dugga.js, but the url's can direct to codeviewerService.php in the version that gets merged.

I will test the integration of the microservices and hopefully this can be merged after.

**Review by a22marca — CHANGES_REQUESTED** [review]
These microservices are working:
- editCodeExample
- editContentOfExample
- editBoxTitle

I'm not able to fully delete a code example using deleteCodeExample. It isn't able to find the codexample for some reason. This isn't necessarily a problem with the microservice itself.
As I mentioned in my previous comment we should also add the switch-case to dugga.js. Other than these two things everything looks good.

**Comment by b21isabe** [comment]
I fixed the error with examplename, sectionname and runlink being updated with placeholder names when opening a code-example. I have also added the switch-cases in dugga.js. 

deleteCodeExample is deleting the codeExamples successfully for me but an alert is sent that the exampleId couldn't be found, possibly because the retrieve is trying to gather info on a deleted code example after the example has been deleted?

**Review by a22marca — APPROVED** [review]
deleteCodeExample works now, but the javascript/frontend is not working like it should. The actual database entry for the code example is being removed though. So this issue is solved.

Good work, merging this.

**Pull request merged**
