### PR TITLE
Fixed default colors for pasted elements

### PR DESCRIPTION
**Pull request by a19nikbo**
Elements are no longer completely black when pasted

### CODE REVIEW

**Comment by a19steis** [comment]
Default colour now works correctly when copy pasting. But dont we want the copied element to retain its colour when it is copied?

**Comment by a19nikbo** [comment]
> Default colour now works correctly when copy pasting. But dont we want the copied element to retain its colour when it is copied?

True, you can make a change request and I'll fix it ^^

**Review by a19steis — CHANGES_REQUESTED** [review]
Awaiting fix.

**Comment by a19nikbo** [comment]
Changes made

**Pull request merged**
