### PR TITLE
Made it possible to submit and load diagram dugga

### PR DESCRIPTION
**Pull request by a18osken**
It is now possible to save and load diagrams. Now when the user makes any change to the diagram iframe it is possible to save the assignment to the database just as any other file submission. We skipped the inclusion of an upload field since it is strictly not necessary when we create the file ourselves from the state of the diagram.

It currently only saves the JSON file.

### CODE REVIEW

**Comment by a18osken** [comment]
Keep in mind that while testing you need to update the database

**Review by a13zanal — APPROVED** [review]
Looks like everything works as described 👍🏻 Well done!

**Review by a19rebsa — APPROVED** [review]
It works as described, good job 👍

**Review by a19matma — APPROVED** [review]
Saving and loading seems to work as intended. Good job!

**Comment by a19hammi** [comment]
Would love if #11153 was reviewed and merged before this one is. @a19chrel @a18osken

**Pull request merged**
