### PR TITLE
Change the cursor when drawing lines #6729 

### PR DESCRIPTION
**Pull request by a17jacsv**
Change the cursor to a pen when drawing lines.

Issue: #6729

### CODE REVIEW

**Comment by a17jacsv** [comment]
I don't agree with you as you can only create lines when clicked-and-dragged on an entity. If the cursor is immediately changed to a pen it would cause unclarity. This is the best solution in my opinion.

**Comment by a17jacsv** [comment]
> @a17celal: I don't agree with you as you can only create lines when clicked-and-dragged on an entity. If the cursor is immediately changed to a pen it would cause unclarity. This is the best solution in my opinion.

@a17vikab & @a14oscna your view on this?

**Comment by a14oscna** [comment]
We have decided that the cursor should be standard pointer when draw line is the selected mode. No change on hover or during the drawing of a line, just standard pointer as it currently is when you hover over nothing. The change in code would be to ignore the current cursor changes when draw line is selected in the toolbar, rather than adding any new functionality.

**Comment by a17jacsv** [comment]
Created a new issue of this updated issue: #6853 So I consider this PR closed...

**Comment by a17celal** [comment]
@a17vikab @a14oscna Is this PR closed or should I approve?

**Comment by a17vikab** [comment]
This PR will be closed and be continued in #6853.

**Pull request closed without merging**
