### PR TITLE
Update the testdata #11110

### PR DESCRIPTION
**Pull request by a19frebo**
Updated all the testdata that is inserted into the userAnswer table. Every row now has a value in the timesSubmitted and timesAccessed columns.

### CODE REVIEW

**Comment by a19frebo** [comment]
Also fixed all the "broken" entries in the table so they should work correctly now when entering the dugga through the hash.

**Comment by a19kevkh** [comment]
To test, simply truncate the Useranswer table and then run the inserts that are in the testdata.sql file in the lenasys/install/SQL folder. Then go into the edit student result page and check so that they all have the correct dugga name and the values are correct.

**Review by a19arvka — APPROVED** [review]
Works, all tables in resulted have a value and that value matches the one in my database after I truncate and execute testdata.sql

**Review by a13zanal — APPROVED** [review]
Looks good 👍🏻

**Pull request merged**
