### PR TITLE
Ds17 #1019 - adding "Files" page fix

### PR DESCRIPTION
**Pull request by a13chrju**
with this code the buttons for adding files are displayed even if there is no file in the database under the course.
Javascript and css links are fixed.
Directories were created for where global and local files will be stored in.
couldn't upload files before, now you can. All global files will show up on all courses which is why I needed an attribute "isGlobal" which is either 0 or 1. if it is a global file the attribute is equal to 1.

### CODE REVIEW

**Comment by a13chrju** [comment]
The attribute I need for this pull request was added in this one from Kári: https://github.com/HGustavs/LenaSYS/pull/1042

**Comment by a13chrju** [comment]
https://github.com/HGustavs/LenaSYS/issues/1019#issuecomment-95246353

**Comment by a13denli** [comment]
Remove deadcode(example you have some outcomment code in DuggaSys/filereceive.php)

**Comment by a13chrju** [comment]
I removed some dead code :+1:

**Comment by a13denli** [comment]
Good (Y)

**Pull request merged**
