### PR TITLE
G1 2021 w17 #10102 v3

### PR DESCRIPTION
**Pull request by e15marol**
The variant now loads and the function to set the time to live now works, for each time the get time expire function is loaded, it checks if the variants TTL has expired or not. When its expired, it removes the key and we get a new variant.

### CODE REVIEW

**Comment by b18jacha** [comment]
To test if assigned variant resets, change the value in the setExpireTime function on line 1026. (showduggaservice)

**Review by a19arvka — APPROVED** [review]
Works as intended. Nice solution. 
Will cause merge conflicts in dugga.js.
Please comment code in the future.

**Review by a18osken — CHANGES_REQUESTED** [review]
Currently variant values gets set to 0 which means the assignment will not save correctly and redirection will fail

**Review by a19arvka — APPROVED** [review]
Works!

**Review by a18osken — APPROVED** [review]
This works well, nice job!

**Pull request merged**
