### PR TITLE
Created tests for resultedservice.php in md

### PR DESCRIPTION
**Pull request by c21axepe**
Created a md file that contains all tests for resultedservice.php

### CODE REVIEW

**Comment by b21antbr** [comment]
I am a co-author to this issue.

**Review by a21oscgu — CHANGES_REQUESTED** [review]
- row 81 forgot $preValuesQuiz[10]?
- row 91, 92, 134, 137, 140, 146, 232, 235 forgot to end with ";"
- row 235, did you mean: "ORDER BY cid DESC LIMIT 1"?

**Review by a21oscgu — APPROVED** [review]
Looks good!

**Comment by d21erisu** [comment]
great

**Pull request merged**
