### PR TITLE
Changed the position divider

### PR DESCRIPTION
**Pull request by a19danla**
Changed the position divider to a lower value and removed the constant to make it scale better for longer lists.

Should work fine for 70+ items.

There is still a "bugg" where this function sometimes struggle when there are alot of newly added items. It fixes itself if you leave the site and rejoins later.

Co-Authored-By: b19wilfo <62884368+b19wilfo@users.noreply.github.com>

### CODE REVIEW

**Comment by a19danla** [comment]
Would be nice to have more testers to see how it behaves for them. Seems to be inconsistent for us.

**Review by a19klafr — CHANGES_REQUESTED** [review]
New items currently gets added somewhere a little bit below the showing screen, so when new item is added you don't see it until you scroll down. Would be nice if this gets changed so you see the added item right away.

**Comment by a19danla** [comment]
Thats good to know it acts like that for you as well. We currently have some problem where it sometimes act how its supposed to and sometimes not. We're currently looking into this but wanted more people to test this.

**Review by a19kimgr — CHANGES_REQUESTED** [review]
The new items are added outside the screen and its hard to see that they are added

**Comment by a19klafr** [comment]
Might want to look at where the pull request is going.. currently saying master instead of G2-2021-W18

**Pull request closed without merging**
