### PR TITLE
G1 2023 v4 #13584

### PR DESCRIPTION
**Pull request by b21matfi**
the element popout is now alligned even if the screen size is bigger o smaller

### CODE REVIEW

**Comment by b21matfi** [comment]
Do not test this yet, something need to make changes

**Comment by b21oscpe** [comment]
Need another review after big merge-conflict

**Review by b21eriho — CHANGES_REQUESTED** [review]
image
This branch is severely broken. Though on the bright side, the popout is still aligned regardless of window size 
image

**Comment by b21oscpe** [comment]
That's great

**Comment by b21matfi** [comment]
Branch should be fixed now please review again

**Review by b21eriho — APPROVED** [review]
Looks good, unbroken and still aligned

**Pull request merged**
