### PR TITLE
Fix for issue with aligning locked objects #6151

### PR DESCRIPTION
**Pull request by a16jenja**
Fix for issue #6151 

The alignment should not be a bit off anymore. It should instantly align correctly when pressing the vertical and horizontal alignment button with objects locked now. Before you had to press the button multiple times for it to align properly.

### CODE REVIEW

**Comment by a16jenja** [comment]
I kinda agree with you, but it's hard to decide what the lock on an object should actually do. Since it can be beneficial to be able to align every object even if they are locked and avoid the hassle of unlocking every object when you want to align them. But it can also be the opposite of course, and be an annoying function.

I am not sure about which direction we should go, regarding if an object that is locked should move when aligned but not be moved by dragging or not be able to move at all. I would like to get @a17drama and @a17jacsv opinion on this. And I will make the changes accordingly.

**Comment by a17drama** [comment]
Locking means that all possibilities to edit the entity are gone. When it's locked it's locked.

**Comment by a17jacsv** [comment]
> Locking means that all possibilities to edit the entity are gone. When it's locked it's locked.
I agree with @a17drama. Aligning with locked entities included, the locked entities should be excluded when aligning items.

**Comment by a16jenja** [comment]
Thanks for the clarification, I will get right on it.

**Comment by a16jenja** [comment]
Ignore the code added before since it only makes it so the lock will temporarily unlock and the locked object will align with the rest of them, but as previously stated we don't want the lock to move at all when aligning.

**Comment by a17alfcl** [comment]
Creating new branch after merge

**Pull request closed without merging**
