### PR TITLE
"Delete marked items" button now hides marked items from students instead. Issue#10280

### PR DESCRIPTION
**Pull request by a18willi**
Can now hide multiple items at the same time using the "-" button.

Co-author: @a19isada

### CODE REVIEW

**Comment by a18willi** [comment]
Mentioned button
Skärmklipp1

**Review by b19alest — CHANGES_REQUESTED** [review]
Seems to work but the popup is missleading as it asks if you want to delete the item.

**Review by a20chrjo — CHANGES_REQUESTED** [review]
The code works. But the pop up that appears, ask for confirmation to delete instead of to hide.

**Review by b19alest — APPROVED** [review]
Perfect!

**Review by a20chrjo — APPROVED** [review]
Tested in Chrome, Edge, Firefox and Opera, in both browser mode and mobile mode.

**Pull request merged**
