### PR TITLE
G3 2024 v6 #15041 is partly fixed as files are fetched and downloaded asynchronously

### PR DESCRIPTION
**Pull request by a22ahmom**
The main problem of this issue is to fetch and download all files and directories from the course URL that is saved in download github repo window asynchronously. However, some parts of this issue have been fixed as files are fetched and downloaded locally asynchronously. The tables gitRepos and fileLink are also populated with relevant data but are incomplete as not all files within directories are fetched properly and downloaded. So the main thing to try to fix is that directories should be fetched and downloaded associated with the URL provided. Right now this is not working. However, it all comes down to the bfs function. Initially, this function used a synchronous approach as requests for files and directories were made synchronously, meaning one at a time. This resulted in longer waiting times. 

What made this function synchronous was the file_get_contents( ) function. However, to make the function asynchronous cURL was used. Specifically curl_multi_init( ) and some other functions related to it. View the source code for a detailed description. Essentially some modifications are needed in the bfs function to also fetch and download directories. View the images below to understand properly the functionality of the bfs at the moment.

The path where the content is downloaded. C:\xampp\htdocs\LenaSYS\courses\$cid\Github
Screenshot 2024-05-08 154732

DB Browser (SQLite) the gitRepos table
Screenshot 2024-05-08 154848

PhpMyAdmin the fileLink table
Screenshot 2024-05-08 154912

### CODE REVIEW

**Comment by a22ahmom** [comment]
Commit from g3-2024-v5-#15041 https://github.com/HGustavs/LenaSYS/commit/33643d4a5e7ac8bb6820f6e9bf5718497586dfaa

**Comment by a22moamy** [comment]
Directories being fetched and downloaded associated with a provided URL will be fixed in another issue. Developer has asked to split this issue and it will be granted. Judge the work only by what has been fixed.

**Review by a22oscja — CHANGES_REQUESTED** [review]
Immediately I have to deny this based on the fact that it includes changes to 95 files, while I know this is mostly formatting it also changes actual code in places. Especially since its from a commit said to not be relevant to the issue in its comment. **Fix this.**

As for the actual code itself I think you've done a pretty good job, it appears to work the way its supposed to and should serve as a good starting point to making the bfs function asynchronous.

You did however remove the logging functionality of bfs, which i'd prefer you did not. I do not believe that it should cause any issues to simply add the code back in with very minor changes, if it does, resubmit saying it did and I will approve without it.

this is the logging btw:
```
if($data === false || !$data) {
            $curl = curl_init($url);
            curl_setopt($curl, CURLOPT_USERAGENT, 'curl/7.48.0');
            curl_setopt($curl, CURLOPT_HEADER, 0);
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
            $response = json_decode(curl_exec($curl));
            $http_response_code = curl_getinfo($curl, CURLINFO_HTTP_CODE);
            $file = '../../LenaSYS/log/gitErrorLog.txt';
            if(strlen($token)<1)
            {
                setcookie("missingToken", 1, time() + (5), "/");
                $message = "\n" . date("Y-m-d H:i:s",time()) . " - Error: connection failed - Error code: ".$http_response_code." Consider setting a token\n";
            }
            else
            {
                $message = "\n" . date("Y-m-d H:i:s",time()) . " - Error: connection failed - Error code: ".$http_response_code."\n";
            }

            http_response_code($http_response_code);
            error_log($message, 3, $file);
        }
```

**Comment by a22ahmom** [comment]
This PR will be closed to fix the issues raised above. A new PR will be created so the reviewer can check it out.

**Pull request closed without merging**
