### PR TITLE
Cv#1225-4

### PR DESCRIPTION
**Pull request by c12jenek**
#1225 Cleaning some more!

### CODE REVIEW

**Comment by c12jenek** [comment]
Hotdogmenu code will be removed in this merge, if this is still desired by customer ( Henke ) please refrain from merging

**Comment by a13alfbe** [comment]
I will wait with this merge until we here from the customer about the hotdog menu.

**Comment by c12jenek** [comment]
Added the hotdog code back into the branch, added comments on why it's still there but never used

**Comment by f12danjo** [comment]
Nice addition of line number were functions are called. Even if these lines changes in the future (most likely) you will at least have an approximation of where the function is called, which is better than having none.

**Pull request merged**
