### PR TITLE
ctrl + z #14364

### PR DESCRIPTION
**Pull request by a22jacka**
Managed to partially fixed how <kbd>ctrl</kbd> + <kbd>z</kbd> works

What works: 
* resize down
* resize right
* resize up
* resize left

What doesn't work:
* move around

I'm gonna keep working on this but keeping these changes would be nice

### CODE REVIEW

**Comment by a22jacka** [comment]
All the resizes now work correctly. Plan is to make so it only stores once the user finishes resizing since it currently saves every step.
After that I'll look at position undo

**Review by a22cazlu — CHANGES_REQUESTED** [review]
Most of the ctrl + z works, but with ER and UML the resizing dosen't work. se videos for better understanding.
[screen-capture (2).webm](https://github.com/HGustavs/LenaSYS/assets/131054714/e31dc344-51d3-498a-bfd5-1fa39578aab2)
[screen-capture (1).webm](https://github.com/HGustavs/LenaSYS/assets/131054714/9b1e80f6-9832-4097-83e4-177952b1a299)

**Comment by a22jacka** [comment]
Mostly done. Currently known issues are it stores every step when resizing and the UML, IE, and State entities sizes getting messed up, however if this get's merged now I can focus more on them after the weekly merge

**Review by a22cazlu — APPROVED** [review]
what i can see nothing else get destroyed but the same issue is still there. And sometime the ctrl + z don't work until I do something else, then the block kind of disappear. And as you say it make all the jumps back to the size it was before when I have resized an object. I can approve it but it really need some more work.

**Pull request merged**
