### PR TITLE
 Possibility to add name/description to dugga variants #12252 

### PR DESCRIPTION
**Pull request by b19karhj**

### CODE REVIEW

**Comment by a20willa** [comment]
For testing:
1. Go into demo course
2. Edit any file
3. Add a note in the note field
4. Create and or update the dugga
5. Check to see that the note appears in the left column

**Comment by b19karhj** [comment]
Seems that the server had to be updated. It now works

**Comment by a20chrka** [comment]
Test failed. Too many letters in "Note" causes a few problems...
image

I can no longer access variant #52 because the "Note" pushed both the cogwheel and the "delete" button off screen.

**Comment by b19karhj** [comment]
Now the note colum has a max width.  
bild

**Pull request merged**
