### PR TITLE
Fixed error with Ctrl+z

### PR DESCRIPTION
**Pull request by a19matma**

### CODE REVIEW

**Review by a19nikbo — CHANGES_REQUESTED** [review]
When deleting all the elements in this order and pressing ctrl + z

changerequestexample

I get this error when moving the cursor

image

**Comment by a19nikbo** [comment]
Also, ctrl + z after having deleted an element while moving it produces this error:

image

**Comment by a19nikbo** [comment]
If you reproduce the bug in the previous comment, pressing ctrl + z while moving an element makes the selection box stay in place

image

And it gives this error

image

**Comment by a19nikbo** [comment]
I'm having difficulty reproducing this error, so I might've been in the main branch when I found the bug.

I do however get this error:

issue_example

The error comes when pressing ctrl + z.

**Comment by a19chrel** [comment]
> 
> 
> When deleting all the elements in this order and pressing ctrl + z
> 
> changerequestexample
> 
> I get this error when moving the cursor
> 
> image

I guess that this was indeed in the main branch, the error that was fixed in the first place was similar.

**Comment by a19chrel** [comment]
> 
> 
> I'm having difficulty reproducing the error in the review, so I might've been in the main branch when I found the bug.
> 
> I do however get this error:
> 
> issue_example
> 
> The error comes when pressing ctrl + z.
This error has now been fixed, also some extra comments was also added.

**Review by a19nikbo — APPROVED** [review]
I can't find any more errors regarding ctrl + z. 
Well done!

**Pull request merged**
