### PR TITLE
G1 2021 #9910

### PR DESCRIPTION
**Pull request by a19kevkh**
Saved assigments are now related to hash. To save without being logged in, see issue #10017.

### CODE REVIEW

**Review by a19simma — APPROVED** [review]
image

When you save an already hashed dugga, password shows as an html object. There should be some explicit message and not this. 

Also, maybe there should be a prompt to login when you save the dugga? Right now you get a hash generated and password so it looks like it worked. But the has is not saved in the database. There should be an error.

@a18osken New issues for this maybe? Unless the login check is going to be removed. But then remove this condition for saving a dugga?

**Review by a19taral — COMMENTED** [review]
The hash is not saved in database (coursekeys) in case if the user is not logged in.

**Review by a19taral — APPROVED** [review]
The hash is not saved in database (coursekeys) in case if the user is not logged in.

**Comment by a19kevkh** [comment]
> The hash is not saved in database (coursekeys) in case if the user is not logged in.

We are working on it on issue #10017.

**Comment by a18osken** [comment]
> image
> 
> When you save an already hashed dugga, password shows as an html object. There should be some explicit error message and not this.
> 
> Also, maybe there should be a prompt to login when you save the dugga? Right now you get a hash generated and password so it looks like it worked. But the has is not saved in the database. There should be an error.
> 
> @a18osken @a19rebsa New issues for this maybe? Unless the login check is going to be removed. But then remove this condition for saving a dugga?

There are issues concerning these shortcomings which should fix the problems found here 🙏

**Review by a19rebsa — APPROVED** [review]
Looks good

**Pull request merged**
