### PR TITLE
G1 2021 W17 #10466

### PR DESCRIPTION
**Pull request by e15marol**
The corresponding variant to the hash URL should now load correctly, when "visiting" a hash, and the saved answer should display correctly. To check this compare the saved answer to the useranswer in the userAnswer inserts, after loading the URL address with the hashes. You could also reset the local storage and save a dugga yourself, and then use the hash and password that is generated to test this issue.

### CODE REVIEW

**Review by a19rebsa — CHANGES_REQUESTED** [review]
Now you do get a variant when local storage is empty while visiting an already submitted assignment/dugga, but you do get different variants. If I submit an assignment/dugga e.g. "biträkningsdugga" with number 25 and then empty my local storage and then go to the hash url, I get number 2. This should be fixed

**Review by a19frebo — COMMENTED** [review]
I have the same issue, after saving an assignment and then deleting the local storage. If you then go to the hash url you have a chance to get a different variant

**Review by a19frebo — CHANGES_REQUESTED** [review]
When you get a variant for a dugga in localstorage and enter an assignment stored in database with a different variant, the variant from local storage is loaded instead of the variant from the database.

**Comment by a19rebsa** [comment]
This needs to be based of the new week 18 branch, so closing this pull request in the mean time.

**Pull request closed without merging**
