### PR TITLE
G1 2021 w19 #10500

### PR DESCRIPTION
**Pull request by a17alfja**

### CODE REVIEW

**Comment by a17alfja** [comment]
link does not work atm, can be fixed later

**Review by a18osken — COMMENTED** [review]
Just on a side note, it seems the solution reverts to the old table if you run an older php version, 7.4.16 in my case, but works fine on php version 8.0.3

However this is likely to be a local issue as I seem to be having a lot of them

**Review by a18osken — APPROVED** [review]
Works, nicely done!

**Review by B18mohah — APPROVED** [review]
Good job!

**Comment by b19ponka** [comment]
I would prefer if the old code was commented out, rather than deleted, for now

**Pull request merged**
