### PR TITLE
G4 2020 W17 issue#7765

### LINKED ISSUE #7765: Download all files as zip
We want the ability for teachers/administrators to download all files from a course.

A download all files menu option in the top toolbar.

### PR DESCRIPTION
**Pull request by b18phibe**
You are now able to download files that are version independent to you course as well as the files to the specific version of the course you are in at the moment.  the already uploaded files are in non of those categories and will not be downloaded as of right now. But all new files will be uploaded appropriately. closes #7765

### CODE REVIEW

**Comment by a18kaswi** [comment]
Note to self: remember to make changes to readme and etc how to enable zip on php if this pr passes testing.

**Comment by a17robhe** [comment]
@b18phibe If more documentation is needed in the code please provide this, see @b18mikfr 's comment

**Comment by b18phibe** [comment]
> Works and follows the code standard. Some more comments on what happens on ELSE while processing IF satements would be nice otherwise, it works.
@b18mikfr 
What do you mean with " Some more comments on what happens on ELSE while processing IF satements"?

**Comment by a17robhe** [comment]
@b18mikfr Can you check that the new comments

**Pull request merged**
