### PR TITLE
Unable to group-select sequence objects #14026

### PR DESCRIPTION
**Pull request by a19clasv**
The title is misleading, you can group-select sequence objects. The problem is that resizing an element vertically changes the y position detected when group-selecting and makes it so that the visual location doesn't match up to the actual location needed to include in Box Selection. 

I've fixed that by storing the height when first resizing an element and changing the compared y position based on the difference with their current height. You still need the Box Selection box to be a bit above them, but that has nothing to do with resizing and was both there before I started and was possibly intended.

### CODE REVIEW

**Comment by b21phiro** [comment]
But does it solve the main issue objective in that you can group these elements?

**Comment by a19clasv** [comment]
You can group sequence objects.

**Comment by a19clasv** [comment]
The box just have to be a bit above them if Box Selection is used to group them.

**Comment by a19clasv** [comment]
I'll change that then.

**Comment by b21phiro** [comment]
I tried by pulling from the branch and it seems to work okay. I'd allow it, but it's up to the tester.

**Comment by d21matbo** [comment]
From what I can tell, it still behaves very strange. Testing with a `sequence-lifeline` the required offset above the elements increases as the element is expanded vertically downwards.

image

The image shows that the first `sequence-lifeline` is inside the selection (since it has lost its name), while the second `sequence-lifeline` is not inside the selection

**Review by d21matbo — CHANGES_REQUESTED** [review]
In addition to the changes made to solve this issue not working, there is also some changes made to other parts of the system that I really do not see the need of, function `drawElement` to be specific.

Newly added `var` declarations and `console.log()` is also present.

**Comment by a19clasv** [comment]
preResizeHeight might need to be a var, but I'll change the rest

**Comment by a19clasv** [comment]
The console log isn't mine.

**Comment by d21matbo** [comment]
Some changes made now allows the selection to happen on the resized `sequence-lifeline` but not the original one.
image

**Comment by b21eriho** [comment]
While changes may not have been made by you but by the person you inherited the branch from please still attempt to resolve the faults. No matter who made them we do not want to merge them into the system. 

Though as said if you will not have the time to fix them the changes will be accepted since today is the final day

**Review by d21matbo — APPROVED** [review]
The group selection now works well, the gap required above is small enough such that it fits with the rest of the system. Very good job!

**Pull request merged**
