### PR TITLE
Have made it possible to for teatchers to download there files to a zip

### PR DESCRIPTION
**Pull request by b18phibe**
Now teachers can download there files for the current version of to course to a single zip-file complete with the version independent files. @a18jonpe  ISSUE #7765

### CODE REVIEW

**Comment by a18petha** [comment]
Cannot reproduce the test, I found the download icon for each course but it seemingly does nothing. The test has been carried out on chrome and firefox, from what I can tell none of the code that has been implemented has been executed once interacting with the download icon.

Following code is what I assume to errorhandlers, but I never interacted with these html messages.
image

**Comment by a18kaswi** [comment]
@b18phibe @a18jonpe take notes of what should be fixed, and close this PR. Put in a new one when changes are made based PR-comments.

**Comment by b18phibe** [comment]
@HGustavs Do you have any idea why the server gets a html 500 error and does not execute the download.php file when it works on a local environment?

**Comment by a18kaswi** [comment]
**ACTIVATE ZIP-ARCHIVE**
sudo apt-get install php7.2-zip
sudo /etc/init.d/apache2 restart

the above needs to be done on server where LenaSYS are installed to enable this feature.

**Pull request closed without merging**
