### PR TITLE
Fixed #14398

### LINKED ISSUE #14398: Github download cooldown should be per-course and not global
### Problem Description

The cooldown for downloading & checking for changes in github repo is currently setting a global cooldown for all courses. This should not be the case, instead it should set a download cooldown for the specific course where the fetch-request took place while other non-related courses are un-affected by this request.

### Expected Behavior

The cooldown should be applied on a per-course basis rather than globally. This means that when a fetch request is made for a specific course, only that course should enter a cooldown period for downloads and change checks. Other courses, not related to the current fetch request, should remain unaffected and accessible without waiting for the cooldown to expire.

### PR DESCRIPTION
**Pull request by a22karja**
- #14398

added SESSION[updatetGitReposCooldown][$cid] to refreshCheck in gitcommitService.php
So that the update cooldown is connected to courses through the course id

### CODE REVIEW

**Comment by a22moamy** [comment]
# The functionality works as intended
The added functionality works, but not visually. 

## A potential issue
After visiting a course page for the first time and entering a cooldown for the first time, the cooldown won’t be visibly expressed as a number. This can be seen in the following figure:
Skärmavbild 2024-04-10 kl  14 01 47

## Another potential issue
To see the cooldown expressed in numbers, the user has to press the button again and refresh the page through the web browser, then the cooldown will be shown. Is this per design or is it worth another issue?

Similarly, this can happen:
Skärmavbild 2024-04-10 kl  13 49 37

This, again, is since the page does not update the cooldown without having the user press on the button and then refresh the page. Perhaps the cooldown should be updated in intervals to avoid confusion? 

After downloading a Github repo and refreshing the page, the cooldown will say 0. To get the actual cooldown, you have to press the button again and then refresh the page again. 

## A third potential issue
Additionally, going into a course after having entered a cooldown in another course will display the same cooldown from that course. For example, if the user entered a cooldown in “Datorgrafik”, then headed into “Webbprogrammering”, then “Webbprogrammering” will display the same cooldown as in “Datorgrafik”. 

Nonetheless the expected functionality of this issue still works.

**Review by a22moamy — CHANGES_REQUESTED** [review]
# The functionality works as intended
The added functionality works, but not visually. 

## A potential issue
After visiting a course page for the first time and entering a cooldown for the first time, the cooldown won’t be visibly expressed as a number. This can be seen in the following figure:
Skärmavbild 2024-04-10 kl  14 01 47

## Another potential issue
To see the cooldown expressed in numbers, the user has to press the button again and refresh the page through the web browser, then the cooldown will be shown. Is this per design or is it worth another issue?

Similarly, this can happen:
Skärmavbild 2024-04-10 kl  13 49 37

This, again, is since the page does not update the cooldown without having the user press on the button and then refresh the page. Perhaps the cooldown should be updated in intervals to avoid confusion? 

After downloading a Github repo and refreshing the page, the cooldown will say 0. To get the actual cooldown, you have to press the button again and then refresh the page again. 

## A third potential issue
Additionally, going into a course after having entered a cooldown in another course will display the same cooldown from that course. For example, if the user entered a cooldown in “Datorgrafik”, then headed into “Webbprogrammering”, then “Webbprogrammering” will display the same cooldown as in “Datorgrafik”. 

Nonetheless the expected functionality of this issue still works. The different courses still have their own cooldowns, just not always visually.

**Review by a22moamy — APPROVED** [review]
# Great, approved
Great! Everything works perfectly. Now the cooldown is updated live and is even expressed in minutes and seconds. Much better for human readability. The cooldown for every course is individual as well. 

Here's how it looks like:
Skärmavbild 2024-04-11 kl  13 44 38

No errors have been found through deleting history / cache either. Cooldown is also hidden when entering a course for the first time.

**Review by a22willi — CHANGES_REQUESTED** [review]
Dont use the $_session for this, the cooldown should be for all users, not for individual users. But each course should have its own cooldown.

**Review by a22willi — APPROVED** [review]

**Pull request merged**
