### PR TITLE
Ds21#1420 - List Page

### PR DESCRIPTION
**Pull request by a13chrju**
for issue: https://github.com/HGustavs/LenaSYS/issues/1420
and: https://github.com/HGustavs/LenaSYS/issues/1452
and finally:  https://github.com/HGustavs/LenaSYS/issues/1251

includes pull request: https://github.com/HGustavs/LenaSYS/pull/1522

*Fix for the list page, you can edit lists and they are displayed after issue 1420.*

### CODE REVIEW

**Comment by a13oscwe** [comment]
Looks really good! Please add testdata for existing courses so we can see how it looks for a bigger course without having to create a new course to see the list output

**Comment by a13denli** [comment]
The code in resultlisted.js is not following code standard.

**Comment by a13chrju** [comment]
okey fixed the file to follow code standard :)

**Comment by c13andka** [comment]
Works perfectly for me! seems good :100: %

**Pull request merged**
