### PR TITLE
Showdugga.php now outputs the filename and respective filepath for json diagram #11664

### PR DESCRIPTION
**Pull request by a16linas**
Added functionality where showdugga.php now lists the filename and filepath for the selected json diagram in variant editor. You can test this by selecting a json diagram and creating a new variant on a diagram dugga, then view said dugga from sectioned and look at the console output, you should see a json filename and filepath. Will add functionality where we read its content to generate a new diagram in #11666 
bild

### CODE REVIEW

**Comment by a20edwth** [comment]
Followed test instruction. Worked as intended.

**Comment by a20micro** [comment]
Additional functionality has been added. As Javascript doesn't support opening local files without user input (safety reasons, meaning file-path as a string can't be used), approach had to be changed and functionality has been moved to showDugga.php as php allows dynamic fetching of file content. 

For testing, rather than filename and filepath, entire content of .json file will be shown as console output.

**Comment by a20gabpa** [comment]
Test failed. When selecting a global file, "Untitled-1.json" or "testfile.json", I get the following alert message. It seems that the code can not find the file.

image

However, it seems to work if a file is in course local instead. I have created a .json-file "test.json" and when selecting this file instead, it prints out the correct content.

image

image

**Comment by a16linas** [comment]
Merged #11664 to #11666 so we're removing this pull request

**Pull request closed without merging**
