### PR TITLE
G4 2020 w15 issue#7888 2

### PR DESCRIPTION
**Pull request by a18frior**
#7888  #7250 regex doesn't accept (åäö) anymore. Error message says Only letters (not åäö).

### CODE REVIEW

**Comment by b18alegu** [comment]
Should this really be merged into the master branch??? @a17robhe

**Comment by a17robhe** [comment]
It's been fixed, i missed that the request targeted the wrong branch, sorry

**Comment by b18alegu** [comment]
Are you sure the master branch restored to the same state as after last weeks merge? @a17robhe, I am not really sure how to check that. I've almost merged to the master branch myself... It can easily happen.

**Comment by a17robhe** [comment]
The revert should undo all the changes this pull did, but I'll investigate

**Comment by a18kaswi** [comment]
Need to redo this PR

**Pull request merged**
