### PR TITLE
Fixed: Lines should have different connection points on recursive relationships. #10619

### PR DESCRIPTION
**Pull request by a19vikth**

### CODE REVIEW

**Review by b19jenda — CHANGES_REQUESTED** [review]
There are many errors occuring when clicking the lines and changing to recursive, also there are many console.logs left

**Review by a19chrel — CHANGES_REQUESTED** [review]
You need to look over the offsets. There is something with the connection points that isent correct.
bild

**Review by a19matma — APPROVED** [review]
LGTM!

**Review by b19jenda — APPROVED** [review]
Looks good

**Review by a19chrel — APPROVED** [review]
Looks good after the changes.

**Pull request merged**
