### PR TITLE
Create Update-profileservice-tests.txt

### PR DESCRIPTION
**Pull request by b21hamwe**
Written a txt test file for profileservice.php

### CODE REVIEW

**Comment by b21kurar** [comment]
Please be clear with which variables/data is sent such as here: 
image
or here:
image

**Review by c21alest — CHANGES_REQUESTED** [review]
I understand how you want the tests to be made but I would like to see more structure to your descriptions, you have made some comments in the code that you have copied which is some what hard to see. And you have forgotten to write code Row on 2 of your tests, and you have not given any name to any of your tests. And I can't find any pre-req and such. Read trough the README file in service-test and try to make a structure out of that.

**Comment by b21hamwe** [comment]
Somewhat of an late review...
Since the merge is gonna take place in a moment! 
Don't think there'll be any time to fix this before the merge.

**Comment by a19hakja** [comment]
We have a new PR for this issue which is based on the v4 branch

https://github.com/HGustavs/LenaSYS/pull/13615

**Pull request closed without merging**
