### PR TITLE
Fix for issue #6280

### PR DESCRIPTION
**Pull request by b17robev**
Fix for issue #6280

Bounding rect should now be implemented correctly. 
It is set once the canvas is loaded and also when the window is resized.

The current branch to test on is gruppA2019W18#5609

### CODE REVIEW

**Comment by b17timjo** [comment]
Note: issue #5609 concerns the ability to remove user group membership in "accessed", I think this merge references the wrong issue.

**Comment by a17drama** [comment]
I couldn't agree more. Resolving this asap.

**Comment by a17jacsv** [comment]
@a16tobfr: Please test this pull-request again after recent fixes with solved conflicts.

**Comment by a17jacsv** [comment]
Approved.

**Pull request merged**
