### PR TITLE
Code view#991 not working in some browsers

### PR DESCRIPTION
**Pull request by f12danjo**
With this fix, the codeviewer works in Internet Explorer. Fixes issue [#991](https://github.com/HGustavs/LenaSYS/issues/991)

### CODE REVIEW

**Comment by c13caral** [comment]
the code in Template4 doesn't follow the code standard.
Look at  line 7-8, 19-20, 32-33

**Comment by a13jorla** [comment]
The fix makes all examples work in every browser i had like Opera, Firefox, Explorer and Chrome.

**Comment by f12danjo** [comment]
The indentation looks weird in github sometimes, it has proper indentation if you open it in another editor like Notepad++.

**Comment by a13jorla** [comment]
Because of that we could not find any more reason not to merge this fix we will do it.

**Pull request merged**
