### PR TITLE
Fixed issue #5723

### PR DESCRIPTION
**Pull request by a16jenja**
Issue: #5723 
Co-author: @a17okaoz 

In diagram_mouse if the coordinates in the info toolbar get below 0 it will be set to 0.

In diagram if the mouseDiff get below 0 AND the coordinates are at 0 in x or y the canvas will not move.

### CODE REVIEW

**Comment by a17drama** [comment]
Issue for this has been updated. Please check the updates.

**Comment by a16jenja** [comment]
Issue: #5723 

No longer able to move the canvas at all and took the liberty to comment out labels and anything else relevant to moving the canvas.

There is a lot of dead code in the system now since I didn't remove anything that was relevant to moving the canvas, I just removed the option to even enter that moveable mode by pressing space.

Let me know if I should remove all the dead code. Since it might be useful to keep, if in the future we want to reimplement the movement of the canvas again.

**Comment by a17drama** [comment]
Prioritize this over #5826 and read the comments from the developer. Important arguments there.

**Comment by a17jacsv** [comment]
Yes, I agree. We put this matter on hold for now.

**Comment by a17jacsv** [comment]
I close this pull-request because there is a better solution on the go. https://github.com/HGustavs/LenaSYS/issues/5826

**Pull request closed without merging**
