### PR TITLE
ER to UML, UML to ER options panel dropdown issue #12694

### PR DESCRIPTION
**Pull request by b21oscpe**
It is now possible to switch types with enter and the save button with the options-pane acting accordning to the switch. 

An another note:
The type-changing is not 100% accurate and desirable yet (Because UML classes cant count lines for some reason). This makes it so that it is possible to change from UML - UML to UML - ER, between relations

Image below shows that the system seems to think there are 0 lines connected to the UML element:
7d8560efd4160df8975b00990d27f54a

### CODE REVIEW

**Comment by b21oscpe** [comment]
Original issue: #12694

**Review by a21aldsa — CHANGES_REQUESTED** [review]
When switching anything to SD, everything breaks. Things also break when switching from IE to UML. Also you cannot switch SD to anything, it just says "successfully saved" without any visible changes.

**Comment by b21oscpe** [comment]
SD worked like this from the start,

I looked into it now and found that this is because it was added recently and hasnt been configured properly within the stateChanged() aswell as many other areas of the code

**Comment by b21oscpe** [comment]
SD should now work as intended, however, lines aren't counted correctly for UML & SD, this is another issue though

**Review by a21aldsa — CHANGES_REQUESTED** [review]
As previously noted, switching to UML can break things but it seems that this will become a new issue, judging by the comments on this PR. 

Something I would like to see fixed though is the rules for switching type while an element is connected. It is currently possible to change any UML, IE or state to anything, even if it already has connections:

image

**Comment by b21oscpe** [comment]
In what way does UML break?

Yes as previously mentioned the lines function is broken

**Comment by a21aldsa** [comment]
> In what way does UML break?
> 
> Yes as previously mentioned the lines function is broken

We had a private conversation about this but the summary is that we made sure I was on the right branch and I showed him that placing text on elements, like functions or name. I also showed him how you can create non allowed connections like IE-state. And how changing IE, or state to UML breaks everything.

**Comment by a21aldsa** [comment]
> In what way does UML break?
> 
> Yes as previously mentioned the lines function is broken

We had a private conversation about this but the summary is that we made sure I was on the right branch and I showed him that placing text on elements, like functions or name. I also showed him how you can create non allowed connections like IE-state. And how changing IE, or state to UML breaks everything.

**Comment by b21eriho** [comment]
What does that mean for this issue?

**Comment by a21aldsa** [comment]
> What does that mean for this issue?

Its essentially just a testing I did and then reported my findings verbally while we both looked at the same screen. This does not affect the issue more than any other testing. The comment is just to make the test documented.

**Review by a21aldsa — APPROVED** [review]
Since this issue only covers switching element types via the drop down panel, and this now working perfectly fine; I will consider this issue to be resolved. All issues that were discovered during this (like the ability to make illegal connections to other elements by switching the type) have been made into new issues, as far as I am aware. Therefore this issue is resolved.

**Pull request merged**
