### PR TITLE
Removed padding in accessed

### PR DESCRIPTION
**Pull request by a13karsi**
The add button doesn't have this huge space between itself and the list anymore. 

See issue #1678

### CODE REVIEW

**Comment by a13chrju** [comment]
pic

the background color isnt covering the items for some reason

**Comment by a13karsi** [comment]
That's weird! It works on my machine, do you have any idea why this happened?

**Comment by a13chrju** [comment]
ill try downloading your whole branch, maybe that's why

**Comment by a13denli** [comment]
Looks weird for me too:

image

**Comment by a13chrju** [comment]
looks good. :)

**Pull request merged**
