### PR TITLE
 Add JSON files to the project #13264 

### PR DESCRIPTION
**Pull request by a21aldsa**
Uploaded a couple JSON files holding diagrams to the server. Created a function called loadMockupDiagram which takes the parameter to determine the type of mockup that should be loaded, IE or UML (when future mockups are created, they can be easily added). And then fetches this file from the server, and calls loadDiagram with that json file as parameter.

### CODE REVIEW

**Review by b21matfi — APPROVED** [review]
checked by calling the function  loadMockupDiagram with parameters 0 and 1, it loaded different diagrams.

**Comment by b21oscpe** [comment]
Putting this merge on hold as we discuss the posibilities of the files being stored on the server instead

**Comment by a21nibah** [comment]
This is an elegant solution. 2 things. Please restructure your parameters so it is not dependent on numbers but rather are more clear. The er type is missing.

**Comment by a21nibah** [comment]
actually now that i think about it  I believe it would be better if you just had the path as a parameter to make this reusable and then you can specify the path you want instead

**Comment by a21aldsa** [comment]
> This is an elegant solution. 2 things. Please restructure your parameters so it is not dependent on numbers but rather are more clear. The er type is missing.

The er type is missing since the issue for creating the ER json is not completed, #13212.

**Comment by a21aldsa** [comment]
> actually now that i think about it I believe it would be better if you just had the path as a parameter to make this reusable and then you can specify the path you want instead

I will implement this

**Comment by a21aldsa** [comment]
> actually now that i think about it I believe it would be better if you just had the path as a parameter to make this reusable and then you can specify the path you want instead

I have now implemented this feedback. The function now wants a path to a json file as parameter, if the parameter is faulty the .catch of the fetch will catch this.

**Review by b21matfi — APPROVED** [review]
testing with loadMockupDiagram("JSON/UMLDiagramMockup.json") works but merge is still going to be put on hold untill all the files are done

**Comment by a21aldsa** [comment]
> testing with loadMockupDiagram("JSON/UMLDiagramMockup.json") works but merge is still going to be put on hold untill all the files are done

The ER diagram just got completed, in issue #13212 I have added it. Note that #13212 is untested so if that test comes back negative this commit will have to be reverted. I do not recommend merging just yet.

**Comment by b21oscpe** [comment]
I would suggest you test to see if the JSON file provided in #13212 is loadable and if it is we can merge

**Comment by b21matfi** [comment]
im going to test it today

**Comment by b21matfi** [comment]
can you make another request so that i can approve or comment?

**Comment by a21aldsa** [comment]
> I would suggest you test to see if the JSON file provided in #13212 is loadable and if it is we can merge

It loads just fine, although it is worth noting that the ER diagram and the IE are way off center.

**Comment by a21aldsa** [comment]
The ER diagram in #13212 has been updated, I will make a new commit for this new, updated, file.

**Comment by b21matfi** [comment]
a21aldsa do you want me to wait with the testing until you are done?

**Comment by a21aldsa** [comment]
> a21aldsa do you want me to wait with the testing until you are done?

It has now been updated to the new ER model.

**Review by b21matfi — APPROVED** [review]
All of them are loadable, Works good. Nice Work. Uses the file path as intended

**Pull request merged**
