### PR TITLE
Centralized course text for mobile view

### PR DESCRIPTION
**Pull request by a19kimgr**
fixed so course name is more centralized in mobile view.

### CODE REVIEW

**Review by b18phika — CHANGES_REQUESTED** [review]
It's impossible to center the course name exactly with hardcoded margins since the course names have different lengths. I think it'd be better to use a solution that relies on flexbox (display: flex), and apply a margin-right that equivalent to the width of the arrow on the left, to get it exactly centered.

**Review by a18willi — COMMENTED** [review]
Looks better. But currently it looks like the text is centralized inbetween the right edge of the arrow/arrows and the right edge of the purple banner. For the text to be completely centralized the text position should not take the arrows into consideration. It looks like this problem still stands even if not in mobile view, it just gets more obvious when in mobile view. Maybe a new issue should be created to get this fixed.

**Comment by a19kimgr** [comment]
The coursename is now in the middle, always, without any margins, with the exception if screen width is smaller than 200px where the text starts to disapear. However, most (if not all ) mobile devices have a screen width bigger than 200px so this should now be fixed.

**Comment by b18phika** [comment]
image

As shown in the image, the text is centered between the arrows and the right side. It's however not in the center of the screen, which I believe to be the intended behavior.

**Review by a18willi — CHANGES_REQUESTED** [review]
Requesting changes due to the same reason @b18phika stated.

**Review by b18phika — APPROVED** [review]

**Review by a18willi — APPROVED** [review]

**Pull request merged**
