### PR TITLE
G1 2023 v2 #13282

### PR DESCRIPTION
**Pull request by b21matfi**
Used css to fix the issue

### CODE REVIEW

**Comment by b21eriho** [comment]
Which icons have you fixed? All but the triangle arrow and weak?

**Comment by c21adano** [comment]
I fixed the conflict on line 1101, it was caused by an extra space from issue#13226. Please test again to see that nothing broke.

**Comment by b21matfi** [comment]
all should be fixed that were not fixed before

**Review by b21eriho — CHANGES_REQUESTED** [review]
All looks good apart from the black triangle which looks like the normal triangle
image

**Comment by c21adano** [comment]
> All looks good apart from the black triangle which looks like the normal triangle image

this is caused by issue#13226 adding a black triangle. It doesn't have to be fixed in this issue.

**Comment by b21eriho** [comment]
Now this clearly overlaps with issue #13209 and how this should be handled I do not know

**Comment by c21adano** [comment]
> Now this clearly overlaps with issue #13209 and how this should be handled I do not know

#13226 and #13209 are the same issue, #13226 is the merged pull request

**Comment by b21eriho** [comment]
Yes, in either case the black arrow does not look right though I think it looked right previously since issue #13226 was merged, so this seems to me like a conflict-solving issue

**Comment by b21eriho** [comment]
I missed you comment with the image, in that case I'll approve my review

**Review by b21eriho — APPROVED** [review]

**Comment by c21adano** [comment]
to clarify #13226/#13209 was the issue that this issue #13282/#13298 had a conflict with. After resolving the conflict the black arrow changes were merge into this issue. Therefor i rule that it would be unfair to push improvements that can be done to #13226/#13209 onto b21matfi.

I will now merge this into g1-2023-v2, then an issue regarding the black arrow will be made.

**Pull request merged**
