### PR TITLE
Give option to add contribution dugga during install

### PR DESCRIPTION
**Pull request by a17adajo**

### CODE REVIEW

**Comment by a17adajo** [comment]
Will be added to Datorns grunder course:

image

**Comment by a17adajo** [comment]
Option during install:

image

**Comment by a17adajo** [comment]
Fixes #6849

**Comment by a17poner** [comment]
Looking at the discussion that was had with @HGustavs wouldn't it make more sense to have this included in the testdata? maybe add a whole extra course with enough data and all the various duggas and sections needed to test and showcase/demo all the features that are likely to be worked on during the project?

**Comment by a17adajo** [comment]
I agree! a demo course should be the long term goal!

**Comment by HGustavs** [comment]
Feel free to steel from the running courses on the real server for inspiration.

Any publicly visible content is CC0.

**Comment by a17poner** [comment]
So would it be better then to ignore this and instead have that included in the testdata always when testdata was chosen + the extra visible content for all the other quizes and views that would fit into testdata?

**Pull request closed without merging**
