### PR TITLE
G1 2021 #10984

### PR DESCRIPTION
**Pull request by a19gusba**

### CODE REVIEW

**Review by a19arvka — APPROVED** [review]
All functionality remains & localstorage is clean. Great!

**Review by a18osken — CHANGES_REQUESTED** [review]
It seems that the teacher links in resulted now randomize the variant for the teacher or something like that, you do not get the same variant anyways.

**Review by a18osken — APPROVED** [review]
It Twerks

**Comment by a17alfja** [comment]
I found a better solution that doesn't require another ajax call.
Pls review again (sorry!)

**Review by a19arvka — APPROVED** [review]
Great!

**Review by a18osken — APPROVED** [review]
Not having to call the service script again is a really nice find!

**Pull request merged**
