### PR TITLE
Issue #9792 center/ left alignment

### PR DESCRIPTION
**Pull request by a18nadma**
Added if statement so center alignment becomes left alignment after a certain amount of characters.

### CODE REVIEW

**Review by a19frelu — CHANGES_REQUESTED** [review]
* Does not work with different width of the elements.
* Only work on the entities, not relations or attributes.
* Use calculation which uses the pixels amount of characters/width of the letters > element width, instead of fixed maximum character value (const maxchar = 29;).

**Comment by a19hammi** [comment]
Updated branch to latest weekly build

**Review by a19frelu — APPROVED** [review]
The changes of the code now makes the text in the elements behave as wished for. The code aligns the text in the center of the object as long as the element is wider then the text. 
If the text is wider then the edges of the element, the text will align to the left in the element to make it possible to read the beginning of the text in each element.

The text alignment is now also depending on how wide the element is wich also was requested.

And for last. The code is now implemented to act over all of the elements, not only the entities, but also the relations and attribute elements.

Good job!

**Comment by a19hammi** [comment]
Re-opening under new branch

**Pull request closed without merging**
