### PR TITLE
Analytics page and "hamburger"-button now shows properly for both teachers and superusers. Issue#10499

### PR DESCRIPTION
**Pull request by a18willi**
Access to analytics now checks if the user is a superuser or creator. Most teachers are creators but not superusers therefore the old code only including superusers didnt work.

### CODE REVIEW

**Review by a18danli — APPROVED** [review]
Works for me!

**Review by a19samke — APPROVED** [review]
It works for me!
 I also wonder if the hamburger button  shoud be on the section page, when logged.in as a student ?

**Comment by a19isada** [comment]
> It works for me!
> I also wonder if the hamburger button shoud be on the section page, when logged.in as a student ?

It should not, those menues are only available for teachers and superusers

**Comment by a18willi** [comment]
Note: In the description of this pull request i mentioned that most teachers are marked as creators. This is not the real purpose of the creator table and therefore should not be used in this solution and should not be used to identify teachers in future solutions.

**Pull request merged**
