### PR TITLE
Code viewer saving descriptions as file with markdown text instead of text in the database #473

### PR DESCRIPTION
**Pull request by a13henhu**
Now it's able to read from a .txt file.

#473 

And also creds to @b12simsa for working togheter.

### CODE REVIEW

**Comment by c13caral** [comment]
boxwordlist have to change to boxWordList because of our code standard.
And all of the alerts have to go.

for(var j = 0; j < 5; j++){
	alert("i: " + i + " j: " + j + " data: ");
	alert(retdata['box'][i][j]);
}

It is making very hard to test the webpage. I mean it is kinda annoying with all the alert popping up.
And I m sorry to say this but your code doesn't work. (The picture is from example id 13.)

skarmavbild 2015-04-21 kl 14 47 16

**Comment by c13caral** [comment]
btw if you are going to test his branch. you have to change this:

$query = $pdo->prepare( "select exampleid, sectionname, examplename, beforeid, afterid from codeexample where cid = :cid and cversion = :cvers order by sectionname, examplename;");
		$query->bindParam(':cid', $courseId);
		$query->bindParam(':cvers', $courseVersion);
		$query->execute();

To:
$query = $pdo->prepare( "select exampleid, sectionname, examplename, beforeid, afterid from codeexample order by exampleid");
		//$query->bindParam(':cid', $cid);
		//$query->bindParam(':cvers', $cvers);
		$query->execute(); 

In editorService.php file.

**Comment by a13henhu** [comment]
I have made some changes, the reason that it didn't work was because I forgot to update one of the files, so it was stoneaged old, the new file is up. And this is also realated to an issue. #668 And it would be an issue if we changed the variablenames, cause it would casue huge errors in this pull request.

**Comment by c12jenek** [comment]
Works just fine with this new update, variable names follows the code standard, great! Ready for merge

**Pull request merged**
