### PR TITLE
G2 2023 v4 issue#13491

### PR DESCRIPTION
**Pull request by b21hamwe**
Done researching and making changes in-order to label the $info variable so that we in our log.php file can see what all the other variables in $info carry in form of data. 
This new "styling" do not change the earlier tables of data, but every new log will be printed out in this new format.

### CODE REVIEW

**Review by b21tilbe — APPROVED** [review]
The code snippets are syntactically correct. It seems to work correctly with JSON too. Approved

**Comment by b21hamwe** [comment]
? JSON ?
The solution doesn't send any JSON data ? 

What do you mean with, "seems to work correctly with JSON too." ?

**Comment by b21tilbe** [comment]
Sorry, has been reviewing wrong file.

**Comment by b21hamwe** [comment]
d21erisu, ready to merge.

**Pull request merged**
