### PR TITLE
G2 2021 w20 issue#10556

### PR DESCRIPTION
**Pull request by b19wilfo**
New items now glow if they are less than a week old. 

Co-author: @a19danla

### CODE REVIEW

**Comment by a19isada** [comment]
Should the new items glow for everyone or just for teachers? @b19wilfo @a19danla

**Review by a18willi — COMMENTED** [review]
Right now the new items glow red for 2-3 seconds then abruptly stop and never glows again. Is this intended or is it supposed to glow/blink any longer?

**Comment by a19danla** [comment]
In the old functionality it was for everyone so we kept it that way @a19isada

**Comment by b19wilfo** [comment]
> 
> 
> Right now the new items glow red for 2-3 seconds then abruptly stop and never glows again. Is this intended or is it supposed to glow/blink any longer?

The glow-time is how it was before and we didn't need to change it. We can change it if necessery.

**Review by a18willi — APPROVED** [review]
Since what i left in my comment earlier seemed to be intended this looks great!

**Review by a19isada — APPROVED** [review]
Works well and looks good!

**Review by b16oskni — APPROVED** [review]
Everything works as intended!

**Pull request merged**
