### PR TITLE
Swimlane layout change

### PR DESCRIPTION
**Pull request by a18danli**
Co-Authored-By: a19samke <62887067+a19samke@users.noreply.github.com>

### CODE REVIEW

**Review by a18willi — CHANGES_REQUESTED** [review]
image
image
As seen above the spacing is not consistent between different courses

**Review by b18phika — CHANGES_REQUESTED** [review]
The spacing at the top and bottom of swimlanes seems a bit big, and is inconsistent between courses. See @a18willi review for pictures. Tested in both Chrome and Firefox.

**Review by a18willi — APPROVED** [review]
Looks better now! Everything seems to be consistent between courses.

**Review by b18phika — APPROVED** [review]
Looks good

**Pull request merged**
