### PR TITLE
G2 2023 v3 issue#13330 v3

### PR DESCRIPTION
**Pull request by a21ponkr**
Created a search functionality for log.php in issue #13330

### CODE REVIEW

**Comment by a21ponkr** [comment]
this is in need of a review

**Comment by b21kurar** [comment]
This pull request also makes changes to an unrelated file, this shouldn't be part of the PR

**Comment by a21ponkr** [comment]
I have put the javascript portion to another file called logSearch.js
I don't know if I can do anything about the readme.md part since it was not my commit

**Comment by a19hakja** [comment]
I'll set this up for review and if we need to convert to php we'll make an additional issue

**Review by a21jeaha — APPROVED** [review]
from what i could gather the search function does what was asked. 
The only problem i could find is that this is based on the old log.php. I cannot say if this will work with how that file functions now.

**Pull request merged**
