### PR TITLE
Code viewer#871 markdown bold/italics

### PR DESCRIPTION
**Pull request by b12simsa**
Added a markdown parser, and a call to the parser. 
The parser is not yet fully functional, and to test it the variable desc must be reassigned a value before sent into the parser.

### CODE REVIEW

**Comment by a13alfbe** [comment]
It works! Just need someone else to take a look at this before i merge it.

**Comment by b12simsa** [comment]
There might to be some problems with Chrome, will do some further testing.

**Comment by f12danjo** [comment]
Works in Chrome now after "new Map()" got changed to "{}" when initializing the maps.

**Comment by c13caral** [comment]
I have tested this and everything works!

**Pull request merged**
