### PR TITLE
Group3 2021 w17 #10377

### PR DESCRIPTION
**Pull request by a18nadma**
Selected lines no longer gets deselected when moving a line \o/

### CODE REVIEW

**Review by a19karal — APPROVED** [review]
Funkar som det ska :)

**Comment by a19nikbo** [comment]
This does not quite do what the issue was about. Note that it says "*Panning* deselects lines but not elements". This means that clicking on the background without moving the mouse should still deselect all lines. It's only when panning that they shouldn't be deselected.

**Review by a19karal — CHANGES_REQUESTED** [review]
Funkar inte som det ska >:(

lines are still "selected" after you click away (background)

**Review by a19karal — APPROVED** [review]
Funkar som det ska :)

**Pull request merged**
