### PR TITLE
Added btn-disable class

### PR DESCRIPTION
**Pull request by a17alfja**
btn-disable class prevents click and alters color of button.

### CODE REVIEW

**Review by a19rebsa — CHANGES_REQUESTED** [review]
I think that the buttons should only be disabled on already handed in assignments, and not all the time for teachers

**Review by a13zanal — CHANGES_REQUESTED** [review]
The save and reset buttons are disabled for all assignments as a teacher, maybe should only be for submitted assignments?

**Review by a13zanal — APPROVED** [review]
Looks good!

**Review by a19rebsa — APPROVED** [review]
Works great

**Pull request merged**
