### PR TITLE
Update style.css (Issue #10265)

### PR DESCRIPTION
**Pull request by b19alest**
Changed from hardcoded colorcode to predefined variables.

### CODE REVIEW

**Review by a19isada — CHANGES_REQUESTED** [review]
There is still contrast issues. Lighthouse test does not pass.

image

**Review by a18willi — CHANGES_REQUESTED** [review]
The contrast problem described in the linked issue is still present in branch G2-2021-W18-ISSUE#10265

**Comment by b19alest** [comment]
@a18willi @19isada Changed more tags because all types of duggas/moments etc didn't have the same tag that changed backgroundcolor/textcolor. Know all types are changed so all different duggas/moments/tests should have the same backgroundcolor/textcolor. Also a new item had opacity drawn down and caused contrast problems, so I took away that aswell (.hidden-tag). 

@a19anjst @b18phika but we still maybe want a new item to "stand out" from other items, can take up this on the next customer meeting maybe?

**Comment by a19anjst** [comment]
Will write it down as something to consider for next customer meeting

**Comment by b18phika** [comment]
@b18alest We'll bring that up on the next customer meeting. However, we think that it'd be a better idea to create a new issue for that, so I'll re-request reviews for this issue.

**Review by a19isada — APPROVED** [review]
Text is much clearer now. Lighthouse also passes.

**Review by a18willi — APPROVED** [review]
Looks great! Lighthouse isnt complainging about contrast issues anymore.

**Pull request merged**
