### PR TITLE
 Add functionality for sequence loop or alternative #13914 new

### PR DESCRIPTION
**Pull request by a21aldsa**
Since the first branch had so many issues, this is the new branch that will be merged into fix3 of v6. see #13980 for explanation on what this new element is and can do.

### CODE REVIEW

**Comment by a19clasv** [comment]
It doesn't change the horizontal size if the new alternative is too long for its current size and letters get hidden if it's too narrow, but otherwise it works

**Comment by a21aldsa** [comment]
> It doesn't change the horizontal size if the new alternative is too long for its current size and letters get hidden if it's too narrow, but otherwise it works

Fair, I'll implement a line break if the length of the text is suspected to be longer than the width of the element

**Review by a19clasv — APPROVED** [review]
I'm approving this because my suggested fixes aren't completely necessary and it works fine.

**Comment by a19clasv** [comment]
Let me know when you're done pushing commits.

**Comment by a21aldsa** [comment]
> Let me know when you're done pushing commits.

Done now, I ultimately decided this was not needed right now. I can be made into its own issue if need be.

**Review by a19clasv — APPROVED** [review]
Something hasn't broken since the last time I approved the changes. Maybe a separate issue should be made to finish off the horisontal text size issues.

**Comment by b21eriho** [comment]
For tester, ensure the buttons in the pop-out work as these also had conflicts

**Review by a19clasv — APPROVED** [review]
Pop-out buttons work as well.

**Pull request merged**
