### PR TITLE
Simple fix for move icon being slightly off center in firefox, issue #7621

### PR DESCRIPTION
**Pull request by a18andtu**
See issue for picture of how it looked before.

### CODE REVIEW

**Comment by a18andtu** [comment]
Moved the icon to be inside the black border.

**Comment by b18phibe** [comment]
please move the button to 
  right: 12.3px;
  top: 85.4px; 👯‍♂️

**Comment by a18andtu** [comment]
image
Is this better?

**Comment by a18andtu** [comment]
waiting to fix this since some changes will be made so that it can be made relative to the canvas

**Pull request closed without merging**
