### PR TITLE
G2 2023 v5 issue#13494

### PR DESCRIPTION
**Pull request by a21ponkr**
Created a sorting method in log.php
Issue: #13494

### CODE REVIEW

**Comment by a21ponkr** [comment]
> There are some conflicts in logSearch.js that I think needs to be resolved. Otherwise, it looks good.

Looks like they changed the name of the file, will take a look

**Comment by a21jeaha** [comment]
I changed the name of the file, i had an issue where i was to transition log.php into a service. 
the contents of logSearch.js was such that it was part of the multi file structure that the services consist of. As such the file was renamed into log.js.

**Comment by a21ponkr** [comment]
> with that said whatever new functionality that was meant for logSearch.js should now be made in log.js

All javascript code is inside log.js now but there's still a conflict somehow, haven't changed the logSearch.js part only added logSort.js part into log.js

**Comment by a21ponkr** [comment]
> > > with that said whatever new functionality that was meant for logSearch.js should now be made in log.js
> > 
> > 
> > All javascript code is inside log.js now but there's still a conflict somehow, haven't changed the logSearch.js part only added logSort.js part into log.js
> 
> have you tried resolving that conflict on your githubclient? (i have not done this before)

Says it doesn't have a conflict anymore after i removed the sorting part and put it into another javascript-file. However that's wrong because I assume that every javascript code should be inside log.js?

**Comment by a21jeaha** [comment]
> > > > with that said whatever new functionality that was meant for logSearch.js should now be made in log.js
> > > 
> > > 
> > > All javascript code is inside log.js now but there's still a conflict somehow, haven't changed the logSearch.js part only added logSort.js part into log.js
> > 
> > 
> > have you tried resolving that conflict on your githubclient? (i have not done this before)
> 
> Says it doesn't have a conflict anymore after i removed the sorting part and put it into another javascript-file. However that's wrong because I assume that every javascript code should be inside log.js?

that's right, all js related code should be in log.js
but as i gathered you probably need to resolve the conflict on your github client

**Comment by a21ponkr** [comment]
@a20fanma please review again

**Comment by d21erisu** [comment]
> @a20fanma please review again

you can re-request review to alert the reviewer that changes has been made

**Review by a20fanma — APPROVED** [review]
It looks good

**Comment by d21erisu** [comment]
Great

**Pull request merged**
