### PR TITLE
Create a button for objects according to #13577 #13580

### PR DESCRIPTION
**Pull request by a21aldsa**
created the icon and added it to the menu, with appropriate tooltip, alt, etc.

### CODE REVIEW

**Review by a19clasv — DISMISSED** [review]
It's done, but it could be slightly broader and shorter to make it more like the model for an object box. Right now it looks almost like a horisontal activation box.

image

**Comment by a21aldsa** [comment]
Thats just the key, please look at the actual model in #13535

**Comment by a19clasv** [comment]
The conflicts do need to be fixed though

**Comment by a19clasv** [comment]
Still works

**Comment by c21adano** [comment]
I resolved the new conflict

**Comment by a19clasv** [comment]
It performs well yet again

**Pull request merged**
