### PR TITLE
Update The message of the day and added to the hamburgerBox

### PR DESCRIPTION
**Pull request by a19samke**
@a18danli 
The message of the day button moved to the dropdown menu in mobile vers!

### CODE REVIEW

**Review by a20chrjo — APPROVED** [review]
Works as intended, in Chrome, Edge, Firefox and Opera. Even when you refresh the page after removing the MOTD.

**Review by b19alest — APPROVED** [review]
Works very nice! Didn't find any issues with it.

**Comment by b18phika** [comment]
Since the dropdown isn't visible to users who aren't teachers, the motd-button isn't visible to non-teachers after this change. Is this the intended behavior?

Before:
image

After:
image

**Comment by a18danli** [comment]
MOTD Button should now work for all users, even guest. 

MOTD is not in the hamburgerbox in this version.

Try this on diffrent webbrowsers.

**Review by a19danla — APPROVED** [review]
Seems to be working as intended according to comments

**Pull request merged**
