### PR TITLE
Sorted functions into regions 

### LINKED ISSUE #10368: Set regions in code to make certain areas of the code hide-able
With the ability to "fold" regions of code would make it easier to focus on the specifics parts of the code that matter when working. This way we could fast go past regions without a bunch of scrolling!

The way to make regions is as follow:
```js
//#region REGION_NAME
function thisIsAVeryLongFunctionName(andImAnParameter) {
  hereWehaveAnotherFunctionCallWithLongName();
  var andHereIsAVariable = 10;
}

function thisIsAnotherVeryLongFunctionName(anotherOne, andAnotherOne) {
  hereWehaveAnotherFunctionCallWithLongNameAgain();
  var andHereIsAnotherVariable = 10;
}
//#endregion REGION_NAME

### PR DESCRIPTION
**Pull request by a19hammi**
fixes  #10368

### CODE REVIEW

**Review by a19steis — APPROVED** [review]
Looks good, the sorting of functions into current regions makes sense.

**Review by a19phith — APPROVED** [review]
hotel? trivago

**Review by a19aleda — APPROVED** [review]

**Review by a19matma — APPROVED** [review]
LGTM! Good job!

**Review by a19frelu — APPROVED** [review]
Guess this will work.
"THE BEST A MAN CAN GET."

**Pull request merged**
