### PR TITLE
Updated margins on Stoplights

### PR DESCRIPTION
**Pull request by a17fellu**
Removed commented out lines and changed the margin to be more consistent

### CODE REVIEW

**Comment by a17andby** [comment]
This is not our area of responsibility. This is gruppB2019 area of responsibility. They will decide if they want to implement this pull request.

@a17pongo

**Comment by a17pongo** [comment]
how does it look now?

**Comment by a17fellu** [comment]
this is how it looks like now:
new stop lights

@a17pongo

**Comment by a17andby** [comment]
(Make sure that you merge to the right branch @a17pongo, if you wanna merge it)

**Comment by a17poner** [comment]
talked to @b17nicsv  and it should be fine for group C to take this for this occassion and then in the future avoid sectioned. merging this.

**Pull request merged**
