### PR TITLE
Added basic service logging for diagramservice and highscoreservice.php - G1-2020-W17-ISSUE#8213

### PR DESCRIPTION
**Pull request by b17carbr**
Result from using the service: 

Screenshot 2020-04-17 at 12 04 45
Screenshot 2020-04-17 at 12 04 54

How to test:
Download https://sqlitebrowser.org/dl/

Choose open database
Screenshot 2020-04-17 at 12 08 08

Open the db file located in the log dir
Screenshot 2020-04-17 at 12 07 14
Screenshot 2020-04-17 at 12 07 25

Run services mentioned in the pull request:
Screenshot 2020-04-17 at 12 10 37
Screenshot 2020-04-21 at 10 58 27

then look up the result in table:
Screenshot 2020-04-17 at 12 12 38

co authored with @a18jakme

### CODE REVIEW

**Comment by a18jakme** [comment]
Because of the situation with contribution.php, we didn't find a solution for logging contributionservice.php.

**Comment by a18jakme** [comment]
@a97marbr @HGustavs We are unsure how to test this on our testserver. Do you have an idea how to do that?

**Comment by a18filkr** [comment]
Skärmklipp

Loggade entries 2 gånger som UNK

**Comment by a18filkr** [comment]
Contributionservice didn't log anything on local testing

**Comment by a18filkr** [comment]
bild

highscoreservice works on the server, contributionservice doesn't show up just like the local test.

**Comment by a18filkr** [comment]
contributionservice was changed to diagramservice. Tested this instead, seems to work fine!
bild

**Pull request merged**
