### PR TITLE
Change contribution to use standard dugga format instead of an iframe…

### PR DESCRIPTION
**Pull request by b17carma**
… since it caused a lot of issues

### CODE REVIEW

**Comment by b17carma** [comment]
Fix for issue https://github.com/HGustavs/LenaSYS/issues/6857

This also resolves the problem with there being 2 navbars

**Comment by a17joaap** [comment]
https://github.com/HGustavs/LenaSYS/issues/4193 requested loading it in an iframe

**Comment by b17carma** [comment]
Using an iframe created lots of problems (such as double navbar, problems with scrollbar overlaps etc) & with this solution the end result is the same. ShowDugga is used to show the contribution like any other dugga.

**Comment by a17joaap** [comment]
If the iFrame was needed for some reason, an easy fix for the double navbar and navbar overlapping scroll is this:

Remove from contribution.php:
```
<?php
	$noup="SECTION";
	include '../Shared/navheader.php';
?>
```

Change in contribution.js:
`<iframe style='position: fixed; top: 50px`

**Comment by a17poner** [comment]
A little bit unsure about this change since it does conflict with the issue mentioned by @a17joaap and seems like a pretty big change for what wasn't an issue on over half the groups environments. Is this change really needed?

**Comment by b17carma** [comment]
I think this change is needed for a few reasons:
- It changes contribution to use standard dugga template which I think is preferable
- It minimizes future problems which could be caused by using a iframe
- It fixes the issue with the scrollbar position (not sure if this problem can be avoided completely if using an iframe)

Capture

The screencap shows how the contribution is right now with a margin set on the frame to show the problem more clearly. Even if the navbar is removed from the iframe, the scrollbar wouldn't act the way it does on other pages since it would appear below the login/logout button and not next to it.

Like I said earlier, I don't think there's any benefit to using an iframe and this way feels a lot more proper.

**Comment by a17poner** [comment]
Still very uncertain on this since henrik specificly asked for it to be put in an iframe, not sure what advantages is but for some reason he wanted it to be in an iframe.

**Comment by b17carma** [comment]
This seems reasonable and I'll do what you suggest @a17joaap, but it would be good to get some feedback from @HGustavs to clear up why an iframe is needed :)

**Comment by a17poner** [comment]
That sounds fine, we get a solution that doesn't do to much and risk breaking things and we should hopefully get feedback from henrik if we really need the iframe, if we don't get a response before Friday I could try to remember to bring it up with him during the customer meeting.

**Comment by b17carma** [comment]
Reverted previous changes. The page now resizes the navbar to make space for the scrollbar when not on a mobile device.

**Pull request merged**
