### PR TITLE
G2 2023 v5 issue#13396 Design test for courseedservice.php

### PR DESCRIPTION
**Pull request by a21oscgu**

### CODE REVIEW

**Comment by b21antbr** [comment]
I co-contributed on this issue, copy test is very unclear how it should be performed. It is between line 181-432 and might not be needed/changed to be tested properly.

**Comment by b21antbr** [comment]
Unable to link it to issue#13396 for some reason.

**Comment by c21alest** [comment]
PR related to issue: #13396

**Review by a21ponkr — APPROVED** [review]
Looks good to me

**Pull request merged**
