### PR TITLE
Group3 2021 w17 #10067

### PR DESCRIPTION
**Pull request by b19phier**

### CODE REVIEW

**Review by a19phith — CHANGES_REQUESTED** [review]
image
Seems to be working with some minor problems, the text seems to stick out of the entity when alter the size of the entities. And the text seems to alter when the zoom in and out function use

**Comment by a19nikbo** [comment]
I would like to add that we preferably don't want to influence the spacing between characters as it makes things look inconsistent and can be difficult to read.

**Review by a19phith — APPROVED** [review]
seems to be working

**Comment by a19nikbo** [comment]
We'll have to put this on ice for the time being as it seems to be a difficult issue to solve in a satisfactory way. I'll close the pull request for now to avoid accidental merge

**Pull request closed without merging**
