### PR TITLE
Created microservice createListentrie_ms.php #14212

### PR DESCRIPTION
**Pull request by b21eddka**
Created the microservice createListentrie under sectionedService

### CODE REVIEW

**Comment by b21antbr** [comment]
Tested by adding
```
if(opt==="NEW"){$.ajax({ 
            url: "../DuggaSys/microservices/sectionedService/createListentrie_ms.php", 
            type: "POST", 
            data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para, 
            dataType: "json", 
            success: returnedGroups });}
        else {$.ajax({
        url: "sectionedservice.php",
        type: "POST",
        data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para+"&hash="+hash,
        dataType: "json",
        success: returnedSection
        });}
```
To file dugga.js

Creating a section then uses the file properly.

dugga.js changes was then revoked. So now the microservice file exists, but how it is used has to be decided later.

**Comment by a22iliru** [comment]
assigning a tester to this before merge

**Comment by a22albjo** [comment]
This pull request is trying to merge to master, i think it should merge to our group branch instead?

**Comment by c22emigr** [comment]
The php code itself in the file seems to be working but might be susceptible to SQL-injections. Connecting the file to the system seems to not work and causes other issues. The file paths for different "includes" in the file are incorrect or not up to date. Still unsure if it's possible to be implement the file into the system.

**Comment by a22eriwi** [comment]
The files that are used by this microservice are not completed. So in order for this microservice to work you also need to implement other files that are needed such as coursesypw.php and database.php which do not seem to be completed. So if we are going to implement this there needs to be work done on multiple other files also.

**Comment by a22albjo** [comment]
@a22eriwi There might be a bit of a misunderstanding about the purpose of database.php and coursesyspw.php. 
**database.php** opens a connection to the database and contains the pdoConnect(); function used by the microservices. 
**coursesyspw.php** contain only local environment variables (the username, password and database name you entered during the installation). 

Im under the impression that they are done and shouldn't be extended further with more functionality to make new microservices work. (i might be wrong tho).

**Comment by a22iliru** [comment]
> This pull request is trying to merge to master, i think it should merge to our group branch instead?

correct. changed

**Comment by a22iliru** [comment]
> This pull request is trying to merge to master, i think it should merge to our group branch instead?

correct. changed and closing issue now.

**Pull request merged**
