### PR TITLE
Ds15 #767

### PR DESCRIPTION
**Pull request by a13chrju**
okey so you should now be able to add users to access the courses
https://github.com/HGustavs/LenaSYS/issues/767

### CODE REVIEW

**Comment by a13oscwe** [comment]
Kan du ta bort width: 100% style på #content? Den påverkar hela systemet vilket inte är så bra. Annars verkar det funka att 

Can you remove the width: 100% style on #content? line 79 in shared/css/style.css. It affects the entire system and that's probably not a good idea.

**Comment by a13chrju** [comment]
yes will do!

**Comment by a13chrju** [comment]
okey fixed the width

**Comment by c13chrjo** [comment]
Since this is fixed I will merge this into our branch

**Pull request merged**
