### PR TITLE
Add output if filter list is empty

### LINKED ISSUE #2440: If blank filter list we need some output
We need a "filter list is blank" output if filter list is blank, currently nothing happens....
which may confuse the user to thing that the code is broken.

### PR DESCRIPTION
**Pull request by a15matab**
This fixes #2440.

### CODE REVIEW

**Comment by a15wilhe** [comment]
It looks a bit wierd when it's outputed to the body. Should it not be printed to the filter dropdown with id dropdownc? It is the "popup" box on hover on the "tratt" icon.

**Comment by a15matab** [comment]
Do you mean inside the actual dropdown, like the example below?

namnlos

**Comment by a15wilhe** [comment]
hmm is this for when data has been filtered (and there is no data to output equal to that filtering) or when there is nothing to filter on (when the actual dropdown list is empty)

**Comment by a15matab** [comment]
It would be after the data has been filtered. E.g if no checkboxes are selected in the dropdown and the user presses "Filter" the "Filter list is blank" text would be outputed. So instead of a completely blank page which could make the user think it's broken (I assume this is what the issue meant) it shows the text.

**Comment by a15wilhe** [comment]
ok. then I will approve your commit.

**Comment by a15wilhe** [comment]
close #2440

**Pull request merged**
