### PR TITLE
Fixed the collide issue

### PR DESCRIPTION
**Pull request by a22cazlu**
You are no longer stuck when you collide with another objekt using the arrow keys.  Implemented in some code in setPos()- if(overlapping) that make the objekt take one step back if it collide.

### CODE REVIEW

**Comment by b22jonan** [comment]
testing failed. moved object into another one and tried moving down and it was still stuck

https://github.com/HGustavs/LenaSYS/assets/61019188/d22feeef-f229-4995-8bf6-1f821cec8482

**Comment by a22jacka** [comment]
Seems like it works but only if you go in the opposite direction of the other element, could maybe be worth changing so that every direction beside the side where the other element is should work

**Comment by b22jonan** [comment]
> Seems like it works but only if you go in the opposite direction of the other element, could maybe be worth changing so that every direction beside the side where the other element is should work

for clarity, i went up into the object, then pressed down arrow to try and move down and away

**Comment by b22jonan** [comment]
never mind, chrome just didnt cleare cache when i told it to do so, changes did in fact work

**Review by b22jonan — APPROVED** [review]
changes work, can now move away with arrow keys

**Review by a22solmi — CHANGES_REQUESTED** [review]
Looks good but please remove the console logs and comments.

**Review by b22jonan — APPROVED** [review]
tested moving into another entity from all 4 directions, could then move in all other directions except into the entity. also tested moving into a corner between two other entities, did not get stuck there either.

**Pull request merged**
