### PR TITLE
G1 2023 v2 #13221

### PR DESCRIPTION
**Pull request by b21phiro**
Pop out function disabled in dugga diagram. #13221.

NOTE: Accidently committed for black arrow.

### CODE REVIEW

**Review by d21matbo — CHANGES_REQUESTED** [review]
This does not exactly solve the issue...

For starters, diagram_dugga previously worked by getting information from the JSON string in the database table 'variant', where it only loads the notations used for the current dugga, i.e. ER and UML. Now everything is loaded which is not correct.

If we overlook the above part the following things does not work 
1. The changes both affect diagram.php and diagramdugga
2. All notations show untill one specific is selected from the pop-out
3. The state-start and state-stop are always visible
4. After selecting the state-start/stop from the pop-out it is not possible to change back
5. It is possible to have multiple pop-out windows show at the same time (see figure)
image

**Comment by d21matbo** [comment]
This is the JSON part previously used to dynamically create the pop-out windows for diagram_dugga; {"type":"md","filelink":"HTML_Ex1.txt","gType":"md","gFilelink":"HTML_Ex1.txt","diagram_File":"example_ER.json","diagram_type":{"ER":true,"UML":true},"extraparam":"","notes":"","submissions":[{"type":"pdf","fieldname":"","instruction":""}],"errorActive":true}

**Comment by a21oligu** [comment]
I've done some changes that should be reviewed @d21matbo.

**Review by d21matbo — CHANGES_REQUESTED** [review]
#### From previous review:
1. The changes both affect diagram.php and diagramdugga (Might acually be better like this)
2. ~~All notations show untill one specific is selected from the pop-out~~
3. The state-start and state-stop are always visible
4. After selecting the state-start/stop from the pop-out it is not possible to change back
5. ~~It is possible to have multiple pop-out windows show at the same time~~

#### New: 
6. The Placements of the pop-outs doesn't match with the buttons (depends on screen size)

Points 3 and 4 needs fixing, 1 and 6 are less important

**Pull request merged**
