### PR TITLE
Swimlane not show in mac safari

### PR DESCRIPTION
**Pull request by a18danli**
@a19samke

### CODE REVIEW

**Comment by a18danli** [comment]
If you want to try, use the following example:
navigator.venor == "Google Inc."

DrawSwimlane will not if using safari browser and the arrows will be hidden.

**Review by a19frelu — APPROVED** [review]
I followed your example by changing the navigator.vendor to "Google Inc." and back to "Apple Computer, Inc." and it seems to work as intended when I tested it in the Chrome, Firefox, Opera, Brave and Safari browsers. 
The swimlanes are now visible in every tested browser but Safari.
Good job.

**Review by a19danla — APPROVED** [review]
Seens to be working on pc. Tried changing so it doesn't show up on Chrome and it doesn't but still shows on Firefox

**Review by b19wilfo — APPROVED** [review]
Tested with chrome and firefox and it works.

**Pull request merged**
