### PR TITLE
Resulted filtering drop-down out of position been fixed #7091

### LINKED ISSUE #7091: Resulted filtering drop-down out of position
After this weeks merge the filter drop-down is still out of position. When hovering from icon to drop-down a gap between them will close the drop-down.

### PR DESCRIPTION
**Pull request by a16hiwah**
test link; https://a16hiwah.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732
bild

efter
bild

### CODE REVIEW

**Comment by a16hiwah** [comment]
@c17julka 
now is working on both Desktop and on mobile

mobile(Samsung)
bild

**Comment by a16hiwah** [comment]
@c17julka 
now is working on both Desktop and  mobile.

**Comment by a16hiwah** [comment]
@c17julka
 but it works very well and changes will not affect other function.

**Comment by c17julka** [comment]
@a16hiwah No. The issue has not been solved, and icons / the searchbar are no longer styled correctly.

**Comment by a16hiwah** [comment]
@c17julka 
you can test it now, in the mobile you have to press and hold drop-down for 3 sec ,then you be allowed to se dropdown menu 
OBS! if you have better solution write it as Comment.
image

**Pull request merged**
