### PR TITLE
G2 2023 v5 issue#13744 Update class diagram Fileed.svg to include input data in methods

### PR DESCRIPTION
**Pull request by a21oscgu**
- Added new version (fileedservice.svg)
- Deleted old version (Fileed.svg)

### CODE REVIEW

**Review by c21alest — CHANGES_REQUESTED** [review]
@a21oscgu I can't find the function `} else if (strcmp($opt, "SAVEFILE") === 0)` { (line 144)  in your class diagram. And It looks like you've made the test description md and that one is also missing SAVEFILE.

**Comment by a21oscgu** [comment]
I did only translate what I received yesterday @c21alest. So should I go back and fill in?

**Comment by c21alest** [comment]
Yes please!

**Comment by c21alest** [comment]
Yes please!

**Comment by c21alest** [comment]
Yes please!

**Comment by c21alest** [comment]
Yes please!

**Review by a20fanma — CHANGES_REQUESTED** [review]
Missing the include_once: shared/sessions.php and shared/basic.php. Otherwise it looks good.

**Review by a20fanma — APPROVED** [review]
Looks good

**Comment by d21erisu** [comment]
nice

**Pull request merged**
