### PR TITLE
Issue #5533 Pull Request

### PR DESCRIPTION
**Pull request by a17oscno**
Test the result page for filtering out the different headers and when you filter out a Moment (and not a sub-moment like a test/dugga) then all of that moments sub-categories should also be filtered out.

### CODE REVIEW

**Comment by c17johha** [comment]
#5533

**Comment by a17oscno** [comment]
https://a17oscno.gruppb.webug.his.se:20002/DuggaSys/resulted.php?cid=2&coursevers=97732 
Link to the site that should be used when testing

**Comment by a17amama** [comment]
Code works fine and follows standard

**Comment by a17oscno** [comment]
Fixed it by removing unnecesary console.logs that displayed data.

**Comment by a17amama** [comment]
Code works fine and follows standard

**Pull request merged**
