### PR TITLE
CodeViewer #470, Part 1

### PR DESCRIPTION
**Pull request by a13erisc**
This is a very difficult issue, which I've decided to split up into parts. This part will at least implement a new border next to the existing codeborder which holds buttons for each codeblock. See issue #470 for more.

### CODE REVIEW

**Comment by HGustavs** [comment]
Im thinking we can leave this issue as a "stretch goal", there are more pressing issues to attend to.
If we run out of other issues to work with, we can come back to this issue.

**Comment by f12danjo** [comment]
Looking good. Like you said, it adds a side border where "+"-buttons can be added in the future. Fixed a minor thing so your code follows the code standard: The first bracket of a function is supposed to be on a new line.

**Comment by a13alfbe** [comment]
* There is no need to use float:right when the element is absolutely positioned.
* I found that the height of the buttonborder isn't 100% of it's parent when you scroll the content of the codebox.

**Comment by f12danjo** [comment]
We will close this because, like HGustavs wrote, we should concentrate on other, more high priority issues. If this were to be implemented again, do a new branch from the weekly branch so it's up to date.

**Pull request closed without merging**
