### PR TITLE
Codeviewer file extension filtering

### PR DESCRIPTION
**Pull request by b16johso**
https://github.com/HGustavs/LenaSYS/issues/6951

### CODE REVIEW

**Comment by a17andby** [comment]
Someone strange conflicts here. Can you check what code is yours @b16johso so I can review this.

**Comment by b16johso** [comment]
Everything looks fine to me? Can't find anything strange

**Comment by a17andby** [comment]
Screenshot from 2019-05-13 16-50-50
Screenshot from 2019-05-13 16-51-11

**Comment by a17andby** [comment]
not sure what is your code or not

**Comment by b16johso** [comment]
This bit is the code modified/added by the branch to be merged from
image

**Pull request merged**
