### PR TITLE
Fixed behavior and visuals for ´Edit Course Version´,  ´New Course Version´ and ´Edit Section´ #14675

### PR DESCRIPTION
**Pull request by a20jonda**
´Edit Course Version´
image
Non filled fields appear neutral but disables Submit with exception of `message of the day`

´New Course Version´
image

´Edit Section´
image
image

### CODE REVIEW

**Comment by a20jonda** [comment]
#14675

**Comment by a22diako** [comment]
Skärmbild 2024-04-24 205205

when form is empty no message appears to guide the user, this could save them time on the form filling. Not sure if this was apart of the issue, just a thought. 

Skärmbild 2024-04-24 205249
Message appears when the deadline date is before the start date- nice job. 

Skärmbild 2024-04-24 205516
Message appears when the user have written more than 50 symbols. Obs, only after the 50 symbols have been written. Says nothing about what symbols are allowed to use AND how many before. 

Skärmbild 2024-04-24 210246
Looks good, valid messages! Very nice.

**Review by a22diako — COMMENTED** [review]
Skärmbild 2024-04-24 205205
when form is empty no message appears to guide the user, this could save them time on the form filling. Not sure if this was apart of the issue, just a thought.


Skärmbild 2024-04-24 205249
 Message appears when the deadline date is before the start date- nice job.


Skärmbild 2024-04-24 205324
Message appears when the user have written more than 50 symbols. Obs, only after the 50 symbols have been written. Says nothing about what symbols are allowed to use AND how many before.


Skärmbild 2024-04-24 210246
Looks good, valid messages! Very nice.

**Comment by a20jonda** [comment]
image
image

**Comment by a20jonda** [comment]
### popup forms outside of sectioned.php are part of another issue.

**Review by a22marca — APPROVED** [review]
The input validation seems to work properly, a few new issues might be needed. I have spoken to issue responsible about this.

Good to merge.

**Comment by d22mikwe** [comment]
LGTM!

**Pull request merged**
