### PR TITLE
fixed element delete function

### PR DESCRIPTION
**Pull request by a22vioja**
The problem was that delete button area was covering the element area because of the wrong “deleteBtnX” callcullation. 

I changed the “deleteBtnX” calculation. I added 5 pixels to the X-coordinate of the selected element's right edge (highX) to position the delete button slightly to the right of the element.

With this change the delete button is outside the element area and it is not possible to delete it without pressing on the element, when delete button is visible. 

Screenshot 2024-04-12 at 10 05 36

### CODE REVIEW

**Comment by a22solmi** [comment]
Moving the cross does not solve the root issue. Please find a way to disable the delete without moving it.

**Review by a22solmi — CHANGES_REQUESTED** [review]
Moving the cross does not solve the root issue. Please find a way to disable the delete without moving it.

**Comment by a22vioja** [comment]
The problem was that delete button was always active on the right corner of an element, but not outside it. 

I changed the logic of checkDeleteBtn so that at first it would check if the mouse is over the delete button area and only after that it would check if delete button is active AND I added “!mouseOverElement” to
check if the mouse is not over an element. 

Now it is not possible to delete the element if it is not selected and the delete button is not active if element is not selected.

**Review by b22jonan — APPROVED** [review]
I tried to click where the "x" mark is suppose to be to delete it while its not selected, I couldnt get that to work, deleting while selected still works. Id say this works

**Review by a22solmi — APPROVED** [review]

**Pull request merged**
