### PR TITLE
Group3 2021 w18 10514

### PR DESCRIPTION
**Pull request by a18nadma**
Made the select cardinality bars better positioned and made it look prettier! Also added "none" to the empty option!

### CODE REVIEW

**Review by a19steis — APPROVED** [review]
Looks pretty, good job!

**Comment by a19nikbo** [comment]
If solving conflict, keep in mind that one of the drop down menus have been removed since you should only be able to have one cardinality per line.

**Comment by a19hammi** [comment]
Button moved when I pressed lol

**Review by a19karwa — APPROVED** [review]
LGTM! Cardinality dropdown-menu now has the options: N, 1 and none, instead of many, one and none.

**Pull request merged**
