### PR TITLE
Update swimlane layout

### PR DESCRIPTION
**Pull request by a18danli**
Co-Authored-By: a19samke <62887067+a19samke@users.noreply.github.com>

### CODE REVIEW

**Review by b18phika — APPROVED** [review]

**Review by a18willi — APPROVED** [review]
Looks good

**Comment by a20chrjo** [comment]
Changes does not appear to work in Chromium based browsers, please recheck your reviews

@b18phika @a18willi 

Swimlanes have different sizes #10275

**Comment by a19isada** [comment]
I think this is caused by different lengths in weeks. The demo-course has 9 weeks but the datorgrafik has 10 weeks and therefore looks weird. The other courses do not have anything added to them and that is probably why they are to the left. I do not know if this is something we should fix or if we should just leave it as it is? what do you say @a20chrjo?

**Comment by a20chrjo** [comment]
That is true for both Firefox and Chromium based browsers. Though the difference is vastly different between the two.

Swimlanes have different sizes #10275

I think this should be fixed for both browsers because it does not look nice when you have different sizes for the swimlane. Maybe with the exception for the course with less weeks. But then it should at least start at the same position to the left. If it's centered the size should be the same across the board and the course with less weeks should be resized to match the size of the courses with more weeks.

@a19isada

**Comment by b18phika** [comment]
@a20chrjo I think the issue that you displayed in your last comment is at least partially due to the fact that the first and fourth screenshot counting from the top, has two scrollbars on the right. One for the whole page, and I'm guessing that the other one exists because there are too many lanes to display them all at once. If I'm not mistaken this will affect the width of the parent element and thus also the width of the element since the width of the element is set to 70%. 

image

**Review by a18willi — CHANGES_REQUESTED** [review]
After looking into it further it seems that whenever you get the message "You either have no access or there isnt anthing undern this course" message the swimlanes gets really small, atleast in chromium based browsers.  Swimlanes size seems to only be determined by having 70% of the width as its parent object. Looking into the "statisticsSwimlanes" which seems to be the parent object containing "swimlaneSVG" may be needed.

**Review by b18phika — CHANGES_REQUESTED** [review]
For reasons already mentioned by @a18willi

**Comment by b18phika** [comment]
We (@a18willi and I) have pushed a fix to issue#10403 which will hide swimlanes when there aren't any duggor, so that part of the issue is resolved. 

The swim lanes diagram might still have different widths, due to a difference in the number of weeks, but the width of one week is now consistent, which is good. 

In our mind the swimlanes are still a bit too big, they're also not centered horizontally.  Whether or not that should be part of this issue or its own issue is a question for somebody else.

**Comment by a19isada** [comment]
The swimlanes should be resized to make them a bit smaller. Swimlanes not being centered horizontally will be its own issue.

**Comment by a19isada** [comment]
Old pull request. Has been renewed.

**Pull request closed without merging**
