### PR TITLE
Ds15 #541

### PR DESCRIPTION
**Pull request by a13chrju**
the "forgot password" link now switches UI when clicked. https://github.com/HGustavs/LenaSYS/issues/541

### CODE REVIEW

**Comment by b13alebr** [comment]
I think the new function "toggleloginnewpass()" should be placed i dugga.js in "shared"-folder instead of courseed.js in "DuggaSys"-folder.

**Comment by c13chrjo** [comment]
I agree with b13alebr and you should change the names of the placeholder names to something more professional. Like "Password" for password, "Username" for username and "mail@address.com" for mail.

**Comment by a13chrju** [comment]
now the code lays under the folder "shared". placeholder values changed aswell

**Comment by c13chrjo** [comment]
The framework for forgot password is now in place

**Pull request merged**
