### PR TITLE
G3 2024 v3 #14743 copy content from existing course version is fixed

### PR DESCRIPTION
**Pull request by a22ahmom**
After all the struggle with this issue, it seemed like the solution to the problem was to add another else if statement but for CPYVRS and fix a syntax error. So now it should be possible to successfully copy content from existing course version when creating a new course version. The tester can try this with multiple courses and see if there are no bugs or problems.

### CODE REVIEW

**Review by a22moamy — CHANGES_REQUESTED** [review]
# Changes requested
OBS! This test has been done by a mac user with Firefox

When trying to create a new version of a course I get these errors upon submitting the form:
Skärmavbild 2024-04-23 kl  11 06 37

I have tried filling the form with both dates that align with the copied versions dates and with random dates. For example, The form for Demo-course was filled like this:
Skärmavbild 2024-04-23 kl  11 06 27

After creating the version, the page is blank. This can be seen below:
Skärmavbild 2024-04-23 kl  11 06 43

Every other course I've tried this on shows the same result. 

## Potential new issue found
Tooltips for inputs in "New Course Version" form appear on the wrong row.
Skärmavbild 2024-04-23 kl  11 01 24

**Comment by a22ahmom** [comment]
The new issues you found are not part of this issue description. It concerns another issue.
Example of valid input format: 
Version ID: 111
Version Name: HT16
Start Date: 04/23/2024
End Date: 04//24/2024
MOTD: MOTD
Copy content from: ST20 - 52432

**Review by d22mikwe — COMMENTED** [review]
Windows 11
Microsoft Edge
Copying content from existing course version works as intended. even when self created content has been created it is copied from the existing version.

Some problems arose when copying from demo-course and webbutveckling -datrografik.
Some visual problems:
Old version:
image
New Version:
image

When trying to open a dugga or majority of the content in the copied version these errors appear:
Error
image
image

**Review by d22mikwe — CHANGES_REQUESTED** [review]
Windows 11
Microsoft Edge
Copying content from existing course version works as intended. even when self created content has been created it is copied from the existing version.

Some problems arose when copying from demo-course and webbutveckling -datrografik.
Some visual problems:
Old version:
image
New Version:
image

When trying to open a dugga or majority of the content in the copied version these errors appear:
Error
image
image

**Comment by a22moamy** [comment]
> The new issues you found are not part of this issue description. It concerns another issue. Example of valid input format: Version ID: 111 Version Name: HT16 Start Date: 04/23/2024 End Date: 04//24/2024 MOTD: MOTD Copy content from: ST20 - 52432

When trying the advised input:
Skärmavbild 2024-04-23 kl  13 17 39

When submitting the form:
Skärmavbild 2024-04-23 kl  13 18 58

The issue remains

**Comment by a22moamy** [comment]
Old weekly branch

**Pull request closed without merging**
