### PR TITLE
G1 2021 w17 #10434

### PR DESCRIPTION
**Pull request by b18jacha**
We have updated userAnswer and submission in testdata.sql with new hashes, passwords etc.

### CODE REVIEW

**Comment by e15marol** [comment]
If you want to test the new testdata you can simply check the inserts for userAnswer and see the corresponding url hashes and passwords, and copy paste the hash into the url to retrieve the saved dugga, and then the password to display it. First of all you'll have to reinstall lenasys with the new testdata, and view the data through mysql workbench.

**Review by a19kevkh — APPROVED** [review]
It works but some other stuff broke that isnt related to this issue. If we dont have anything in localstorage, variant doesnt get retrieved.

**Review by a19frebo — APPROVED** [review]
Insertion of the values works, however we found another issue that if we do not have a local storage and try to go in to a dugga through the hash we don't get a variant.

**Comment by a19rebsa** [comment]
We'll create a new issue for fixing the variant problem

**Pull request merged**
