### PR TITLE
Synced height and width expansion for issue#14828

### PR DESCRIPTION
**Pull request by a23ponek**
Fixed an half-done solution for the height and width expansion so they expand together "kinda", to get a perfect circle one must fix the expansion to fit but its possible. The room that the box takes up are also decreased by the size of the circle as requested.

However, some weird problems showed up. The changes creates a small circle like a blob on top of the init state circle which doesnt expand and stays idle. Also the uncommented code at line 9672 seem to affect the circle if its removed, even if its "outcommented" which is very odd. Also the final state circle appears exactly like the init state circle for some reason. I havent been able to locate where these anomalies come from, and the diagram.css and style.css seem to have nothing affecting this. 

Link to issue: 
https://github.com/HGustavs/LenaSYS/issues/14828

### CODE REVIEW

**Review by a22jacka — CHANGES_REQUESTED** [review]
You need to scale the parent div for the circle so that the whole circle is always visible

You also need to fix the issues with the white circle in the corner and final states appearing like initial states

**Review by a22jacka — APPROVED** [review]
Those immideate problems seem to have been fixed

Ready for proper testing

**Review by c22abdha — DISMISSED** [review]
resize up, resize left and the entire object moves. please change so the object doesnt move before resize

**Review by d22abdha — APPROVED** [review]
the elements can now be resized and move in different directions on the screeen

**Pull request closed without merging**
