### PR TITLE
Stretching arrow on segmented edge #14063

### PR DESCRIPTION
**Pull request by a21oligu**
Solved an issue where segmented arrows would strecth if pointing upwards. The underlying issue is not the arrow itself, but the "hitbox" of the SD entity being to large:

image

I would suggest that the "hitbox"-issue should be fixed in a new issue.

Solves issue #14063

### CODE REVIEW

**Review by a21aldsa — CHANGES_REQUESTED** [review]
The arrow is still stretched 

image

**Comment by a21oligu** [comment]
@a21aldsa the problem should now be fixed.

**Review by a21aldsa — CHANGES_REQUESTED** [review]
Now arrows going downward are longer than arrows going upward

image

**Comment by a21oligu** [comment]
made some changes @a21aldsa

**Pull request merged**
