### PR TITLE
G2 2023 v0 issue#13365

### PR DESCRIPTION
**Pull request by b21ricni**
Removed docx and pdf that has a MD version
Created sectionservice MD
Changed names to follow standards

### CODE REVIEW

**Comment by a19hakja** [comment]
Typo in the branch name, no worries though

**Comment by b21ricni** [comment]
You call it typo, i call it improvment

**Review by d21erisu — APPROVED** [review]
Great! [FRD_contribution_loginbox_service.md] is wack. Some other already merged md are also wack. Needs to be fixed later

**Comment by a19hakja** [comment]
improvement*

**Pull request merged**
