### PR TITLE
G2 2023 v0 issue#12969

### PR DESCRIPTION
**Pull request by c21axepe**
Created class diagram and text file to describe highscoreservice.php

### CODE REVIEW

**Comment by a19hakja** [comment]
This issue was also assigned to a20fanma, as of now only c21axepe stands as author. Is this intended?

**Comment by a20fanma** [comment]
> This issue was also assigned to a20fanma, as of now only c21axepe stands as author. Is this intended?

I think we forgot to add me (a20fanma). Do I need to add myself? If yes, how do I do that?

**Comment by a19hakja** [comment]
There is a function in Github desktop where you can add co-authors, I will wait with assigning reviewers until I see you both as authors :)

**Review by b21antbr — APPROVED** [review]
Looks good to my knowledge.

**Comment by a19hakja** [comment]
@a21ponkr awaiting your review

**Comment by a21ponkr** [comment]
Looks good

**Review by a21ponkr — APPROVED** [review]
Approved

**Pull request merged**
