### PR TITLE
Added toggleFeedback function and changed feedback area construction

### PR DESCRIPTION
**Pull request by a18osken**
Separated the accordion toggles for instructions and feedback into two different functions, toggleFeedback and toggleInstructions

### CODE REVIEW

**Review by a19rebsa — APPROVED** [review]
It works, good job!

**Review by a13zanal — CHANGES_REQUESTED** [review]
Works fine, except for rapport inlämning where it seems stuck

**Review by a13zanal — APPROVED** [review]
Now everything works great, good job!

**Review by a19rebsa — APPROVED** [review]
Nice!

**Pull request merged**
