### PR TITLE
G2 2023 v2  Present the logs in a usable format #13277 

### PR DESCRIPTION
**Pull request by a21jeaha**
Present the logs in a usable format #13277 

This issue is completed and pending review.

### CODE REVIEW

**Comment by b21kurar** [comment]
I would appreciate a more detailed description of your work in the pull request comment.
I can tell that a lot of work has been done, and would like an overview of what. 

Such as: Presentation of the tables in loglena6.db in different ways, the different tables have different representation. 
A dropdown menu to choose table

etc...

**Comment by b21kurar** [comment]
Pictures are welcome as well!

**Comment by a21jeaha** [comment]
Each table in the database file, located at the users root folder (https://cms.webug.se/root/"projektGroup"/students/"studentID"/log/) is presented through the file log.php. Which can be found in the folder /Shared.

The log tables can be chosen from a dropdown containing every table in the database, only one table at a time will be shown.

!https://user-images.githubusercontent.com/102600391/232444907-d3e22ab4-9d68-4a02-a8ed-8d20875bd377.png

**Review by d21erisu — APPROVED** [review]
I used 2 different accounts and logged in and pushed around. It logged and tracked some events, presented them. It seems to work! Works as intended i guess.

**Comment by a21jeaha** [comment]
@d21erisu @c21alest this issue was already resolved and merged, is there a reason i have been assigned to it?

**Pull request merged**
