### PR TITLE
Added outline

### PR DESCRIPTION
**Pull request by a19steis**
Made the selected lines display a shadow so we can more clearly see which lines are selected.

### CODE REVIEW

**Review by a19karwa — COMMENTED** [review]
It does make the marking of lines more clear for me, but I can not tell if it will make a difference 
for those who are colorblind, perhaps someone that is colorblind should test this aswell?

**Review by a18nadma — CHANGES_REQUESTED** [review]
A suggestion we recieved would be to have a dot or a small square in the middle of the line as an indication that the line is being selected.

**Review by a19vikth — APPROVED** [review]
Looks good :)

**Comment by a19hammi** [comment]
Closed until later

**Pull request closed without merging**
