### PR TITLE
issue#12697

### PR DESCRIPTION
**Pull request by b21hamwe**
Klassdiagram & textfil.

### CODE REVIEW

**Review by d21erisu — CHANGES_REQUESTED** [review]
The variables: querystring, stmt, errror, result, accessString, querystringz, passwordquery. Are missing?

Methods: execute(), rowCount(),password_verify(), errorInfo() is inside checklogin?, made to be
microservices in the future but might be "same" as of now. 

In textfile add: Input, output. Should be very clear.

**Review by d21erisu — APPROVED** [review]
Good job! I am satisfied.

**Review by c21alest — COMMENTED** [review]
Im satisfied to, great job!

**Comment by b21kurar** [comment]
issue #12967

**Pull request merged**
