### PR TITLE
G1 2023 V2 #13345

### PR DESCRIPTION
**Pull request by d21matbo**
Solved the problem of overlapping the selected element by removing a continue in the loop for exactly that element. It is no longer possible to place a element under the selected one.

### CODE REVIEW

**Review by a21aldsa — CHANGES_REQUESTED** [review]
This issue is only solved when trying to place an element behind a UML element, For all other elements it is still very much possible to overlap by first selecting an element and then clicking just outside the element. This means you can freely overlap any element behind any element except UML, this issue is therefore not solved.

image

**Comment by a21aldsa** [comment]
Here's an example of me placing an IE element behind a ER, by selecting it first.

image

**Comment by d21matbo** [comment]
These changes should also stop IE Entites from overlapping when no or another element is selected

**Review by a21aldsa — APPROVED** [review]
Looks good to me; it seems impossible to spawn elements behind other elements, no matter the type or where you click. Good job.

**Pull request merged**
