### PR TITLE
G2 2023 v4 issue #13532 Created test API

### PR DESCRIPTION
**Pull request by c21alest**
Related to #13532 

Created test.php file in /Shared folder which helps testing services.
This includes 3 tests.
* Assert test (Compare two values)
* Login test - Check if login credentials are valid
* Call service - With the help of parameters like opt some service functionality can be executed

Session.php have been modified to allow checkLogin() with POST

----------------------------------------------------------
## Example on how to run this test from another file:

include_once "../Shared/test.php";

$testData = array(
    'value1' => 'test',
    'value2' => 'test',
    'service' => 'https://cms.webug.se/root/G2/students/c21alest/LenaSYS/DuggaSys/courseedservice.php',
    'serviceData' => serialize(array( // Data that service needs to execute function
        'opt' => 'NEW',
        'username' => 'usr',
        'password' => 'pass',
    )),
    'test1Debug' => false, // If true more information of test will be displayed
    'test2Debug' => true,
    'test3Debug' => true,
);

testHandler($testData, false); // 2nd argument true = prettyprint (HTML) false = raw JSON, no debug mode is avalible when using prettyprint

----------------------------------------------------------

### To test
* I have not yet checked that a service call makes any changes to the database, just that the service marks it as a success.
* Check that different login types are working (student, teacher etc) and that a student can't perform any activities that requires a teacher or admin.
* Test that JSON format can be compared in the assert test.
* Is it clear how to use the test or is any further documentation needed?
* Session.php has been modified so further testing might be needed to make sure that this won't brake anything

### CODE REVIEW

**Comment by b21kurar** [comment]
I think it would be more preferable to let the testdesigner decide when to call the different functions (such as `assertEqualsTest`), that way it would land more in line to the discussions made in issue #13062 . That would make the `testHandler` unnecessary as of now. 

I think that a good way of doing this is letting the test designer send an array of all relevant values to each function and then letting them decide the order of execution.

And also, future issue, adding an ignore list for the response JSON.

**Comment by b21kurar** [comment]
An issue I am encountering is trying to create a new course via a test case. It doesn't seem to work. I have even added new courses by hand and can't get the test case page to show the new courses
image
image

**Comment by b21kurar** [comment]
The testcase used:
image

**Comment by b21kurar** [comment]
I realize that it may be because I am creating entries in my own database, while `courseedservice` only checks the master database...

**Comment by b21kurar** [comment]
That means that for testing, we need a way to redirect which database is to be used

**Comment by b21kurar** [comment]
Since the PDO connection is made via a global variable, maybe it could be as easy as modifying it? 
image
I believe however that this could be a separate issue

**Comment by b21kurar** [comment]
Wait, nevermind, those values are set in `coursesyspw.php` and should connect to the correct database. I am unsure of how it is set up

**Comment by c21alest** [comment]
https://cms.webug.se/root/G2/students/b21kurar/LenaSYS/DuggaSys/courseedservice.php returns the new courses you created

**Comment by b21kurar** [comment]
> 

This is my result when viewing that page: 
image
I search for `test-` but no matches are found. 

Can't find it in the response tab either:
image

They are however existing in the database:
image

**Comment by c21alest** [comment]
> This is my result when viewing that page: image I search for `test-` but no matches are found.
> 
> Can't find it in the response tab either: image
> 
> They are however existing in the database: image

Created and Activeversion is null, can this be the problem? I'll try to reset my LenaSys and create my own courses.

**Comment by b21kurar** [comment]
> > This is my result when viewing that page: image I search for `test-` but no matches are found.
> > Can't find it in the response tab either: image
> > They are however existing in the database: image
> 
> Created and Activeversion is null, can this be the problem? I'll try to reset my LenaSys and create my own courses.
They are now available in the service, the session might have logged me out without me knowing. However still not available in the test case. Will be trying some stuff!
image

**Pull request merged**
