### PR TITLE
Fix: Saving what mode you're in doesn't quite work #7152

### PR DESCRIPTION
**Pull request by a17jacsv**
**Issue: #7152** (related to issue: #6933 and #7089)

* When refreshing the page the chosen toolbar is loaded in from the local storage and works as it is expected to do.

* Fixed functions to remove duplicated code and stuff.

* Changed key binding to two separate key bindings to prevent duplicate switches.

**Co-author: @a16jenja**

### CODE REVIEW

**Comment by a16jenja** [comment]
We tried to resolve some conflicts with another branch and that's probably why it doesn't work right now, we will look into it.

**Comment by a16jenja** [comment]
@a14oscna We fixed the merging issues again.

**Comment by a14oscna** [comment]
Great, I will proceed to merge now and before you guys do anything else I want you to check that everything works on the group branch!

**Comment by a17jacsv** [comment]
> Great, I will proceed to merge now and before you guys do anything else I want you to check that everything works on the group branch! @a16jenja @a17jacsv

it seems like some menu items are added since we started with our recent PR which caused some visual concerns. We'll create a new issue fixing them immediately.

**Pull request merged**
