### PR TITLE
G3 2020#9053 is solved

### PR DESCRIPTION
**Pull request by a18mahkh**
- if you edit an announcement then the announcement is marked as 'edited' at the bottom of the announcement card

### CODE REVIEW

**Comment by a18mahkh** [comment]
The issue was to mark the announcement if it's edited which is solved. Look at figure below:
Anteckning 2020-05-14 195840


And if an announcement is edited means it's renewed and that's why the notification counter will be visible.

@a18felen

**Comment by a18felen** [comment]
In this branch you have made a commit saying "notification icon added" and "if an announcement is created or updated you get an notification" so with that you could at least implement a working notification instead of creating something that will need an issue later.

Basically, if the announcement has been viewed remove the notification.

**Comment by a18mahkh** [comment]
Those commits are from other branches that this was built on

**Comment by a18mahkh** [comment]
Actually you have to click on the announcement card for notification counter to be gone

**Comment by a18jenro** [comment]
"Those commits are from other branches that this was built on".
@a18mahkh Try to avoid building branches on top of other ones.

**Pull request merged**
