### PR TITLE
added documents

### PR DESCRIPTION
**Pull request by d21erisu**
Created functional requirements for showDuggaservice.php AND a template for creating functional requirements

### CODE REVIEW

**Comment by b21ricni** [comment]
I was part of the creation/issue so i can not review this

**Review by b21tilbe — APPROVED** [review]
The general layout looks good and the requirements seems correct. I approve this commit

**Comment by b21ricni** [comment]
Create new issue to make this to a MD doc

**Comment by d21erisu** [comment]
i created new issue

**Pull request merged**
