### PR TITLE
G1 2021 W21 #10660

### PR DESCRIPTION
**Pull request by b18jacha**
Added a button to start a new submission on every dugga. 

**To test:** 
- Go to any dugga and save something, then press the **New submission** button.

### CODE REVIEW

**Comment by e15marol** [comment]
To test the load dugga button, simply test it by loading a dugga which is the same duggatype in which you are in, so if you're inside Biträkningsdugga 1, get a hash from a saved Biträkningsdugga 1 and try and load it. It should only work for the duggas that correspond to the same dugga types. So the hash that works for loading a dugga inside Biträkningsdugga 1, should not work when trying to load it in Biträkningsdugga 2 for example.

**Review by a19gusba — CHANGES_REQUESTED** [review]
do not use ajax calls outside the AJAXService function. Figure out what the new submission should contain, what should it do, what things should be added/removed. The variant is already saved in local storage so the item does not need to be removed and replaced. The new submission should not save so do not use the "SAVDU" opt. Why is the setPassword function called?

**Comment by a19gusba** [comment]
image
why not just use the variantValue variable? What is the point of storing a variable in local storage to get in 2 lines below

**Comment by e15marol** [comment]
> image
> why not just use the variantValue variable? What is the point of storing a variable in local storage to get in 2 lines below

The variantValue came out as undefined when implementing the solution, so it had to be temporarily stored and then retrieved.

**Comment by a19gusba** [comment]
image
image

This creates problems since it doesnt use our "localStorageHandler()" function that is used to correctly handle values in local storage

**Comment by a19gusba** [comment]
image
image

Using save dugga option when dugga should not be saved should be avoided!

**Review by a17alfja — CHANGES_REQUESTED** [review]
When new variant when pressing save is fixed, the solution does not work for me
image
(solution in showduggaservice.php) 
I think you can reduce the number of (new) ajax calls by sending values as parameter. eg.
image

**Comment by a19gusba** [comment]
> > image
> > why not just use the variantValue variable? What is the point of storing a variable in local storage to get in 2 lines below
> 
> The variantValue came out as undefined when implementing the solution, so it had to be temporarily stored and then retrieved.

image
image

Tried using console.log to check if this was the case but i would get access to the variable before and after the if statement, doesnt really see how an if statement could turn the variable to undefined unless the "confirm()" function somehow manually changed the variable

**Comment by a19gusba** [comment]
does the ajax call really need to be used in "newSubmission()"?

**Review by a19gusba — CHANGES_REQUESTED** [review]
the "New submission" button should be located on the login screen to a dugga, not the dugga itself. The function "newSubmission" still uses an ajax call

**Review by a19rebsa — APPROVED** [review]
It works as described!

**Pull request merged**
