### PR TITLE
G2 2023 v1 issue#13095

### PR DESCRIPTION
**Pull request by a21jeaha**
issue#13095 Investigate potential microservices in fileedservice.php
is ready to be reviewed

### CODE REVIEW

**Comment by a19hakja** [comment]
Assigning a reviewer :)
Please tag pull-requests with our label "Group-2-2023" so that we don't miss anything

**Review by b21antbr — CHANGES_REQUESTED** [review]
Looks good to my knowledge, check out typos at row 15, Delite-> delete, 53, filers->filters, 67, mentiond->mentioned, 81, than->then.

**Comment by a21jeaha** [comment]
changes made

**Review by b21antbr — APPROVED** [review]
Looks good, well done!

**Pull request merged**
